import {ArrowDown,ArrowUp,Plus,Trash} from "@phosphor-icons/react";
import {FormEvent} from "react";

export type Condition={field:"source"|"text";operator:"equals"|"contains";value:string};
export type Step={kind:"notification"|"skill";title:string;body:string;skill:string};
export type Draft={id?:string;version?:number;name:string;triggerKind:string;schedule:string;conditions:Condition[];steps:Step[];enabled:boolean};

type Props={draft:Draft;skills:{id:string;description:string}[];busy:boolean;onChange:(draft:Draft)=>void;onPreview:()=>void;onClose:()=>void;onSubmit:(event:FormEvent)=>void};
const notification=():Step=>({kind:"notification",title:"",body:"",skill:"weekly-review"});

export function AutomationBuilder({draft,skills,busy,onChange,onPreview,onClose,onSubmit}:Props){
  const updateCondition=(index:number,value:Condition)=>onChange({...draft,conditions:draft.conditions.map((item,i)=>i===index?value:item)});
  const updateStep=(index:number,value:Step)=>onChange({...draft,steps:draft.steps.map((item,i)=>i===index?value:item)});
  const moveStep=(index:number,direction:-1|1)=>{const target=index+direction;if(target<0||target>=draft.steps.length)return;const steps=[...draft.steps];[steps[index],steps[target]]=[steps[target],steps[index]];onChange({...draft,steps})};
  const addStep=()=>onChange({...draft,steps:[...draft.steps,notification()]});
  return <form className="automation-builder" onSubmit={onSubmit} aria-label={draft.id?"Edit automation":"Create automation"}>
    <header><div><h2>{draft.id?"Edit automation":"Build an automation"}</h2><p>Compose a trigger, optional conditions, and ordered actions. Preview before saving.</p></div><button type="button" className="secondary" onClick={onClose}>Close</button></header>
    <div className="builder-grid"><fieldset><legend>1 · Trigger</legend><label>Name<input required maxLength={300} value={draft.name} onChange={event=>onChange({...draft,name:event.target.value})}/></label><label>Starts when<select value={draft.triggerKind} onChange={event=>onChange({...draft,triggerKind:event.target.value})}><option value="manual">Run manually</option><option value="schedule">Schedule matches</option><option value="capture">Capture is created</option></select></label>{draft.triggerKind==="schedule"&&<label>Cron schedule<input required placeholder="0 8 * * 0" value={draft.schedule} onChange={event=>onChange({...draft,schedule:event.target.value})}/><small>Minute, hour, day, month, weekday. Use a number or *.</small></label>}</fieldset>
      <fieldset><legend>2 · Conditions</legend><p className="field-help">All conditions must match. Capture conditions inspect only its source and text.</p>{draft.conditions.map((condition,index)=><div className="condition-row" key={index}><label>Field<select aria-label={`Condition ${index+1} field`} value={condition.field} onChange={event=>updateCondition(index,{...condition,field:event.target.value as Condition["field"]})}><option value="text">Capture text</option><option value="source">Capture source</option></select></label><label>Match<select aria-label={`Condition ${index+1} operator`} value={condition.operator} onChange={event=>updateCondition(index,{...condition,operator:event.target.value as Condition["operator"]})}><option value="contains">Contains</option><option value="equals">Equals</option></select></label><label>Value<input required maxLength={500} value={condition.value} onChange={event=>updateCondition(index,{...condition,value:event.target.value})}/></label><button type="button" className="icon-button" aria-label={`Remove condition ${index+1}`} onClick={()=>onChange({...draft,conditions:draft.conditions.filter((_,i)=>i!==index)})}><Trash/></button></div>)}<button type="button" className="secondary" disabled={draft.conditions.length>=10} onClick={()=>onChange({...draft,conditions:[...draft.conditions,{field:"text",operator:"contains",value:""}]})}><Plus/>Add condition</button></fieldset>
    </div>
    <fieldset className="step-builder"><legend>3 · Ordered actions</legend>{draft.steps.map((step,index)=><article className="step-card" key={index}><header><strong>Step {index+1}</strong><div><button type="button" className="icon-button" disabled={index===0} aria-label={`Move step ${index+1} up`} onClick={()=>moveStep(index,-1)}><ArrowUp/></button><button type="button" className="icon-button" disabled={index===draft.steps.length-1} aria-label={`Move step ${index+1} down`} onClick={()=>moveStep(index,1)}><ArrowDown/></button><button type="button" className="icon-button" disabled={draft.steps.length===1} aria-label={`Remove step ${index+1}`} onClick={()=>onChange({...draft,steps:draft.steps.filter((_,i)=>i!==index)})}><Trash/></button></div></header><label>Action<select value={step.kind} onChange={event=>updateStep(index,{...step,kind:event.target.value as Step["kind"]})}><option value="notification">Create notification</option><option value="skill" disabled={index!==draft.steps.length-1||draft.steps.some((item,i)=>item.kind==="skill"&&i!==index)}>Run managed skill (final step)</option></select></label>{step.kind==="notification"?<div className="step-fields"><label>Title<input required maxLength={500} value={step.title} onChange={event=>updateStep(index,{...step,title:event.target.value})}/></label><label>Body<textarea value={step.body} onChange={event=>updateStep(index,{...step,body:event.target.value})}/></label></div>:<label>Skill<select value={step.skill} onChange={event=>updateStep(index,{...step,skill:event.target.value})}>{skills.map(skill=><option key={skill.id} value={skill.id}>{skill.id} — {skill.description}</option>)}</select></label>}</article>)}<button type="button" className="secondary" disabled={draft.steps.length>=10||draft.steps.some(step=>step.kind==="skill")} onClick={addStep}><Plus/>Add action</button></fieldset>
    <label className="toggle-line"><input type="checkbox" checked={draft.enabled} onChange={event=>onChange({...draft,enabled:event.target.checked})}/>Enable immediately</label><footer><button type="button" className="secondary" disabled={busy} onClick={onPreview}>Preview</button><button className="primary" disabled={busy}>{busy?"Saving…":draft.id?"Save changes":"Create automation"}</button></footer>
  </form>;
}
