"use client";

import {FormEvent,useEffect,useState} from "react";
import {ArrowClockwise,ArrowLeft,ArrowRight,Circle,Clock,Copy,Lightning,Pause,PencilSimple,Play,Plus,Trash,Warning} from "@phosphor-icons/react";
import {ModuleShell} from "../components/ModuleShell";

type Automation={id:string;name:string;trigger_kind:"manual"|"schedule"|"capture";schedule:string|null;action_kind:"notification"|"skill";config_json:string;enabled:number;last_run_at:string|null;version:number};
type Run={id:string;state:string;job_id:string|null;started_at:string;finished_at:string|null;output_json:string|null;error:string|null};
type Metrics={total:number;states:Record<string,number>;lastRun:{state:string;startedAt:string;finishedAt:string|null;error:string|null}|null};
type Condition={field:"source"|"text";operator:"equals"|"contains";value:string};
type Draft={id?:string;version?:number;name:string;triggerKind:string;schedule:string;actionKind:string;title:string;body:string;skill:string;conditions:Condition[];enabled:boolean};
type Preview={trigger:string;conditions:Condition[];action:string;enabled:boolean};
const empty:Draft={name:"",triggerKind:"manual",schedule:"",actionKind:"notification",title:"",body:"",skill:"weekly-review",conditions:[],enabled:true};
const request=async(path:string,init?:RequestInit)=>{const response=await fetch(path,init),data=await response.json();if(!response.ok)throw new Error(data.error?.message||"Request failed");return data};
const when=(value:string|null)=>value?new Date(value).toLocaleString():"Never";
const payload=(draft:Draft)=>({id:draft.id,version:draft.version,name:draft.name,triggerKind:draft.triggerKind,schedule:draft.triggerKind==="schedule"?draft.schedule:null,actionKind:draft.actionKind,config:draft.actionKind==="notification"?{title:draft.title||draft.name,body:draft.body,conditions:draft.conditions}:{skill:draft.skill,input:{},conditions:draft.conditions},enabled:draft.enabled});
const editDraft=(item:Automation):Draft=>{const config=JSON.parse(item.config_json);return {id:item.id,version:item.version,name:item.name,triggerKind:item.trigger_kind,schedule:item.schedule||"",actionKind:item.action_kind,title:config.title||item.name,body:config.body||"",skill:config.skill||"weekly-review",conditions:config.conditions||[],enabled:!!item.enabled}};

export default function AutomationsPage(){
  const [automations,setAutomations]=useState<Automation[]>([]),[selected,setSelected]=useState<Automation|null>(null),[runs,setRuns]=useState<Run[]>([]),[metrics,setMetrics]=useState<Metrics|null>(null),[skills,setSkills]=useState<{id:string;description:string}[]>([]);
  const [tab,setTab]=useState("Runs"),[editing,setEditing]=useState(false),[draft,setDraft]=useState<Draft>(empty),[preview,setPreview]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const load=()=>request("/api/v1/automations").then(data=>{setAutomations(data.automations);setSelected(current=>current?data.automations.find((item:Automation)=>item.id===current.id)||null:null)}).catch(reason=>setError(reason.message));
  const loadRuns=(id:string)=>request(`/api/v1/automations/${id}/runs`).then(data=>{setRuns(data.runs);setMetrics(data.metrics)}).catch(reason=>setError(reason.message));
  useEffect(()=>{load();request("/api/v1/skills").then(data=>setSkills(data.skills)).catch(()=>{})},[]);
  useEffect(()=>{if(selected)loadRuns(selected.id)},[selected?.id]);
  useEffect(()=>{if(!selected)return;const source=new EventSource(`/api/v1/automations/${selected.id}/events`);source.addEventListener("snapshot",event=>{const data=JSON.parse((event as MessageEvent).data);setRuns(data.runs);setMetrics(data.metrics)});return()=>source.close()},[selected?.id]);
  function openEditor(value:Draft){setDraft(value);setPreview(null);setError("");setEditing(true)}
  async function inspect(){setBusy(true);setError("");try{setPreview(await request("/api/v1/automations/preview",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload(draft))}))}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  async function save(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{await request("/api/v1/automations",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(payload(draft))});setEditing(false);setDraft(empty);setPreview(null);await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  async function duplicate(item:Automation){const copy=editDraft(item);delete copy.id;delete copy.version;copy.name=`${copy.name} copy`;copy.enabled=false;openEditor(copy)}
  async function remove(item:Automation){if(!confirm(`Delete “${item.name}” and its run history?`))return;setBusy(true);setError("");try{await request(`/api/v1/automations/${item.id}?version=${item.version}`,{method:"DELETE"});setSelected(null);await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  async function toggle(item:Automation){setBusy(true);setError("");try{await request("/api/v1/automations",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({...payload(editDraft(item)),enabled:!item.enabled})});await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  async function run(item:Automation){setBusy(true);setError("");try{await request(`/api/v1/automations/${item.id}/runs`,{method:"POST"});await Promise.all([load(),loadRuns(item.id)])}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  async function runAction(runId:string,action:"cancel"|"retry"){setBusy(true);setError("");try{await request(`/api/v1/automations/${selected!.id}/runs/${runId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})});await loadRuns(selected!.id)}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}

  const editor=<form className="automation-builder" onSubmit={save} aria-label={draft.id?"Edit automation":"Create automation"}><header><div><h2>{draft.id?"Edit automation":"Build an automation"}</h2><p>Define the trigger and action, preview the exact behavior, then save.</p></div><button type="button" className="secondary" onClick={()=>setEditing(false)}>Close</button></header><div className="builder-grid"><fieldset><legend>1 · Trigger</legend><label>Name<input required maxLength={300} value={draft.name} onChange={event=>setDraft({...draft,name:event.target.value})}/></label><label>Starts when<select value={draft.triggerKind} onChange={event=>setDraft({...draft,triggerKind:event.target.value})}><option value="manual">Run manually</option><option value="schedule">Schedule matches</option><option value="capture">Capture is created</option></select></label>{draft.triggerKind==="schedule"&&<label>Cron schedule<input required placeholder="0 8 * * 0" value={draft.schedule} onChange={event=>setDraft({...draft,schedule:event.target.value})}/><small>Minute, hour, day, month, weekday. Use a number or * for each field.</small></label>}</fieldset><fieldset><legend>2 · Action</legend><label>Action type<select value={draft.actionKind} onChange={event=>setDraft({...draft,actionKind:event.target.value})}><option value="notification">Create notification</option><option value="skill">Run managed skill</option></select></label>{draft.actionKind==="notification"?<><label>Title<input required value={draft.title} placeholder={draft.name||"Notification title"} onChange={event=>setDraft({...draft,title:event.target.value})}/></label><label>Body<textarea value={draft.body} onChange={event=>setDraft({...draft,body:event.target.value})}/></label></>:<label>Skill<select value={draft.skill} onChange={event=>setDraft({...draft,skill:event.target.value})}>{skills.map(skill=><option key={skill.id} value={skill.id}>{skill.id} — {skill.description}</option>)}</select></label>}<label className="toggle-line"><input type="checkbox" checked={draft.enabled} onChange={event=>setDraft({...draft,enabled:event.target.checked})}/>Enable immediately</label></fieldset></div>{preview&&<section className="automation-preview" aria-live="polite"><strong>Preview</strong><span>{preview.trigger}</span><ArrowRight/><span>{preview.action}</span><em>{preview.enabled?"Enabled":"Saved paused"}</em></section>}<footer><button type="button" className="secondary" disabled={busy} onClick={()=>void inspect()}>Preview</button><button className="primary" disabled={busy}>{busy?"Saving…":draft.id?"Save changes":"Create automation"}</button></footer></form>;

  if(editing)return <ModuleShell active="Automations" title="Automation builder">{error&&<div className="warning-text" role="alert"><Warning/>{error}</div>}{editor}</ModuleShell>;
  if(selected)return <ModuleShell active="Automations" title={selected.name} action={<button className="secondary" onClick={()=>setSelected(null)}><ArrowLeft/>Automations</button>}>
    {error&&<div className="warning-text" role="alert"><Warning/>{error}</div>}<div className="workspace-head"><div><h2>{selected.name}</h2><p>{selected.action_kind} · {selected.trigger_kind}{selected.schedule?` · ${selected.schedule}`:""}</p></div><span className={`status-live ${selected.enabled?"active":""}`}><Circle weight="fill"/>{selected.enabled?"Enabled":"Paused"}</span></div>
    <nav className="workspace-tabs" aria-label="Automation details">{["Runs","Logs","Metrics","Definition"].map(item=><button className={tab===item?"active":""} onClick={()=>setTab(item)} key={item}>{item}</button>)}</nav><div className="automation-workspace"><section>
      {tab==="Runs"&&(runs.length?runs.map(run=><article className="workspace-row" key={run.id}><Lightning/><span><strong>{run.id.slice(0,8)}</strong><small>{when(run.started_at)}</small></span><div className="run-actions"><em>{run.state}</em>{run.job_id&&["queued","running","cancelling"].includes(run.state)&&<button disabled={busy||run.state==="cancelling"} onClick={()=>void runAction(run.id,"cancel")}>Cancel</button>}{run.job_id&&run.state==="failed"&&<button disabled={busy} onClick={()=>void runAction(run.id,"retry")}><ArrowClockwise/>Retry</button>}</div></article>):<div className="empty-state"><Clock/><h3>No runs yet</h3><p>Run this automation manually or wait for its trigger.</p></div>)}
      {tab==="Logs"&&(runs.length?<pre className="terminal-view"><code>{runs.map(run=>`${when(run.started_at)} ${run.state}${run.error?` · ${run.error}`:run.output_json?` · ${run.output_json}`:""}`).join("\n")}</code></pre>:<div className="empty-state"><Clock/><h3>No logs yet</h3></div>)}
      {tab==="Metrics"&&<div className="metric-lines"><span><small>Total runs</small><strong>{metrics?.total||0}</strong></span><span><small>Completed</small><strong>{metrics?.states.completed||0}</strong></span><span><small>Failed</small><strong>{metrics?.states.failed||0}</strong></span><span><small>Last run</small><strong>{metrics?.lastRun?.state||"Never"}</strong></span></div>}
      {tab==="Definition"&&<div className="definition-card"><span><small>Trigger</small><strong>{selected.trigger_kind}{selected.schedule?` · ${selected.schedule}`:""}</strong></span><ArrowRight/><span><small>Action</small><strong>{selected.action_kind}</strong></span><pre><code>{JSON.stringify(JSON.parse(selected.config_json),null,2)}</code></pre></div>}
    </section><aside className="run-controls"><h3>Controls</h3><span>Last run: {when(selected.last_run_at)}</span><button className="primary" disabled={busy||!selected.enabled} onClick={()=>run(selected)}><Play/>Run now</button><button className="secondary" disabled={busy} onClick={()=>openEditor(editDraft(selected))}><PencilSimple/>Edit</button><button className="secondary" disabled={busy} onClick={()=>void duplicate(selected)}><Copy/>Duplicate</button><button className="secondary" disabled={busy} onClick={()=>toggle(selected)}>{selected.enabled?<><Pause/>Pause</>:<><Play/>Resume</>}</button><button className="danger-button" disabled={busy} onClick={()=>void remove(selected)}><Trash/>Delete</button></aside></div>
  </ModuleShell>;
  return <ModuleShell active="Automations" title="Automations" action={<button className="primary top-primary" onClick={()=>openEditor({...empty})}><Plus/>New automation</button>}><div className="module-header"><div><h2>Systems working in the background</h2><p>Build, preview, run, and inspect durable automations.</p></div></div>{error&&<div className="warning-text" role="alert"><Warning/>{error}</div>}<div className="automation-layout"><section><div className="list-title"><h3>Automations</h3><span>{automations.length} total</span></div><div className="automation-list">{automations.map(item=><article key={item.id}><span className={`automation-icon ${item.enabled?"active":"neutral"}`}><Lightning/></span><div><button className="automation-open" onClick={()=>setSelected(item)}><strong>{item.name}</strong><span>{item.action_kind} · {item.trigger_kind}</span></button><small>Last run: {when(item.last_run_at)}</small></div><em className={item.enabled?"active":"neutral"}><Circle weight="fill"/>{item.enabled?"Enabled":"Paused"}</em><button className="icon-button" aria-label={`Open ${item.name}`} onClick={()=>setSelected(item)}><ArrowRight/></button></article>)}{!automations.length&&!error&&<div className="empty-state"><Lightning/><h3>No automations</h3><p>Create a manual, scheduled, or capture-triggered automation.</p><button className="primary" onClick={()=>openEditor({...empty})}><Plus/>Build automation</button></div>}</div></section></div></ModuleShell>;
}
