"use client";

import {useState} from "react";
import {ArrowClockwise, ArrowLeft, ArrowRight, Check, Circle, Clock, Lightning, Pause, Play, Plus, Stop, Warning} from "@phosphor-icons/react";
import {ModuleShell} from "../components/ModuleShell";

const automations=[
  {name:"Stewie Channel Pipeline",state:"Running",detail:"Scene composition · Episode 42",progress:67,next:"Audio mixing",tone:"active"},
  {name:"Study Material Processor",state:"Idle",detail:"Last run completed 2h ago",progress:100,next:"On new capture",tone:"success"},
  {name:"Google Drive Sync",state:"Failed",detail:"Authentication expired",progress:38,next:"Action required",tone:"error"},
  {name:"Weekly Research Digest",state:"Scheduled",detail:"Runs Sunday at 08:00",progress:0,next:"In 2 days",tone:"neutral"},
];

export default function AutomationsPage(){const [paused,setPaused]=useState(false);const [selected,setSelected]=useState<typeof automations[number]|null>(null);const [tab,setTab]=useState("Runs");if(selected)return <ModuleShell active="Automations" title={selected.name} action={<button className="secondary" onClick={()=>setSelected(null)}><ArrowLeft/>Automations</button>}><div className="workspace-head"><div><h2>{selected.name}</h2><p>{selected.detail}</p></div><span className={`status-live ${selected.tone}`}><Circle weight="fill"/>{selected.state}</span></div><nav className="workspace-tabs">{["Runs","Logs","Metrics","Schedule"].map(item=><button className={tab===item?"active":""} onClick={()=>setTab(item)} key={item}>{item}</button>)}</nav><div className="automation-workspace"><section>{tab==="Runs"&&[["Run #142","Running","Started 12 min ago"],["Run #141","Completed","Yesterday · 18m 42s"],["Run #140","Failed","Jul 22 · Retried"]].map(([name,state,time])=><article className="workspace-row" key={name}><Lightning/><span><strong>{name}</strong><small>{time}</small></span><em>{state}</em></article>)}{tab==="Logs"&&<pre className="terminal-view"><code>09:42:18 Loaded scene manifest{"\n"}09:42:22 Rendering composition 28/42{"\n"}09:43:01 Audio normalization complete{"\n"}09:43:14 Waiting for render worker</code></pre>}{tab==="Metrics"&&<div className="metric-lines">{[["Success rate","96.8%"],["Median duration","18m 12s"],["Runs this month","42"],["Compute time","13h 24m"]].map(([label,value])=><span key={label}><small>{label}</small><strong>{value}</strong></span>)}</div>}{tab==="Schedule"&&<div className="schedule-form"><label>Trigger<select><option>New scene manifest</option><option>Every day</option><option>Manual only</option></select></label><label>Maximum concurrent runs<input type="number" defaultValue="2" min="1"/></label><label><input type="checkbox" defaultChecked/> Retry failed runs up to 3 times</label><button className="primary">Save schedule</button></div>}</section><aside className="run-controls"><h3>Current run</h3><i><b style={{width:`${selected.progress}%`}}/></i><span>{selected.progress}% · {selected.next}</span><button className="secondary" onClick={()=>setPaused(!paused)}>{paused?<Play/>:<Pause/>}{paused?"Resume":"Pause"}</button><button className="danger-button"><Stop/>Cancel run</button><button className="secondary"><ArrowClockwise/>Retry from failure</button></aside></div></ModuleShell>;return <ModuleShell active="Automations" title="Automations" action={<button className="primary top-primary"><Plus/>New automation</button>}>
  <div className="module-header"><div><h2>Systems working in the background</h2><p>One pipeline is running. Drive Sync needs attention.</p></div></div>
  <div className="automation-layout"><section><div className="list-title"><h3>Automations</h3><span>4 total</span></div><div className="automation-list">{automations.map(item=><article key={item.name}><span className={`automation-icon ${item.tone}`}><Lightning/></span><div><button className="automation-open" onClick={()=>setSelected(item)}><strong>{item.name}</strong><span>{item.detail}</span></button><i><b style={{width:`${item.progress}%`}}/></i><small>{item.progress?`${item.progress}% · `:""}Next: {item.next}</small></div><em className={item.tone}><Circle weight="fill"/>{item.name.startsWith("Stewie")&&paused?"Paused":item.state}</em>{item.name.startsWith("Stewie")?<button className="icon-button" aria-label={paused?"Resume automation":"Pause automation"} onClick={()=>setPaused(!paused)}>{paused?<Play/>:<Pause/>}</button>:<button className="icon-button" aria-label={`Open ${item.name}`} onClick={()=>setSelected(item)}><ArrowRight/></button>}</article>)}</div></section><aside className="automation-rail"><h3>Recent jobs</h3><article><Check/><div><strong>Lecture OCR</strong><span>Completed · 8 min ago</span></div></article><article><Warning/><div><strong>Drive Sync</strong><span>Failed · 24 min ago</span></div></article><article><Clock/><div><strong>Research Digest</strong><span>Scheduled · Sunday</span></div></article><button className="secondary" onClick={()=>setSelected(automations[0])}><ArrowClockwise/>View run history</button></aside></div>
  </ModuleShell>}
