"use client";

import {FormEvent,useEffect,useState} from "react";
import {ArrowClockwise,ArrowLeft,ArrowRight,Circle,Clock,Lightning,Pause,Play,Plus,Warning} from "@phosphor-icons/react";
import {ModuleShell} from "../components/ModuleShell";

type Automation={id:string;name:string;trigger_kind:"manual"|"schedule"|"capture";schedule:string|null;action_kind:"notification"|"skill";config_json:string;enabled:number;last_run_at:string|null;version:number};
type Run={id:string;state:string;started_at:string;finished_at:string|null;output_json:string|null;error:string|null};
type Metrics={total:number;states:Record<string,number>;lastRun:{state:string;startedAt:string;finishedAt:string|null;error:string|null}|null};
const empty={name:"",triggerKind:"manual",schedule:"",actionKind:"notification",title:"",body:""};
const request=async(path:string,init?:RequestInit)=>{const response=await fetch(path,init);const data=await response.json();if(!response.ok)throw new Error(data.error?.message||"Request failed");return data};
const when=(value:string|null)=>value?new Date(value).toLocaleString():"Never";

export default function AutomationsPage(){
  const [automations,setAutomations]=useState<Automation[]>([]),[selected,setSelected]=useState<Automation|null>(null),[runs,setRuns]=useState<Run[]>([]),[metrics,setMetrics]=useState<Metrics|null>(null);
  const [tab,setTab]=useState("Runs"),[creating,setCreating]=useState(false),[draft,setDraft]=useState(empty),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const load=()=>request("/api/v1/automations").then(data=>setAutomations(data.automations)).catch(reason=>setError(reason.message));
  const loadRuns=(id:string)=>request(`/api/v1/automations/${id}/runs`).then(data=>{setRuns(data.runs);setMetrics(data.metrics)}).catch(reason=>setError(reason.message));
  useEffect(()=>{load()},[]);
  useEffect(()=>{if(selected)loadRuns(selected.id)},[selected]);
  async function create(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{await request("/api/v1/automations",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({name:draft.name,triggerKind:draft.triggerKind,schedule:draft.triggerKind==="schedule"?draft.schedule:null,actionKind:draft.actionKind,config:draft.actionKind==="notification"?{title:draft.title||draft.name,body:draft.body}:{skill:"weekly-review",input:{}}})});setCreating(false);setDraft(empty);await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  async function toggle(item:Automation){setBusy(true);setError("");try{const updated=await request("/api/v1/automations",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({id:item.id,name:item.name,triggerKind:item.trigger_kind,schedule:item.schedule,actionKind:item.action_kind,config:JSON.parse(item.config_json),enabled:!item.enabled,version:item.version})});setSelected(current=>current?.id===updated.id?updated:current);await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  async function run(item:Automation){setBusy(true);setError("");try{await request(`/api/v1/automations/${item.id}/runs`,{method:"POST"});await Promise.all([load(),loadRuns(item.id)])}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  if(selected)return <ModuleShell active="Automations" title={selected.name} action={<button className="secondary" onClick={()=>setSelected(null)}><ArrowLeft/>Automations</button>}>
    {error&&<div className="warning-text" role="alert"><Warning/>{error}</div>}
    <div className="workspace-head"><div><h2>{selected.name}</h2><p>{selected.action_kind} · {selected.trigger_kind}{selected.schedule?` · ${selected.schedule}`:""}</p></div><span className={`status-live ${selected.enabled?"active":""}`}><Circle weight="fill"/>{selected.enabled?"Enabled":"Paused"}</span></div>
    <nav className="workspace-tabs">{["Runs","Logs","Metrics","Schedule"].map(item=><button className={tab===item?"active":""} onClick={()=>setTab(item)} key={item}>{item}</button>)}</nav>
    <div className="automation-workspace"><section>
      {tab==="Runs"&&(runs.length?runs.map(run=><article className="workspace-row" key={run.id}><Lightning/><span><strong>{run.id.slice(0,8)}</strong><small>{when(run.started_at)}</small></span><em>{run.state}</em></article>):<div className="empty-state"><Clock/><h3>No runs yet</h3><p>Run this automation manually or wait for its trigger.</p></div>)}
      {tab==="Logs"&&(runs.length?<pre className="terminal-view"><code>{runs.map(run=>`${when(run.started_at)} ${run.state}${run.error?` · ${run.error}`:run.output_json?` · ${run.output_json}`:""}`).join("\n")}</code></pre>:<div className="empty-state"><Clock/><h3>No logs yet</h3></div>)}
      {tab==="Metrics"&&<div className="metric-lines"><span><small>Total runs</small><strong>{metrics?.total||0}</strong></span><span><small>Completed</small><strong>{metrics?.states.completed||0}</strong></span><span><small>Failed</small><strong>{metrics?.states.failed||0}</strong></span><span><small>Last run</small><strong>{metrics?.lastRun?.state||"Never"}</strong></span></div>}
      {tab==="Schedule"&&<div className="schedule-form"><label>Trigger<input value={selected.trigger_kind} readOnly/></label><label>Schedule<input value={selected.schedule||"Manual only"} readOnly/></label><label>Action<input value={selected.action_kind} readOnly/></label></div>}
    </section><aside className="run-controls"><h3>Controls</h3><span>Last run: {when(selected.last_run_at)}</span><button className="primary" disabled={busy||!selected.enabled} onClick={()=>run(selected)}><Play/>Run now</button><button className="secondary" disabled={busy} onClick={()=>toggle(selected)}>{selected.enabled?<><Pause/>Pause</>:<><Play/>Resume</>}</button><button className="secondary" disabled={busy} onClick={()=>loadRuns(selected.id)}><ArrowClockwise/>Refresh</button></aside></div>
  </ModuleShell>;
  return <ModuleShell active="Automations" title="Automations" action={<button className="primary top-primary" onClick={()=>setCreating(true)}><Plus/>New automation</button>}>
    <div className="module-header"><div><h2>Systems working in the background</h2><p>Run, inspect, and pause durable automations.</p></div></div>{error&&<div className="warning-text" role="alert"><Warning/>{error}</div>}
    {creating&&<form className="schedule-form" onSubmit={create}><label>Name<input required value={draft.name} onChange={event=>setDraft({...draft,name:event.target.value})}/></label><label>Trigger<select value={draft.triggerKind} onChange={event=>setDraft({...draft,triggerKind:event.target.value})}><option value="manual">Manual</option><option value="schedule">Schedule</option><option value="capture">New capture</option></select></label>{draft.triggerKind==="schedule"&&<label>Cron schedule<input required placeholder="0 8 * * 0" value={draft.schedule} onChange={event=>setDraft({...draft,schedule:event.target.value})}/></label>}<label>Notification body<textarea value={draft.body} onChange={event=>setDraft({...draft,body:event.target.value})}/></label><div><button type="button" className="secondary" onClick={()=>setCreating(false)}>Cancel</button><button className="primary" disabled={busy}>Create</button></div></form>}
    <div className="automation-layout"><section><div className="list-title"><h3>Automations</h3><span>{automations.length} total</span></div><div className="automation-list">{automations.map(item=><article key={item.id}><span className={`automation-icon ${item.enabled?"active":"neutral"}`}><Lightning/></span><div><button className="automation-open" onClick={()=>setSelected(item)}><strong>{item.name}</strong><span>{item.action_kind} · {item.trigger_kind}</span></button><small>Last run: {when(item.last_run_at)}</small></div><em className={item.enabled?"active":"neutral"}><Circle weight="fill"/>{item.enabled?"Enabled":"Paused"}</em><button className="icon-button" aria-label={`Open ${item.name}`} onClick={()=>setSelected(item)}><ArrowRight/></button></article>)}{!automations.length&&!error&&<div className="empty-state"><Lightning/><h3>No automations</h3><p>Create a manual, scheduled, or capture-triggered automation.</p></div>}</div></section></div>
  </ModuleShell>;
}
