"use client";

import {useEffect,useState} from "react";
import {CheckCircle,Code,Lightning,Play,ShieldCheck,Sparkle,Trash,WarningCircle,X} from "@phosphor-icons/react";
import {ModuleShell} from "../components/ModuleShell";
import {ModalDialog} from "../components/ModalDialog";

type Manifest={apiVersion:number;id:string;name:string;version:string;description:string;entry:string;permissions:string[];integrity:string;noema:{minimumVersion:string}};
type Catalog={catalogId:string;catalog:string;manifest:Manifest|null;error:{code:string;message:string}|null};
type Installed={id:string;name:string;version:string;enabled:boolean;manifest:Manifest};
type Inspection={catalogId:string;catalog:string;manifest:Manifest;files:{path:string;sha256:string;source:string|null;size:number}[]};
const permissionCopy:{[key:string]:string}={"tasks:read":"Read task titles and scheduling metadata","notes:read":"Read note titles and excerpts","projects:read":"Read project names and status","notifications:write":"Create Noema notifications"};
export default function PluginsPage(){
  const [catalog,setCatalog]=useState<Catalog[]>([]),[installed,setInstalled]=useState<Installed[]>([]),[inspection,setInspection]=useState<Inspection|null>(null),[error,setError]=useState(""),[status,setStatus]=useState(""),[busy,setBusy]=useState(false);
  async function json(url:string,init?:RequestInit){const response=await fetch(url,init),value=await response.json();if(!response.ok)throw new Error(value.error?.message||"Plugin request failed");return value}
  async function load(){setError("");try{const value=await json("/api/v1/plugins");setCatalog(value.catalog);setInstalled(value.installed)}catch(reason){setError(reason instanceof Error?reason.message:"Marketplace is unavailable")}}
  useEffect(()=>{void load()},[]);
  async function inspect(item:Catalog){if(!item.manifest)return;setError("");try{setInspection(await json(`/api/v1/plugins/inspect?catalogId=${item.catalogId}&pluginId=${encodeURIComponent(item.manifest.id)}&version=${item.manifest.version}`))}catch(reason){setError(reason instanceof Error?reason.message:"Plugin inspection failed")}}
  async function approval(actionType:string,action:object,summary:string,risk="high",commands:string[]=[],files:string[]=[],diff=""){const record=await json("/api/v1/approvals",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({actionType,action,summary,risk,commands,files,diff})});if(!confirm(`${summary}\n\n${diff||commands.join("\n")}`))throw new Error("Approval cancelled");await json(`/api/v1/approvals/${record.id}/approve`,{method:"POST"});return record.id}
  async function install(item:Catalog){if(!item.manifest||!inspection||inspection.catalogId!==item.catalogId||inspection.manifest.id!==item.manifest.id||inspection.manifest.version!==item.manifest.version){setError("Inspect this exact package version before installation");return}setBusy(true);setError("");try{const action={catalogId:item.catalogId,pluginId:item.manifest.id,version:item.manifest.version},approvalId=await approval("plugin.install",action,`${installed.some(value=>value.id===item.manifest!.id)?"Update":"Install"} ${item.manifest.name} ${item.manifest.version}`,"critical",["verify manifest and package integrity","transactional plugin install"],inspection.files.map(file=>file.path),JSON.stringify(item.manifest,null,2));await json("/api/v1/plugins",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...action,approvalId})});setInspection(null);setStatus(`${item.manifest.name} ${item.manifest.version} installed`);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Installation failed")}finally{setBusy(false)}}
  async function toggle(item:Installed){setBusy(true);setError("");try{const action={pluginId:item.id,enabled:!item.enabled},approvalId=await approval("plugin.enable",action,`${item.enabled?"Disable":"Enable"} ${item.name}`);await json(`/api/v1/plugins/${encodeURIComponent(item.id)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({enabled:!item.enabled,approvalId})});await load()}catch(reason){setError(reason instanceof Error?reason.message:"Plugin state could not be changed")}finally{setBusy(false)}}
  async function uninstall(item:Installed){setBusy(true);setError("");try{const action={pluginId:item.id},approvalId=await approval("plugin.uninstall",action,`Uninstall ${item.name} ${item.version}`,"critical",["remove installed plugin package"]);await json(`/api/v1/plugins/${encodeURIComponent(item.id)}`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({approvalId})});setStatus(`${item.name} uninstalled`);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Uninstall failed")}finally{setBusy(false)}}
  async function run(item:Installed){setBusy(true);setError("");try{const input={},action={pluginId:item.id,input},approvalId=await approval("plugin.run",action,`Run ${item.name}`,item.manifest.permissions.includes("notifications:write")?"high":"medium",[`isolated plugin run ${item.id}`],[],item.manifest.permissions.map(permission=>permissionCopy[permission]).join("\n")),result=await json(`/api/v1/plugins/${encodeURIComponent(item.id)}/run`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({input,approvalId})});setStatus(`${item.name} completed · ${result.effects.notifications} notification effect(s)`)}catch(reason){setError(reason instanceof Error?reason.message:"Plugin run failed")}finally{setBusy(false)}}
  return <ModuleShell active="Plugins" title="Plugins"><div className="module-header"><div><h2>Plugin marketplace</h2><p>Inspect source, permissions, compatibility, and integrity before installing extensions from explicitly configured catalogs.</p></div></div>
    <section className="permission-note"><ShieldCheck/><span><strong>Untrusted by default</strong><small>Install, enablement, execution, updates, and removal require exact approval. Runs are network-isolated and receive only declared data.</small></span></section>
    {error&&<p className="auth-error" role="alert"><WarningCircle/>{error}</p>}{status&&<p className="success-note" role="status"><CheckCircle/>{status}</p>}
    <section><div className="list-title"><h3>Installed</h3><span>{installed.length} plugins</span></div>{installed.length?<div className="plugin-grid">{installed.map(item=><article className="plugin-card" key={item.id}><header><Lightning/><span><strong>{item.name}</strong><small>{item.id} · {item.version}</small></span><em className={item.enabled?"active":"paused"}>{item.enabled?"enabled":"disabled"}</em></header><p>{item.manifest.description||"No description provided."}</p><ul>{item.manifest.permissions.map(permission=><li key={permission}>{permissionCopy[permission]||permission}</li>)}</ul><footer><button className="secondary" disabled={busy} onClick={()=>void toggle(item)}>{item.enabled?"Disable":"Enable"}</button><button className="secondary" disabled={busy||!item.enabled} onClick={()=>void run(item)}><Play/>Run</button><button className="danger-link" disabled={busy} onClick={()=>void uninstall(item)}><Trash/>Uninstall</button></footer></article>)}</div>:<div className="empty-state"><Sparkle/><h3>No plugins installed</h3><p>Inspect a catalog package before installing it.</p></div>}</section>
    <section><div className="list-title"><h3>Configured catalogs</h3><span>{catalog.filter(item=>item.manifest).length} verified packages</span></div>{catalog.length?<div className="plugin-grid">{catalog.map((item,index)=>item.manifest?<article className="plugin-card" key={`${item.catalogId}-${item.manifest.id}-${item.manifest.version}`}><header><Code/><span><strong>{item.manifest.name}</strong><small>{item.catalog} · {item.manifest.version}</small></span></header><p>{item.manifest.description||"No description provided."}</p><small>{item.manifest.permissions.length} permissions · Noema ≥ {item.manifest.noema.minimumVersion}</small><footer><button className="primary" onClick={()=>void inspect(item)}>{installed.some(value=>value.id===item.manifest!.id)?"Inspect update":"Inspect source"}</button></footer></article>:<article className="plugin-card invalid" key={`${item.catalogId}-${index}`}><header><WarningCircle/><span><strong>Rejected package</strong><small>{item.catalog} · {item.error?.code}</small></span></header><p>{item.error?.message}</p></article>)}</div>:<div className="empty-state"><WarningCircle/><h3>No configured catalogs</h3><p>Set <code>NOEMA_PLUGIN_CATALOGS</code> to one or more local catalog directories.</p></div>}</section>
    {inspection&&<ModalDialog className="plugin-inspector" onClose={()=>setInspection(null)}><header><span><ShieldCheck/><strong>{inspection.manifest.name} {inspection.manifest.version}</strong></span><button className="icon-button" aria-label="Close plugin inspection" onClick={()=>setInspection(null)}><X/></button></header><h3>Requested permissions</h3><ul>{inspection.manifest.permissions.map(permission=><li key={permission}><strong>{permission}</strong><span>{permissionCopy[permission]}</span></li>)}</ul><h3>Verified package files</h3>{inspection.files.map(file=><article key={file.path}><header><code>{file.path}</code><small>{file.size} bytes · SHA-256 {file.sha256}</small></header>{file.source?<pre tabIndex={0}><code>{file.source}</code></pre>:<p>Binary or large file; hash only.</p>}</article>)}<footer><button className="secondary" onClick={()=>setInspection(null)}>Close</button><button className="primary" disabled={busy} onClick={()=>void install({catalogId:inspection.catalogId,catalog:inspection.catalog,manifest:inspection.manifest,error:null})}>Install verified package</button></footer></ModalDialog>}
  </ModuleShell>
}
