"use client";

import {createId} from "./id";

export type QueueStatus="pending"|"replaying"|"failed"|"conflict";
export type QueuedRequest={id:string;path:string;method:string;body:unknown;idempotencyKey:string;dependencies:string[];retryCount:number;status:QueueStatus;createdAt:string;error?:string};
export type OfflineCapture={id:string;kind:"capture";capture:Record<string,unknown>;blob:Blob;fileName:string;mime:string;idempotencyKey:string;retryCount:number;status:QueueStatus;createdAt:string;error?:string};
export type PendingItem=QueuedRequest|OfflineCapture;
export type InkDraft={id:string;noteId:string;width:number;height:number;strokes:unknown[];updatedAt:string};

const databaseName="noema-offline-v1",legacyDatabaseName="lifeos-offline-v1",mutationStore="mutations",captureStore="capture-blobs",inkStore="ink-drafts",recordingStore="recording-chunks",changedEvent="noema:queue-changed";
let migration:Promise<void>|undefined;

function database(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(databaseName,4);request.onupgradeneeded=()=>{const db=request.result;for(const name of [mutationStore,captureStore]){if(!db.objectStoreNames.contains(name)){const store=db.createObjectStore(name,{keyPath:"id"});store.createIndex("createdAt","createdAt")}}if(!db.objectStoreNames.contains(inkStore))db.createObjectStore(inkStore,{keyPath:"id"});if(!db.objectStoreNames.contains(recordingStore)){const store=db.createObjectStore(recordingStore,{keyPath:"key"});store.createIndex("recordingId","recordingId")}};request.onsuccess=()=>{migration??=migrateLegacy(request.result);migration.then(()=>resolve(request.result),reject)};request.onerror=()=>reject(request.error||new Error("Failed to open offline database"))})}
function requestResult<T>(request:IDBRequest<T>){return new Promise<T>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error("IndexedDB request failed"))})}
async function migrateLegacy(target:IDBDatabase){if(!indexedDB.databases||!(await indexedDB.databases()).some(item=>item.name===legacyDatabaseName)){return}const legacy=await new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(legacyDatabaseName);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error("Failed to open legacy offline database"))});try{for(const name of [mutationStore,captureStore]){if(!legacy.objectStoreNames.contains(name)){continue}const rows=await requestResult<PendingItem[]>(legacy.transaction(name).objectStore(name).getAll());if(!rows.length){continue}await new Promise<void>((resolve,reject)=>{const transaction=target.transaction(name,"readwrite"),store=transaction.objectStore(name);for(const row of rows){store.put(row)}transaction.oncomplete=()=>resolve();transaction.onerror=()=>reject(transaction.error||new Error("Offline migration failed"))})}}finally{legacy.close()}}
async function store(name:string,mode:IDBTransactionMode){const db=await database(),transaction=db.transaction(name,mode);transaction.oncomplete=()=>db.close();return transaction.objectStore(name)}
function announce(){dispatchEvent(new Event(changedEvent));try{const channel=new BroadcastChannel(changedEvent);channel.postMessage("changed");channel.close()}catch{}}
async function registerSync(){try{const registration=await navigator.serviceWorker?.ready;await (registration as ServiceWorkerRegistration&{sync?:{register(tag:string):Promise<void>}})?.sync?.register("noema-mutations")}catch{}}

export async function listQueued(){return requestResult<QueuedRequest[]>((await store(mutationStore,"readonly")).index("createdAt").getAll())}
export async function listOfflineCaptures(){return requestResult<OfflineCapture[]>((await store(captureStore,"readonly")).index("createdAt").getAll())}
export async function listPending(){return [...await listQueued(),...await listOfflineCaptures()].sort((a,b)=>a.createdAt.localeCompare(b.createdAt))}
export async function queueRequest(input:Omit<QueuedRequest,"id"|"retryCount"|"status"|"createdAt">){const item:QueuedRequest={...input,id:createId(),retryCount:0,status:"pending",createdAt:new Date().toISOString()};await requestResult((await store(mutationStore,"readwrite")).add(item));announce();await registerSync();return item.id}
export async function queueOfflineCapture(capture:Record<string,unknown>,file:File){const item:OfflineCapture={id:String(capture.id),kind:"capture",capture,blob:file,fileName:file.name,mime:file.type||"application/octet-stream",idempotencyKey:createId(),retryCount:0,status:"pending",createdAt:new Date().toISOString()};await requestResult((await store(captureStore,"readwrite")).put(item));announce();await registerSync();return item.id}
export async function saveInkDraft(draft:Omit<InkDraft,"updatedAt">){await requestResult((await store(inkStore,"readwrite")).put({...draft,updatedAt:new Date().toISOString()}))}
export async function loadInkDraft(id:string){return requestResult<InkDraft|undefined>((await store(inkStore,"readonly")).get(id))}
export async function deleteInkDraft(id:string){await requestResult((await store(inkStore,"readwrite")).delete(id))}

export type RecordingChunk={key:string;recordingId:string;index:number;blob:Blob;mime:string;createdAt:string};
export async function saveRecordingChunk(recordingId:string,index:number,blob:Blob,mime:string){const chunk:RecordingChunk={key:`${recordingId}:${index}`,recordingId,index,blob,mime,createdAt:new Date().toISOString()};await requestResult((await store(recordingStore,"readwrite")).put(chunk))}
export async function loadRecording(recordingId:string){const chunks=requestResult<RecordingChunk[]>((await store(recordingStore,"readonly")).index("recordingId").getAll(recordingId));return (await chunks).sort((a,b)=>a.index-b.index)}
export async function listUnfinishedRecordings(){const all=await requestResult<RecordingChunk[]>((await store(recordingStore,"readonly")).getAll());const ids=new Set(all.map(chunk=>chunk.recordingId));return [...ids]}
export async function deleteRecording(recordingId:string){const db=await database();await new Promise<void>((resolve,reject)=>{const transaction=db.transaction(recordingStore,"readwrite"),index=transaction.objectStore(recordingStore).index("recordingId"),request=index.openKeyCursor(IDBKeyRange.only(recordingId));request.onsuccess=()=>{const cursor=request.result;if(cursor){transaction.objectStore(recordingStore).delete(cursor.primaryKey);cursor.continue()}else resolve()};request.onerror=()=>reject(request.error||new Error("Failed to delete recording"))});if(db)db.close()}
export async function retryQueued(id:string){for(const name of [mutationStore,captureStore]){const item=await requestResult<PendingItem|undefined>((await store(name,"readonly")).get(id));if(item){await requestResult((await store(name,"readwrite")).put({...item,status:"pending",error:undefined}));announce();await flushQueue();return}}}

async function replayCaptures(){for(const item of (await listOfflineCaptures()).map(item=>item.status==="replaying"?{...item,status:"pending" as const}:item)){if(item.status!=="pending")continue;await requestResult((await store(captureStore,"readwrite")).put({...item,status:"replaying"}));announce();try{const form=new FormData();form.append("file",new File([item.blob],item.fileName,{type:item.mime}));let response=await fetch("/api/v1/assets",{method:"POST",body:form}),data=await response.json().catch(()=>null);if(!response.ok)throw Object.assign(new Error(data?.error?.message||`Upload failed (${response.status})`),{status:response.status});response=await fetch("/api/v1/captures",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":item.idempotencyKey},body:JSON.stringify({...item.capture,assetIds:[data.assets[0].id]})});data=await response.json().catch(()=>null);if(!response.ok)throw Object.assign(new Error(data?.error?.message||`Capture failed (${response.status})`),{status:response.status});await requestResult((await store(captureStore,"readwrite")).delete(item.id))}catch(error){const status=(error as {status?:number}).status;await requestResult((await store(captureStore,"readwrite")).put({...item,retryCount:item.retryCount+1,status:status===409?"conflict":!status||status>=500?"pending":"failed",error:error instanceof Error?error.message:"Network unavailable"}));if(!status||status>=500)break}announce()}}
async function replay(){await replayCaptures();const items=(await listQueued()).map(item=>item.status==="replaying"?{...item,status:"pending" as const}:item),ids=new Set(items.map(item=>item.id));for(const item of items){if(item.status!=="pending"||item.dependencies.some(id=>ids.has(id)))continue;await requestResult((await store(mutationStore,"readwrite")).put({...item,status:"replaying"}));announce();try{const response=await fetch(`/api/v1${item.path}`,{method:item.method,headers:{"Content-Type":"application/json","Idempotency-Key":item.idempotencyKey},body:JSON.stringify(item.body)});if(response.ok){const result=item.path==="/captures"?await response.json().catch(()=>null):null;await requestResult((await store(mutationStore,"readwrite")).delete(item.id));if(result?.jobId)dispatchEvent(new CustomEvent("noema:capture-synced",{detail:result}))}else{const message=(await response.json().catch(()=>null))?.error?.message||`Request failed (${response.status})`;await requestResult((await store(mutationStore,"readwrite")).put({...item,retryCount:item.retryCount+1,status:response.status===409?"conflict":response.status>=500?"pending":"failed",error:message}))}}catch(error){await requestResult((await store(mutationStore,"readwrite")).put({...item,retryCount:item.retryCount+1,status:"pending",error:error instanceof Error?error.message:"Network unavailable"}));break}announce()}}

export async function flushQueue(){if(!navigator.onLine){return}const locks=(navigator as Navigator&{locks?:LockManager}).locks;if(locks){await locks.request("noema-offline-replay",replay)}else{await replay()}}
export function observeQueue(callback:(items:PendingItem[])=>void){const update=()=>void listPending().then(callback);addEventListener(changedEvent,update);let channel:BroadcastChannel|undefined;try{channel=new BroadcastChannel(changedEvent);channel.onmessage=update}catch{}update();return()=>{removeEventListener(changedEvent,update);channel?.close()}}
