"use client";

import {FormEvent,useEffect,useState} from "react";
import {ArrowLeft,BookOpen,Brain,CalendarBlank,Camera,Cards,FileText,Pen,Plus,UploadSimple,Warning} from "@phosphor-icons/react";
import {ModuleShell} from "../components/ModuleShell";

type Course={id:string;code:string;name:string;term:string;color:string;archived:number;version:number};
type Assignment={id:string;course_id:string;title:string;due_at:string|null;status:"todo"|"doing"|"submitted"|"graded";score:number|null;version:number};
type Card={id:string;course_id:string|null;front:string;back:string;due_at:string;version:number};
type Question={id:string;prompt:string;choices:string[]};type Quiz={id:string;course_id:string|null;title:string;questions:Question[];version:number};
type Workspace="dashboard"|"course"|"review"|"quiz"|"handwriting"|"upload";
async function request(path:string,init?:RequestInit){const response=await fetch(path,init),data=await response.json();if(!response.ok)throw new Error(data.error?.message||"Request failed");return data}
const post=(path:string,body:unknown)=>request(path,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(body)});

export default function StudyPage(){
  const [workspace,setWorkspace]=useState<Workspace>("dashboard"),[courses,setCourses]=useState<Course[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[cards,setCards]=useState<Card[]>([]),[quizzes,setQuizzes]=useState<Quiz[]>([]),[quiz,setQuiz]=useState<Quiz|null>(null),[answers,setAnswers]=useState<Record<string,number>>({}),[score,setScore]=useState<number|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[hw,setHw]=useState({extracting:false,text:"",equations:[] as {latex:string;confidence:string}[],error:""});
  const load=()=>Promise.all([request("/api/v1/study/courses"),request("/api/v1/study/assignments"),request("/api/v1/study/cards"),request("/api/v1/study/quizzes")]).then(([a,b,c,d])=>{setCourses(a.courses);setAssignments(b.assignments);setCards(c.cards);setQuizzes(d.quizzes)}).catch(reason=>setError(reason.message)).finally(()=>setLoading(false));
  useEffect(()=>{void load()},[]);const back=<button className="secondary" onClick={()=>setWorkspace("dashboard")}><ArrowLeft/>Study</button>,courseName=(id:string|null)=>courses.find(course=>course.id===id)?.name||"Unassigned";
  async function createCourse(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{const course=await post("/api/v1/study/courses",{name:form.get("name"),code:form.get("code"),term:form.get("term")});setCourses(current=>[course,...current]);event.currentTarget.reset();setWorkspace("dashboard")}catch(reason){setError((reason as Error).message)}}
  async function archive(course:Course){try{const saved=await post("/api/v1/study/courses",{...course,archived:true});setCourses(current=>current.map(item=>item.id===saved.id?saved:item))}catch(reason){setError((reason as Error).message)}}
  async function updateAssignment(item:Assignment,status:Assignment["status"]){try{const saved=await post("/api/v1/study/assignments",{id:item.id,courseId:item.course_id,title:item.title,dueAt:item.due_at,status,score:item.score,version:item.version});setAssignments(current=>current.map(value=>value.id===saved.id?saved:value))}catch(reason){setError((reason as Error).message)}}
  async function review(rating:number){const card=cards[0];if(!card)return;try{await request(`/api/v1/study/cards/${card.id}/review`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({rating})});setCards(current=>current.slice(1))}catch(reason){setError((reason as Error).message)}}
  async function submitQuiz(){if(!quiz)return;try{const result=await request(`/api/v1/study/quizzes/${quiz.id}/attempts`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({answers:quiz.questions.map(question=>answers[question.id]??-1)})});setScore(result.score)}catch(reason){setError((reason as Error).message)}}
  async function extract(file:File){setHw({extracting:true,text:"",equations:[],error:""});try{const form=new FormData();form.append("file",file);const upload=await request("/api/v1/assets",{method:"POST",body:form}),result=await request("/api/v1/extract/handwriting",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({assetId:upload.assets[0].id})});setHw({extracting:false,text:result.text||"",equations:result.equations||[],error:""})}catch(reason){setHw({extracting:false,text:"",equations:[],error:(reason as Error).message})}}
  if(workspace==="course")return <ModuleShell active="Study" title="New course" action={back}><section className="study-workspace narrow"><header><BookOpen/><div><h2>Add a course</h2><p>Assignments, cards, quizzes, and sources can link to it.</p></div></header><form className="auth-result" onSubmit={createCourse}><label>Course name<input name="name" required maxLength={300}/></label><label>Code<input name="code" maxLength={50}/></label><label>Term<input name="term" maxLength={100}/></label><button className="primary">Create course</button></form>{error&&<p role="alert" className="auth-error">{error}</p>}</section></ModuleShell>;
  if(workspace==="review")return <ModuleShell active="Study" title="Flashcard review" action={back}><section className="study-workspace narrow"><header><Cards/><div><h2>Due cards</h2><p>{cards.length} remaining</p></div></header>{cards[0]?<><article className="flashcard"><small>Question</small><h3>{cards[0].front}</h3><div><small>Answer</small><p>{cards[0].back}</p></div></article><div className="rating-row">{[[1,"Again"],[2,"Hard"],[4,"Good"],[5,"Easy"]].map(([rating,label])=><button className={rating===4?"primary":""} key={rating} onClick={()=>void review(rating as number)}>{label}</button>)}</div></>:<p role="status">No flashcards are due.</p>}{error&&<p role="alert">{error}</p>}</section></ModuleShell>;
  if(workspace==="quiz"&&quiz)return <ModuleShell active="Study" title="Practice quiz" action={back}><section className="study-workspace narrow"><header><Brain/><div><h2>{quiz.title}</h2><p>{quiz.questions.length} questions · attempts are saved</p></div></header>{quiz.questions.map(question=><fieldset className="quiz" key={question.id}><legend>{question.prompt}</legend>{question.choices.map((choice,index)=><label key={choice}><input type="radio" name={question.id} checked={answers[question.id]===index} onChange={()=>setAnswers(current=>({...current,[question.id]:index}))}/><span>{choice}</span></label>)}</fieldset>)}{score!==null&&<p role="status"><strong>Score: {score}%</strong></p>}<footer><button className="primary" disabled={quiz.questions.some(question=>answers[question.id]===undefined)} onClick={()=>void submitQuiz()}>Submit attempt</button></footer></section></ModuleShell>;
  if(workspace==="handwriting")return <ModuleShell active="Study" title="Handwriting" action={back}><section className="study-workspace narrow"><header><Pen/><div><h2>Handwriting & math</h2><p>Upload handwritten notes or equations.</p></div></header><div className="drop-zone"><UploadSimple/><strong>Drop a photo here</strong><span>PNG, JPEG, WebP · up to 50 MB</span><label className="primary">Choose image<input type="file" accept="image/*" onChange={event=>{const file=event.target.files?.[0];if(file)void extract(file)}}/></label></div>{hw.extracting&&<p role="status">Extracting…</p>}{hw.error&&<div className="warning-text" role="alert"><Warning/>{hw.error}</div>}{hw.text&&<article><h3>Extracted text</h3><textarea readOnly value={hw.text}/></article>}{hw.equations.length>0&&<ul className="equation-list">{hw.equations.map((item,index)=><li key={index}><code>{item.latex}</code><small>{item.confidence}</small></li>)}</ul>}</section></ModuleShell>;
  if(workspace==="upload")return <ModuleShell active="Study" title="Capture lecture" action={back}><section className="study-workspace"><header><Camera/><div><h2>Add lecture material</h2><p>Originals stay immutable and linked to their capture.</p></div></header><div className="drop-zone"><UploadSimple/><strong>Choose lecture files</strong><span>PDF, images, audio · up to 50 MB each</span><label className="primary">Choose files<input type="file" multiple onChange={()=>setWorkspace("dashboard")}/></label></div></section></ModuleShell>;
  return <ModuleShell active="Study" title="Study" action={<button className="primary top-primary" onClick={()=>setWorkspace("upload")}><Camera/>Capture lecture</button>}><div className="module-header"><div><h2>Keep learning in motion</h2><p>Courses, due reviews, quizzes, and assignments from your workspace.</p></div><button className="secondary" onClick={()=>setWorkspace("course")}><Plus/>New course</button></div>{loading?<p role="status">Loading study workspace…</p>:error?<p role="alert" className="auth-error">{error}</p>:<><div className="study-layout"><section><div className="list-title"><h3>Current courses</h3></div><div className="course-list">{courses.filter(course=>!course.archived).length?courses.filter(course=>!course.archived).map(course=><div className="course-row" key={course.id}><span className="course-icon"><BookOpen/></span><div><small>{course.code||course.term||"Course"}</small><strong>{course.name}</strong><span>{assignments.filter(item=>item.course_id===course.id&&item.status!=="graded").length} open assignments</span></div><button className="secondary" onClick={()=>void archive(course)}>Archive</button></div>):<p>No courses yet. Create one to organize study material.</p>}</div></section><aside className="study-rail"><h3>Review queue</h3><button onClick={()=>setWorkspace("review")}><Cards/><span><strong>Flashcards due</strong><small>{cards.length} cards</small></span><em>Start</em></button>{quizzes.map(item=><button key={item.id} onClick={()=>{setQuiz(item);setAnswers({});setScore(null);setWorkspace("quiz")}}><Brain/><span><strong>{item.title}</strong><small>{item.questions.length} questions</small></span><em>Open</em></button>)}<button onClick={()=>setWorkspace("handwriting")}><Pen/><span><strong>Handwriting & math</strong><small>Extract notes and equations</small></span><em>Open</em></button></aside></div><section className="assignments"><div className="list-title"><h3>Upcoming assignments</h3></div>{assignments.length?assignments.map(item=><div className="assignment-row" key={item.id}><CalendarBlank/><div><strong>{item.title}</strong><span>{courseName(item.course_id)}</span></div><time>{item.due_at?new Date(item.due_at).toLocaleDateString():"No due date"}</time><select aria-label={`Status for ${item.title}`} value={item.status} onChange={event=>void updateAssignment(item,event.target.value as Assignment["status"])}>{["todo","doing","submitted","graded"].map(status=><option key={status}>{status}</option>)}</select></div>):<p>No assignments yet.</p>}</section></>}</ModuleShell>
}
