"use client";

import {useState} from "react";
import {ArrowLeft, ArrowRight, BookOpen, Brain, CalendarBlank, Camera, Cards, Check, CheckCircle, FileText, Plus, UploadSimple, Warning} from "@phosphor-icons/react";
import {ModuleShell} from "../components/ModuleShell";

const courses=[{name:"Computer Networks",code:"CS310",next:"Congestion control review",progress:68},{name:"Database Systems",code:"CS320",next:"Normalization assignment",progress:54},{name:"Operating Systems",code:"CS330",next:"Memory management quiz",progress:41}];
type Workspace="dashboard"|"upload"|"result"|"review"|"quiz"|"assignment";
export default function StudyPage(){const [workspace,setWorkspace]=useState<Workspace>("dashboard");const [answer,setAnswer]=useState<number|null>(null);const [submitted,setSubmitted]=useState(false);const back=<button className="secondary" onClick={()=>setWorkspace("dashboard")}><ArrowLeft/>Study</button>;
  if(workspace==="upload")return <ModuleShell active="Study" title="Capture lecture" action={back}><section className="study-workspace"><header><Camera/><div><h2>Add lecture material</h2><p>Combine photos, screenshots, PDFs, or audio. Originals stay attached to the result.</p></div></header><div className="drop-zone"><UploadSimple/><strong>Drop lecture files here</strong><span>PDF, images, audio · up to 250 MB</span><label className="primary">Choose files<input type="file" multiple onChange={()=>setWorkspace("result")}/></label></div><div className="camera-flow"><Camera/><span><strong>Use your phone camera</strong><small>Capture pages in order; edges and rotation are corrected locally.</small></span><button className="secondary" onClick={()=>setWorkspace("result")}>Open camera</button></div></section></ModuleShell>;
  if(workspace==="result")return <ModuleShell active="Study" title="Processing result" action={back}><section className="study-workspace"><header><CheckCircle/><div><h2>Lecture ready for review</h2><p>18 pages processed. Check uncertain passages before creating study material.</p></div></header><div className="result-summary"><span><strong>94%</strong><small>Text confidence</small></span><span><strong>12</strong><small>Key concepts</small></span><span><strong>3</strong><small>Needs review</small></span></div><div className="source-compare"><article><h3>Original source</h3><div className="source-page"><FileText/><strong>TCP congestion control</strong><p>Congestion avoidance increases the window linearly until loss is detected…</p><small>Page 6 of 18</small></div></article><article><h3>Extracted note</h3><textarea defaultValue={"## Congestion avoidance\n\nThe congestion window grows linearly until packet loss indicates congestion. TCP then reduces the window multiplicatively."}/><span className="warning-text"><Warning/>Low confidence: “multiplicatively”</span></article></div><footer><button className="secondary">Save draft</button><button className="primary" onClick={()=>setWorkspace("review")}>Confirm and create cards</button></footer></section></ModuleShell>;
  if(workspace==="review")return <ModuleShell active="Study" title="Flashcard review" action={back}><section className="study-workspace narrow"><header><Cards/><div><h2>Congestion control</h2><p>Card 3 of 12 · Review the generated answer before rating it.</p></div></header><article className="flashcard"><small>Question</small><h3>What happens to the congestion window after packet loss?</h3><div><small>Answer</small><p>TCP reduces the congestion window multiplicatively, then resumes additive growth during congestion avoidance.</p></div></article><div className="rating-row"><button>Again<small>&lt; 1 min</small></button><button>Hard<small>2 days</small></button><button className="primary">Good<small>4 days</small></button><button>Easy<small>7 days</small></button></div></section></ModuleShell>;
  if(workspace==="quiz")return <ModuleShell active="Study" title="Practice quiz" action={back}><section className="study-workspace narrow"><header><Brain/><div><h2>Operating Systems practice</h2><p>Question 1 of 10 · Choose one answer.</p></div></header><fieldset className="quiz"><legend>Which scheduling algorithm can cause starvation without aging?</legend>{["Round robin","First-come, first-served","Priority scheduling","Shortest remaining time"].map((option,index)=><label className={submitted&&index===2?"correct":""} key={option}><input type="radio" name="answer" checked={answer===index} onChange={()=>setAnswer(index)}/><span>{option}</span>{submitted&&index===2&&<Check/>}</label>)}</fieldset>{submitted&&<div className="correction"><CheckCircle/><span><strong>Correct: Priority scheduling</strong><small>Aging gradually raises waiting processes’ priority, preventing indefinite starvation.</small></span></div>}<footer><button className="primary" disabled={answer===null} onClick={()=>setSubmitted(true)}>Check answer</button></footer></section></ModuleShell>;
  if(workspace==="assignment")return <ModuleShell active="Study" title="Assignment workspace" action={back}><section className="study-workspace"><header><FileText/><div><h2>Database normalization worksheet</h2><p>Due Friday · Database Systems</p></div></header><div className="assignment-layout"><article><label>Working notes<textarea defaultValue={"Given R(A, B, C, D) with dependencies A → B and B → C…\n\n1. Find candidate keys\n2. Identify highest normal form\n3. Decompose to BCNF"}/></label></article><aside><h3>Attached sources</h3><button><FileText/><span><strong>Week 4 slides</strong><small>PDF · 32 pages</small></span></button><button><BookOpen/><span><strong>Normalization notes</strong><small>Vault note</small></span></button><h3>Checklist</h3>{["Candidate keys","Dependency preservation","Lossless join"].map(item=><label key={item}><input type="checkbox"/>{item}</label>)}</aside></div><footer><button className="secondary">Save draft</button><button className="primary">Mark ready to submit</button></footer></section></ModuleShell>;
  return <ModuleShell active="Study" title="Study" action={<button className="primary top-primary" onClick={()=>setWorkspace("upload")}><Camera/>Capture lecture</button>}><div className="module-header"><div><h2>Keep learning in motion</h2><p>One lecture needs review. Your next assignment is due Friday.</p></div></div><div className="study-layout"><section><div className="list-title"><h3>Current courses</h3><button>View all</button></div><div className="course-list">{courses.map(course=><button className="course-row" key={course.code}><span className="course-icon"><BookOpen/></span><div><small>{course.code}</small><strong>{course.name}</strong><span>{course.next}</span><i><b style={{width:`${course.progress}%`}}/></i></div><em>{course.progress}%</em><ArrowRight/></button>)}</div></section><aside className="study-rail"><h3>Review queue</h3><button onClick={()=>setWorkspace("result")}><FileText/><span><strong>TCP congestion control</strong><small>Lecture capture · 12 cards</small></span><em>Review</em></button><button onClick={()=>setWorkspace("review")}><Cards/><span><strong>Flashcards due</strong><small>24 cards · 15 min</small></span><em>Start</em></button><button onClick={()=>setWorkspace("quiz")}><Brain/><span><strong>OS practice quiz</strong><small>10 questions</small></span><em>Open</em></button></aside></div><section className="assignments"><div className="list-title"><h3>Upcoming assignments</h3><button>Open calendar</button></div><button className="assignment-row" onClick={()=>setWorkspace("assignment")}><CalendarBlank/><div><strong>Database normalization worksheet</strong><span>Database Systems</span></div><time>Friday</time><span className="status warning-text">In progress</span></button><button className="assignment-row"><Check/><div><strong>TCP lab report</strong><span>Computer Networks</span></div><time>Jul 30</time><span className="status">Planned</span></button></section></ModuleShell>}
