"use client";

import {createId} from "../../../lib/id";
import {FormEvent,useEffect,useState} from "react";
import {DownloadSimple,HighlighterCircle,PenNib,TextT} from "@phosphor-icons/react";
import {useParams} from "next/navigation";
import {ModuleShell} from "../../../components/ModuleShell";
type Annotation={id:string;page:number;kind:string;content:string;comment:string;version:number;geometry:unknown};
export default function AnnotatePdfPage(){const {id}=useParams<{id:string}>(),[items,setItems]=useState<Annotation[]>([]),[error,setError]=useState("");const load=()=>fetch(`/api/v1/assets/${id}/annotations`).then(response=>response.json()).then(data=>setItems(data.annotations||[])).catch(reason=>setError(reason.message));useEffect(()=>{void load()},[id]);async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),kind=String(form.get("kind")),geometry=kind==="ink"?{points:[[.1,.1],[.3,.25],[.5,.2]]}:{x:Number(form.get("x")),y:Number(form.get("y")),width:Number(form.get("width")),height:Number(form.get("height"))};const response=await fetch(`/api/v1/assets/${id}/annotations`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":createId()},body:JSON.stringify({page:Number(form.get("page")),kind,geometry,content:form.get("content"),comment:form.get("comment"),linkType:form.get("linkType")||null,linkId:form.get("linkId")||null})}),data=await response.json();if(!response.ok){setError(data.error?.message||"Annotation failed");return}event.currentTarget.reset();void load()}return <ModuleShell active="Vault" title="PDF annotations" action={<a className="secondary" href={`/api/v1/assets/${id}/annotations/export`}><DownloadSimple/>Export</a>}><div className="project-workspace"><iframe title="PDF source" src={`/api/v1/assets/${id}`} className="pdf-frame"/><aside className="workspace-context"><h2>Page annotations</h2><form onSubmit={save}><label>Tool<select name="kind"><option value="highlight">Highlight</option><option value="ink">Ink</option><option value="text">Text</option></select></label><label>Page<input name="page" type="number" min="1" defaultValue="1" required/></label>{["x","y","width","height"].map(name=><label key={name}>{name}<input name={name} type="number" min="0" max="1" step="0.01" defaultValue={name==="width"?.4:name==="height"?.08:.1}/></label>)}<label>Text<input name="content"/></label><label>Comment<textarea name="comment"/></label><label>Link type<select name="linkType"><option value="">None</option><option value="note">Note</option><option value="course">Course</option></select></label><label>Linked object ID<input name="linkId"/></label><button className="primary">Save annotation</button></form>{error&&<p role="alert">{error}</p>}<ol>{items.map(item=><li key={item.id}>{item.kind==="highlight"?<HighlighterCircle/>:item.kind==="ink"?<PenNib/>:<TextT/>}<span><strong>Page {item.page}</strong><small>{item.comment||item.content||"No comment"}</small></span></li>)}</ol></aside></div></ModuleShell>}
