"use client";

import {PointerEvent,useEffect,useRef,useState} from "react";
import {useParams} from "next/navigation";
import Link from "next/link";
import {ArrowLeft,ArrowRight,DownloadSimple,HighlighterCircle,MagnifyingGlassMinus,MagnifyingGlassPlus,PenNib,TextT} from "@phosphor-icons/react";
import {ModuleShell} from "../../../components/ModuleShell";
import {createId} from "../../../lib/id";

type Kind="highlight"|"ink"|"text";
type Annotation={id:string;page:number;kind:Kind;geometry:{x?:number;y?:number;width?:number;height?:number;points?:number[][]};content:string;comment:string;link_type:string|null;link_id:string|null;version:number};
const clamp=(value:number)=>Math.max(0,Math.min(1,value));

export default function AnnotatePdfPage(){
  const {id}=useParams<{id:string}>(),canvas=useRef<HTMLCanvasElement>(null),surface=useRef<HTMLDivElement>(null);
  const [items,setItems]=useState<Annotation[]>([]),[page,setPage]=useState(1),[pages,setPages]=useState(1),[scale,setScale]=useState(1),[kind,setKind]=useState<Kind>("highlight"),[drawing,setDrawing]=useState<number[][]>([]),[draft,setDraft]=useState<Annotation|null>(null),[error,setError]=useState(""),[status,setStatus]=useState("Loading PDF…");
  const load=()=>fetch(`/api/v1/assets/${id}/annotations`).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error?.message||"Annotations are unavailable");setItems(data.annotations||[])}).catch(reason=>setError(reason.message));
  useEffect(()=>{void load()},[id]);
  useEffect(()=>{let cancelled=false;(async()=>{try{setStatus("Rendering page…");const pdfjs=await import("pdfjs-dist/legacy/build/pdf.mjs"),pdf=await pdfjs.getDocument({url:`/api/v1/assets/${id}`}).promise;if(cancelled)return;setPages(pdf.numPages);const source=await pdf.getPage(page),viewport=source.getViewport({scale:Math.min(2,scale)}),element=canvas.current;if(!element)return;element.width=viewport.width;element.height=viewport.height;await source.render({canvas:element,canvasContext:element.getContext("2d")!,viewport}).promise;if(!cancelled)setStatus(`Page ${page} of ${pdf.numPages}`)}catch(reason){if(!cancelled){setError(reason instanceof Error?reason.message:"PDF could not be rendered");setStatus("PDF unavailable")}}})();return()=>{cancelled=true}},[id,page,scale]);
  const point=(event:PointerEvent)=>{const rect=surface.current!.getBoundingClientRect();return [clamp((event.clientX-rect.left)/rect.width),clamp((event.clientY-rect.top)/rect.height)]};
  const save=async(annotation:Annotation)=>{setError("");const response=await fetch(`/api/v1/assets/${id}/annotations`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":createId()},body:JSON.stringify(annotation)}),data=await response.json();if(!response.ok){setError(data.error?.message||"Annotation was not saved");return}setItems(current=>[...current.filter(item=>item.id!==data.id),data]);setStatus("Annotation saved");setDraft(null)};
  const start=(event:PointerEvent<HTMLDivElement>)=>{if(event.pointerType==="mouse"&&kind==="ink"&&event.button!==0)return;event.currentTarget.setPointerCapture(event.pointerId);const start=point(event);setDrawing([start]);if(kind!=="ink")setDraft({id:createId(),page,kind,geometry:{x:start[0],y:start[1],width:0,height:0},content:"",comment:"",link_type:null,link_id:null,version:0})};
  const move=(event:PointerEvent<HTMLDivElement>)=>{const next=point(event);if(kind==="ink")setDrawing(current=>[...current,next]);else setDraft(current=>current?{...current,geometry:{...current.geometry,width:next[0]-(current.geometry.x||0),height:next[1]-(current.geometry.y||0)}}:current)};
  const end=()=>{if(kind==="ink"&&drawing.length>1)void save({id:createId(),page,kind,geometry:{points:drawing},content:"",comment:"",link_type:null,link_id:null,version:0});else if(draft&&kind==="highlight")void save({...draft,geometry:{...draft.geometry,width:Math.abs(draft.geometry.width||0),height:Math.abs(draft.geometry.height||0),x:Math.min(draft.geometry.x||0,(draft.geometry.x||0)+(draft.geometry.width||0)),y:Math.min(draft.geometry.y||0,(draft.geometry.y||0)+(draft.geometry.height||0))}});setDrawing([])};
  const visible=items.filter(item=>item.page===page);
  return <ModuleShell active="Vault" title="PDF annotations" action={<a className="secondary" href={`/api/v1/assets/${id}/annotations/export`}><DownloadSimple/>Export annotations</a>}><section className="pdf-annotator"><header><div className="pdf-tools" role="toolbar" aria-label="PDF annotation tools">{([["highlight",HighlighterCircle,"Highlight"],["ink",PenNib,"Ink"],["text",TextT,"Text"]] as const).map(([next,Icon,label])=><button key={next} className={kind===next?"active":""} aria-pressed={kind===next} onClick={()=>setKind(next)}><Icon/>{label}</button>)}<button onClick={()=>setScale(value=>Math.max(.5,value-.2))} aria-label="Zoom out"><MagnifyingGlassMinus/></button><button onClick={()=>setScale(value=>Math.min(2,value+.2))} aria-label="Zoom in"><MagnifyingGlassPlus/></button></div><div className="pdf-pages"><button disabled={page===1} onClick={()=>setPage(value=>value-1)} aria-label="Previous page"><ArrowLeft/></button><span>{status}</span><button disabled={page===pages} onClick={()=>setPage(value=>value+1)} aria-label="Next page"><ArrowRight/></button></div></header><div className="pdf-stage"><div ref={surface} className="pdf-page" style={{maxWidth:`${scale*100}%`}} onPointerDown={start} onPointerMove={move} onPointerUp={end}><canvas ref={canvas}/>{visible.map(item=><AnnotationShape item={item} key={item.id}/>)}{kind==="ink"&&drawing.length>1&&<svg className="pdf-overlay" viewBox="0 0 1 1" preserveAspectRatio="none"><polyline points={drawing.map(point=>point.join(",")).join(" ")}/></svg>}{draft&&kind==="text"&&<AnnotationShape item={draft}/>}</div></div>{draft?.kind==="text"&&<form className="pdf-text-form" onSubmit={event=>{event.preventDefault();void save(draft)}}><label>Annotation text<input autoFocus value={draft.content} onChange={event=>setDraft({...draft,content:event.target.value})} required/></label><label>Comment<input value={draft.comment} onChange={event=>setDraft({...draft,comment:event.target.value})}/></label><button className="primary">Save text</button></form>}<aside className="pdf-annotation-list"><h2>Annotations</h2>{visible.length?<ol>{visible.map(item=><li key={item.id}>{item.kind==="highlight"?<HighlighterCircle/>:item.kind==="ink"?<PenNib/>:<TextT/>}<span><strong>Page {item.page}</strong><small>{item.comment||item.content||"No comment"}</small>{item.link_type&&item.link_id&&<Link href={item.link_type==="note"?`/vault?open=${item.link_id}`:"/study"}>Open linked {item.link_type}</Link>}</span></li>)}</ol>:<p>No annotations on this page.</p>}</aside>{error&&<p role="alert">{error}</p>}<p className="sr-only" role="status" aria-live="polite">{status}</p></section></ModuleShell>}

function AnnotationShape({item}:{item:Annotation}){const geometry=item.geometry;if(item.kind==="ink")return <svg className="pdf-overlay" viewBox="0 0 1 1" preserveAspectRatio="none"><polyline points={(geometry.points||[]).map(point=>point.join(",")).join(" ")}/></svg>;const style={left:`${(geometry.x||0)*100}%`,top:`${(geometry.y||0)*100}%`,width:`${(geometry.width||0)*100}%`,height:`${(geometry.height||0)*100}%`};return item.kind==="text"?<span className="pdf-text-annotation" style={style}>{item.content}</span>:<span className="pdf-highlight" style={style}/>}
