"use client";

import Link from "next/link";
import {FormEvent, useRef, useState} from "react";
import {ArrowLeft, CheckCircle, Play, ShieldCheck, Sparkle, Terminal, WarningCircle} from "@phosphor-icons/react";
import {ModuleShell} from "../../components/ModuleShell";
import {TutorPanel} from "../../components/TutorPanel";

const starters={javascript:"console.log(6 * 7);",python:"print(6 * 7)",c:'#include <stdio.h>\nint main(void) { printf("%d\\n", 6 * 7); }',cpp:'#include <iostream>\nint main() { std::cout << 6 * 7 << "\\n"; }',go:'package main\nimport "fmt"\nfunc main() { fmt.Println(6 * 7) }',rust:'fn main() { println!("{}", 6 * 7); }',java:'public class Main { public static void main(String[] args) { System.out.println(6 * 7); } }'};
type Language=keyof typeof starters;
type Result={code:number;output:string;truncated:boolean;stage:string;durationMs:number};
type Approval={id:string;details:{summary:string;commands:string[];files:string[];diff:string};expiresAt:string};

export default function CompilerPage(){
  const [language,setLanguage]=useState<Language>("javascript"),[code,setCode]=useState(starters.javascript),[result,setResult]=useState<Result|null>(null),[approval,setApproval]=useState<Approval|null>(null),[error,setError]=useState(""),[running,setRunning]=useState(false),[tutorOpen,setTutorOpen]=useState(false);
  const textareaRef=useRef<HTMLTextAreaElement>(null);
  function insert(text:string){const el=textareaRef.current;if(!el)return;const start=el.selectionStart,end=el.selectionEnd;el.setRangeText(text,start,end,"end");setCode(el.value);el.focus();}
  const mobileKeys=["()","{}","[]",";","\"","'","=","=>","  "];
  function changeLanguage(value:Language){setLanguage(value);setCode(starters[value]);setResult(null);setError("")}
  async function run(event:FormEvent){event.preventDefault();setRunning(true);setError("");setResult(null);try{const response=await fetch("/api/v1/approvals",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({actionType:"compiler.run",action:{language,code},risk:"high",summary:"Compile and run this source in the isolated workspace",commands:[`compile-and-run ${language}`],files:[`main.${language}`],diff:code})}),body=await response.json();if(!response.ok)throw new Error(body.error?.message||"Approval could not be created");setApproval(body)}catch(reason){setError(reason instanceof Error?reason.message:"Approval could not be created")}finally{setRunning(false)}}
  async function approveRun(){if(!approval)return;setRunning(true);setError("");try{let response=await fetch(`/api/v1/approvals/${approval.id}/approve`,{method:"POST"}),body=await response.json();if(!response.ok)throw new Error(body.error?.message||"Approval failed");response=await fetch("/api/v1/compiler/run",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({language,code,approvalId:approval.id})});body=await response.json();if(!response.ok)throw new Error(body.error?.message||"Compilation failed");setApproval(null);setResult(body)}catch(reason){setError(reason instanceof Error?reason.message:"Compilation failed")}finally{setRunning(false)}}
  return <ModuleShell active="Coding" title="Compiler" action={<Link className="secondary" href="/coding"><ArrowLeft/>Coding</Link>}><form className="compiler-workspace" onSubmit={run}><header><div><h2>Run code safely</h2><p>Each run uses a disposable, network-isolated workspace with time and output limits.</p></div><button className="secondary" type="button" onClick={()=>setTutorOpen(true)}><Sparkle/>Ask tutor</button><label>Language<select value={language} onChange={event=>changeLanguage(event.target.value as Language)}>{Object.keys(starters).map(item=><option key={item}>{item}</option>)}</select></label><button className="primary" disabled={running||!code.trim()}>{running?"Preparing…":<><Play/>Review run</>}</button></header><label className="code-editor"><span>Source</span><textarea ref={textareaRef} value={code} onChange={event=>{setCode(event.target.value);setApproval(null)}} spellCheck={false} aria-label="Source code"/><div className="mobile-toolbar" aria-label="Mobile editor keys">{mobileKeys.map(key=><button type="button" key={key} onClick={()=>insert(key)}>{key}</button>)}</div></label>{approval&&<section className="compiler-output" aria-label="Run approval"><header><ShieldCheck/><strong>Approval required · high risk</strong><small>Expires {new Date(approval.expiresAt).toLocaleTimeString()}</small></header><p>{approval.details.summary}</p><strong>Command</strong><pre><code>{approval.details.commands.join("\n")}</code></pre><strong>Affected files</strong><pre><code>{approval.details.files.join("\n")}</code></pre><strong>Source</strong><pre><code>{approval.details.diff}</code></pre><button type="button" className="secondary" onClick={()=>setApproval(null)}>Reject</button><button type="button" className="primary" disabled={running} onClick={()=>void approveRun()}>Approve and run</button></section>}<section className="compiler-output" aria-live="polite"><header><Terminal/><strong>Output</strong>{result&&<small>{result.stage} · {result.durationMs} ms · exit {result.code}</small>}</header>{error?<div className="compiler-error" role="alert"><WarningCircle/><span>{error}</span></div>:result?<><div className={result.code===0?"compiler-success":"compiler-error"}>{result.code===0?<CheckCircle/>:<WarningCircle/>}<span>{result.code===0?"Run completed":"Run failed"}{result.truncated?" · output truncated":""}</span></div><pre><code>{result.output||"(no output)"}</code></pre></>:<p>Review and approve the source to run it.</p>}</section></form>{tutorOpen&&<TutorPanel kind="code" context={{name:`main.${language}`,language,code}} onApply={value=>value&&setCode(value)} onClose={()=>setTutorOpen(false)}/>}</ModuleShell>;
}
