"use client";

import {FormEvent, useEffect, useState} from "react";
import {Archive, CalendarBlank, CaretDown, Check, Circle, Flag, Plus, X} from "@phosphor-icons/react";
import {ModuleShell} from "../components/ModuleShell";
import {Task, useAppState} from "../components/AppState";

const blankTask=():Task=>({id:crypto.randomUUID(),title:"",project:"Inbox",due:"Today",priority:"Medium",completed:false});
const reminderValue=(value?:string|null)=>value?new Date(new Date(value).getTime()-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16):"";

export default function TasksPage(){
  const {tasks,toggleTask,saveTask,archiveTask}=useAppState();
  const [filter,setFilter]=useState("Today");
  const [draft,setDraft]=useState<Task|null>(null);
  useEffect(()=>{const id=new URLSearchParams(location.search).get("open"),task=tasks.find(item=>item.id===id);if(task){setFilter("Inbox");setDraft({...task})}},[tasks]);
  function submit(event:FormEvent){event.preventDefault();if(!draft?.title.trim())return;saveTask({...draft,title:draft.title.trim(),project:draft.project.trim()||"Inbox"});setDraft(null)}
  const visible=tasks.filter(task=>filter==="Completed"?task.completed&&!task.archived:filter==="Someday"?task.due==="No date"&&!task.archived:filter==="Upcoming"?!["Today","No date"].includes(task.due)&&!task.completed&&!task.archived:filter==="Today"?task.due==="Today"&&!task.completed&&!task.archived:!task.archived);
  return <ModuleShell active="Tasks" title="Tasks" action={<button className="primary top-primary" onClick={()=>setDraft(blankTask())}><Plus/>New task</button>}>
    <div className="module-header"><div><h2>What needs doing</h2><p>Four tasks are ready. Start with the proposal review.</p></div><button className="filter-button"><CalendarBlank/>{filter}<CaretDown/></button></div>
    <div className="task-layout">
      <nav className="subnav" aria-label="Task views">{[["Inbox",3],["Today",4],["Upcoming",8],["Overdue",2],["Someday",0],["Completed",12]].map(([label,count])=><button className={label===filter?"active":""} key={label} onClick={()=>setFilter(label as string)}><span>{label}</span><small>{count}</small></button>)}</nav>
      <section className="task-list" aria-labelledby="task-list-title"><div className="list-title"><h3 id="task-list-title">{filter}</h3><span>{visible.length} shown</span></div>{visible.map(task=><article className={`${task.completed?"completed ":""}${draft?.id===task.id?"selected":""}`} key={task.id}><button className="task-check" aria-label={`${task.completed?"Reopen":"Complete"} ${task.title}`} aria-pressed={task.completed} onClick={()=>toggleTask(task.id)}>{task.completed?<Check weight="bold"/>:<Circle/>}</button><button className="task-copy" onClick={()=>setDraft({...task})}><strong>{task.title}</strong><span><Flag/> {task.project}{task.subtasks?.length?` · ${task.subtasks.length} subtasks`:""}</span></button><time>{task.due}</time><span className={`priority ${task.priority.toLowerCase()}`}>{task.priority}</span><button className="row-menu" aria-label={`Edit ${task.title}`} onClick={()=>setDraft({...task})}>Edit</button></article>)}{!visible.length&&<div className="empty-state"><Check/><h3>Nothing here</h3><p>This view is clear.</p></div>}</section>
      {draft?<aside className="object-inspector"><div className="object-inspector-head"><div><span>{tasks.some(task=>task.id===draft.id)?"Edit task":"New task"}</span><small>Use plain language; changes appear on Today immediately.</small></div><button className="icon-button" aria-label="Close task inspector" onClick={()=>setDraft(null)}><X/></button></div><form onSubmit={submit}><label>Task name<input autoFocus value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="What needs doing?" required/></label><label>Project<input value={draft.project} onChange={e=>setDraft({...draft,project:e.target.value})}/></label><div className="field-row"><label>Due<select value={draft.due} onChange={e=>setDraft({...draft,due:e.target.value})}><option>Today</option><option>Tomorrow</option><option>Friday</option><option>No date</option></select></label><label>Priority<select value={draft.priority} onChange={e=>setDraft({...draft,priority:e.target.value as Task["priority"]})}><option>High</option><option>Medium</option><option>Low</option></select></label></div><label>Reminder<input type="datetime-local" value={reminderValue(draft.reminderAt)} onChange={e=>setDraft({...draft,reminderAt:e.target.value?new Date(e.target.value).toISOString():null})}/></label><label>Repeat<select value={draft.recurrence||"Never"} onChange={e=>setDraft({...draft,recurrence:e.target.value})}><option>Never</option><option>Daily</option><option>Weekdays</option><option>Weekly</option><option>Monthly</option></select></label><label>Subtasks<textarea value={(draft.subtasks||[]).join("\n")} onChange={e=>setDraft({...draft,subtasks:e.target.value.split("\n").filter(Boolean)})} placeholder="One subtask per line"/></label><label className="check-field"><input type="checkbox" checked={draft.completed} onChange={e=>setDraft({...draft,completed:e.target.checked})}/> Mark completed</label><div className="inspector-actions">{tasks.some(task=>task.id===draft.id)&&<button type="button" className="icon-button danger" aria-label="Archive task" onClick={()=>{archiveTask(draft.id);setDraft(null)}}><Archive/></button>}<button type="button" className="secondary" onClick={()=>setDraft(null)}>Cancel</button><button className="primary">Save task</button></div></form></aside>:<aside className="task-focus"><Flag/><h3>Select a task</h3><p>Open any task to change its schedule, recurrence, subtasks, project, or priority.</p><button className="secondary" onClick={()=>setDraft(blankTask())}><Plus/>Add task</button></aside>}
    </div>
  </ModuleShell>
}
