"use client";
import {FormEvent,useEffect,useState} from "react";
import {Key,Plus,Robot,Trash} from "@phosphor-icons/react";

type Agent={id:string;name:string;provider:string;model:string;profile:string;baseUrl:string;enabled:boolean;hasApiKey:boolean};
const providers=["gemini","openai","deepseek","glm","kimi","qwen"];
export function AIAgentSettings(){
  const [agents,setAgents]=useState<Agent[]>([]),[error,setError]=useState(""),[saving,setSaving]=useState(false);
  async function load(){const response=await fetch("/api/v1/ai-agents"),data=await response.json();if(!response.ok)throw new Error(data.error?.message||"Could not load AI agents");setAgents(data.agents)}
  useEffect(()=>{load().catch(reason=>setError(reason.message))},[]);
  async function add(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError("");const form=event.currentTarget,data=Object.fromEntries(new FormData(form));try{const response=await fetch("/api/v1/ai-agents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)}),body=await response.json();if(!response.ok)throw new Error(body.error?.message||"Could not add agent");form.reset();await load()}catch(reason){setError((reason as Error).message)}finally{setSaving(false)}}
  async function remove(id:string){setError("");const response=await fetch("/api/v1/ai-agents",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})}),body=await response.json();if(!response.ok){setError(body.error?.message||"Could not remove agent");return}setAgents(items=>items.filter(item=>item.id!==id))}
  return <section className="ai-agent-settings"><header><div><h3>AI agents</h3><p>Add models and credentials here. Changes apply to new requests immediately.</p></div><Key/></header>{error&&<div className="tutor-error" role="alert">{error}</div>}<div className="ai-agent-list">{agents.map(agent=><article key={agent.id}><Robot/><span><strong>{agent.name}</strong><small>{agent.provider} · {agent.model} · {agent.profile}</small></span><em>{agent.hasApiKey?"Key saved":"No key"}</em><button className="icon-button danger" aria-label={`Remove ${agent.name}`} onClick={()=>void remove(agent.id)}><Trash/></button></article>)}{!agents.length&&<p>No in-app agents yet. Environment providers remain available as fallback.</p>}</div><form onSubmit={add}><label>Name<input name="name" placeholder="Fast Gemini" maxLength={80} required/></label><label>Provider<select name="provider" defaultValue="gemini">{providers.map(provider=><option key={provider}>{provider}</option>)}</select></label><label>Model<input name="model" placeholder="gemini-2.5-flash" required/></label><label>Profile<select name="profile" defaultValue="fast"><option>fast</option><option>balanced</option><option>quality</option></select></label><label className="agent-api-key">API key<input name="apiKey" type="password" autoComplete="new-password" placeholder="Stored encrypted" required/></label><label className="agent-base-url">Base URL <small>Optional; compatible providers only</small><input name="baseUrl" type="url" placeholder="https://api.example.com/v1"/></label><button className="primary" disabled={saving}><Plus/>{saving?"Adding…":"Add agent"}</button></form></section>
}
