"use client";

import {FormEvent,useEffect,useState} from "react";
import {CheckCircle,Folder,NotePencil,X} from "@phosphor-icons/react";
import {createId} from "../lib/id";
import {InkStroke,normalizeInk} from "../lib/ink";
import {deleteInkDraft} from "../lib/offlineQueue";
import {InkEditor} from "./InkEditor";
import {ModalDialog} from "./ModalDialog";

type Source={id:string;name:string};
export function HandwritingCapture({onClose}:{onClose:()=>void}){
  const [mode,setMode]=useState<"quick"|"folder">("quick"),[draft,setDraft]=useState(true),[title,setTitle]=useState(""),[sourceId,setSourceId]=useState(""),[sources,setSources]=useState<Source[]>([]),[folders,setFolders]=useState<string[]>([]),[folder,setFolder]=useState(""),[strokes,setStrokes]=useState<InkStroke[]>([]),[inkId,setInkId]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<{path:string;state:string}|null>(null);
  useEffect(()=>{const key="noema-handwriting-capture-id",id=localStorage.getItem(key)||createId();localStorage.setItem(key,id);setInkId(id)},[]);
  useEffect(()=>{let live=true;Promise.all([fetch("/api/v1/settings").then(response=>response.json()),fetch("/api/v1/vault-sources").then(response=>response.json())]).then(([settings,vaults])=>{if(!live)return;const available=vaults.sources||[],configured=settings.preferences?.captureVaultSourceId,selected=available.some((item:Source)=>item.id===configured)?configured:available[0]?.id||"";setSources(available);setSourceId(selected)}).catch(()=>setError("Could not load the capture vault" )).finally(()=>setLoading(false));return()=>{live=false}},[]);
  useEffect(()=>{if(!sourceId){setFolders([]);setFolder("");return}fetch(`/api/v1/vault-sources/${sourceId}/tree`).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error?.message);setFolders(data.folders||[]);setFolder(current=>(data.folders||[]).includes(current)?current:"")}).catch(()=>setError("Could not load vault folders"))},[sourceId]);
  async function submit(event:FormEvent){event.preventDefault();if(!strokes.length||mode==="folder"&&(!title.trim()||!folder))return;setSaving(true);setError("");try{const ink=normalizeInk(strokes),response=await fetch("/api/v1/handwriting-notes",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":createId()},body:JSON.stringify({mode,vaultSourceId:sourceId,folder,title:title.trim(),draft,ink})}),data=await response.json();if(!response.ok)throw new Error(data.error?.message||"Could not save handwriting");await deleteInkDraft(inkId);localStorage.removeItem("noema-handwriting-capture-id");setResult(data)}catch(reason){setError(reason instanceof Error?reason.message:"Could not save handwriting")}finally{setSaving(false)}}
  return <ModalDialog className="handwriting-dialog full-screen-handwriting" ariaLabel="Create handwritten note" onClose={onClose}>{result?<section className="handwriting-complete"><CheckCircle/><h2>Handwriting saved</h2><p>{result.path}</p><small>{result.state==="queued"?"Queued for the next Process Inbox run.":"Saved without AI processing."}</small><button className="primary" onClick={onClose}>Close</button></section>:<form onSubmit={submit} className="handwriting-form-layout"><header><div><NotePencil/><span><h2>Handwrite</h2><p>Keep original ink editable in your vault.</p></span></div><fieldset className="handwriting-mode"><legend>Destination</legend><label><input type="radio" name="handwriting-mode" checked={mode==="quick"} onChange={()=>setMode("quick")}/><span><strong>Quick note</strong><small>Save to Drafts and process later.</small></span></label><label><input type="radio" name="handwriting-mode" checked={mode==="folder"} onChange={()=>setMode("folder")}/><span><strong>Choose folder</strong><small>File directly into vault.</small></span></label></fieldset><button type="button" className="icon-button" aria-label="Close handwriting" onClick={onClose}><X/></button></header>{loading?<p role="status">Loading capture vault…</p>:!sources.length?<p role="alert">Connect a capture vault in Settings before handwriting.</p>:<><div className="handwriting-config-row"><label>Vault<select value={sourceId} onChange={event=>setSourceId(event.target.value)}>{sources.map(source=><option value={source.id} key={source.id}>{source.name}</option>)}</select></label>{mode==="folder"&&<div className="handwriting-destination"><label>Title<input value={title} onChange={event=>setTitle(event.target.value)} required autoFocus placeholder="Note title"/></label><fieldset><legend>Folder</legend><div className="handwriting-folders">{folders.map(path=><button type="button" className={folder===path?"active":""} aria-pressed={folder===path} onClick={()=>setFolder(path)} key={path}><Folder/>{path}</button>)}</div>{!folders.length&&<small>No folders are available in this vault.</small>}</fieldset></div>}<label className="check-field"><input type="checkbox" checked={draft} onChange={event=>setDraft(event.target.checked)}/> Draft</label></div><div className="handwriting-canvas-frame"><InkEditor id={inkId} capture onChange={setStrokes}/></div></>} {error&&<p className="auth-error" role="alert">{error}</p>}<footer><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={saving||loading||!sourceId||!strokes.length||mode==="folder"&&(!title.trim()||!folder)}>{saving?"Saving…":"Done"}</button></footer></form>}</ModalDialog>;
}
