"use client";

import {createId} from "../lib/id";
import {useEffect,useRef,useState} from "react";
import {ArrowCounterClockwise,ArrowClockwise,FloppyDisk,Plus} from "@phosphor-icons/react";
import {useAppState} from "./AppState";

type Kind="text"|"note"|"task"|"event"|"project"|"asset"|"ink";
type Item={id:string;type:Kind;x:number;y:number;width:number;height:number;title:string;refId?:string;payload?:Record<string,unknown>};
type Viewport={x:number;y:number;zoom:number};
type Canvas={id?:string;name:string;viewport:Viewport;objects:Item[];version?:number};
const blank:Canvas={name:"Untitled canvas",viewport:{x:0,y:0,zoom:1},objects:[]};
const clamp=(value:number,min:number,max:number)=>Math.min(max,Math.max(min,value));

export default function InfiniteCanvas(){
  const {notes,tasks,events,projects}=useAppState(),links=[...notes.map(item=>({id:item.id,type:"note" as const,title:item.title})),...tasks.map(item=>({id:item.id,type:"task" as const,title:item.title})),...events.map(item=>({id:item.id,type:"event" as const,title:item.title})),...projects.map(item=>({id:item.id,type:"project" as const,title:item.name}))];
  const board=useRef<HTMLDivElement>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),drag=useRef<{id?:string;resize?:boolean;x:number;y:number;originX:number;originY:number;before:Canvas}|null>(null),longPress=useRef<ReturnType<typeof setTimeout>|null>(null),pointers=useRef(new Map<number,{x:number;y:number}>()),pinch=useRef<number|null>(null);
  const [canvas,setCanvas]=useState(blank),[selected,setSelected]=useState<string|null>(null),[history,setHistory]=useState<Canvas[]>([]),[future,setFuture]=useState<Canvas[]>([]),[status,setStatus]=useState("Loading…");
  useEffect(()=>{fetch("/api/v1/canvases").then(async response=>{if(!response.ok)throw new Error("Canvas load failed");return response.json()}).then(({canvases})=>{setCanvas(canvases[0]||blank);setStatus(canvases.length?"Saved":"New canvas")}).catch(error=>setStatus(error.message))},[]);
  function commit(next:Canvas){setHistory(values=>[...values.slice(-49),canvas]);setFuture([]);setCanvas(next);schedule(next)}
  function schedule(next:Canvas){if(timer.current)clearTimeout(timer.current);setStatus("Unsaved changes");timer.current=setTimeout(()=>void save(next),500)}
  async function save(next=canvas){const response=await fetch(next.id?`/api/v1/canvases/${next.id}`:"/api/v1/canvases",{method:next.id?"PATCH":"POST",headers:{"Content-Type":"application/json","Idempotency-Key":createId()},body:JSON.stringify(next)});const data=await response.json();if(response.status===409){setStatus("Changed elsewhere — reload before saving");return}if(!response.ok){setStatus(data.error?.message||"Save failed");return}setCanvas(current=>current.version===next.version||!current.id?data:current);setStatus("Saved")}
  function add(type:Kind="text"){commit({...canvas,objects:[...canvas.objects,{id:createId(),type,x:(-canvas.viewport.x+120)/canvas.viewport.zoom,y:(-canvas.viewport.y+100)/canvas.viewport.zoom,width:220,height:120,title:`New ${type}`}]})}
  function addLinked(refId:string){const link=links.find(item=>item.id===refId);if(!link)return;commit({...canvas,objects:[...canvas.objects,{id:createId(),type:link.type,refId:link.id,title:link.title,x:(-canvas.viewport.x+120)/canvas.viewport.zoom,y:(-canvas.viewport.y+100)/canvas.viewport.zoom,width:220,height:120}]})}
  function undo(){const previous=history.at(-1);if(!previous)return;setFuture(values=>[canvas,...values]);setHistory(values=>values.slice(0,-1));setCanvas(previous);schedule(previous)}
  function redo(){const next=future[0];if(!next)return;setHistory(values=>[...values,canvas]);setFuture(values=>values.slice(1));setCanvas(next);schedule(next)}
  function moveSelected(dx:number,dy:number){if(!selected)return;commit({...canvas,objects:canvas.objects.map(item=>item.id===selected?{...item,x:item.x+dx/canvas.viewport.zoom,y:item.y+dy/canvas.viewport.zoom}:item)})}
  function keyDown(event:React.KeyboardEvent){const amount=event.shiftKey?10:1;if(event.key==="ArrowLeft")moveSelected(-amount,0);else if(event.key==="ArrowRight")moveSelected(amount,0);else if(event.key==="ArrowUp")moveSelected(0,-amount);else if(event.key==="ArrowDown")moveSelected(0,amount);else if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="z"){event.preventDefault();event.shiftKey?redo():undo()}else return;event.preventDefault()}
  function down(event:React.PointerEvent,id?:string,resize=false){event.currentTarget.setPointerCapture(event.pointerId);pointers.current.set(event.pointerId,{x:event.clientX,y:event.clientY});if(pointers.current.size===2){const [a,b]=[...pointers.current.values()];pinch.current=Math.hypot(a.x-b.x,a.y-b.y);return}const item=canvas.objects.find(value=>value.id===id);drag.current={id,resize,x:event.clientX,y:event.clientY,originX:resize?item?.width??0:item?.x??canvas.viewport.x,originY:resize?item?.height??0:item?.y??canvas.viewport.y,before:canvas};if(id)longPress.current=setTimeout(()=>setSelected(id),450);setSelected(id||null)}
  function move(event:React.PointerEvent){const previous=pointers.current.get(event.pointerId);pointers.current.set(event.pointerId,{x:event.clientX,y:event.clientY});if(pointers.current.size===2&&pinch.current){const [a,b]=[...pointers.current.values()],distance=Math.hypot(a.x-b.x,a.y-b.y),zoom=clamp(canvas.viewport.zoom*distance/pinch.current,.1,8);pinch.current=distance;setCanvas({...canvas,viewport:{...canvas.viewport,zoom}});return}if(!drag.current||!previous)return;const dx=event.clientX-drag.current.x,dy=event.clientY-drag.current.y;if(Math.abs(dx)+Math.abs(dy)>4&&longPress.current)clearTimeout(longPress.current);if(drag.current.id)setCanvas({...canvas,objects:canvas.objects.map(item=>item.id===drag.current?.id?(drag.current.resize?{...item,width:clamp(drag.current.originX+dx/canvas.viewport.zoom,80,4000),height:clamp(drag.current.originY+dy/canvas.viewport.zoom,48,4000)}:{...item,x:drag.current.originX+dx/canvas.viewport.zoom,y:drag.current.originY+dy/canvas.viewport.zoom}):item)});else setCanvas({...canvas,viewport:{...canvas.viewport,x:drag.current.originX+dx,y:drag.current.originY+dy}})}
  function up(event:React.PointerEvent){pointers.current.delete(event.pointerId);pinch.current=null;if(longPress.current)clearTimeout(longPress.current);if(drag.current){schedule(canvas);setHistory(values=>[...values.slice(-49),drag.current!.before]);setFuture([]);drag.current=null}}
  function wheel(event:React.WheelEvent){event.preventDefault();const zoom=clamp(canvas.viewport.zoom*Math.exp(-event.deltaY*.001),.1,8),rect=board.current?.getBoundingClientRect();if(!rect)return;const px=event.clientX-rect.left,py=event.clientY-rect.top,worldX=(px-canvas.viewport.x)/canvas.viewport.zoom,worldY=(py-canvas.viewport.y)/canvas.viewport.zoom;const next={...canvas,viewport:{x:px-worldX*zoom,y:py-worldY*zoom,zoom}};setCanvas(next);schedule(next)}
  const bounds=board.current?.getBoundingClientRect(),visible=canvas.objects.filter(item=>!bounds||item.x*canvas.viewport.zoom+canvas.viewport.x<bounds.width+300&&item.y*canvas.viewport.zoom+canvas.viewport.y<bounds.height+300&&item.x*canvas.viewport.zoom+canvas.viewport.x+item.width*canvas.viewport.zoom>-300&&item.y*canvas.viewport.zoom+canvas.viewport.y+item.height*canvas.viewport.zoom>-300);
  return <section className="infinite-canvas"><header className="canvas-toolbar"><label>Canvas name<input value={canvas.name} maxLength={200} onChange={event=>commit({...canvas,name:event.target.value})}/></label><label>Add object<select defaultValue="text" onChange={event=>add(event.target.value as Kind)}><option value="text">Text</option><option value="note">Note</option><option value="task">Task</option><option value="event">Event</option><option value="project">Project</option><option value="asset">Asset</option><option value="ink">Ink</option></select></label><button onClick={()=>add()}><Plus/>Add</button><label>Link canonical object<select defaultValue="" onChange={event=>{addLinked(event.target.value);event.target.value=""}}><option value="">Choose…</option>{links.map(item=><option key={`${item.type}-${item.id}`} value={item.id}>{item.type} · {item.title}</option>)}</select></label><button aria-label="Undo" disabled={!history.length} onClick={undo}><ArrowCounterClockwise/>Undo</button><button aria-label="Redo" disabled={!future.length} onClick={redo}><ArrowClockwise/>Redo</button><button className="primary" onClick={()=>void save()}><FloppyDisk/>Save</button><span className={`canvas-save-status ${status==="Saved"?"is-saved":""}`} role="status">{status}</span></header><div ref={board} className="canvas-viewport" tabIndex={0} aria-label="Infinite canvas. Use arrow keys to move the selected object." onKeyDown={keyDown} onWheel={wheel} onPointerDown={event=>down(event)} onPointerMove={move} onPointerUp={up} onPointerCancel={up}><div className="canvas-world" style={{transform:`translate(${canvas.viewport.x}px,${canvas.viewport.y}px) scale(${canvas.viewport.zoom})`}}>{visible.map(item=><article key={item.id} className={`canvas-object ${selected===item.id?"selected":""}`} style={{transform:`translate(${item.x}px,${item.y}px)`,width:item.width,height:item.height}} onPointerDown={event=>{event.stopPropagation();down(event,item.id)}}><small>{item.type}</small><input aria-label={`${item.type} title`} value={item.title} onChange={event=>commit({...canvas,objects:canvas.objects.map(value=>value.id===item.id?{...value,title:event.target.value}:value)})}/><button className="resize-handle" aria-label={`Resize ${item.title}`} onPointerDown={event=>{event.stopPropagation();down(event,item.id,true)}}>↘</button></article>)}</div></div><details><summary>Accessible object list ({canvas.objects.length})</summary><ul>{canvas.objects.map(item=><li key={item.id}><button aria-pressed={selected===item.id} onClick={()=>setSelected(item.id)}>{item.type}: {item.title}</button><button onClick={()=>moveSelected(-10,0)}>Move left</button><button onClick={()=>moveSelected(10,0)}>Move right</button></li>)}</ul></details></section>
}
