"use client";
import {useEffect,useRef,useState} from "react";
import {ArrowCounterClockwise,ArrowClockwise,Copy,FloppyDisk,HighlighterCircle,PenNib,Selection,Trash} from "@phosphor-icons/react";
import {acceptInkPointer,eraseAt,inkPoint,InkPoint,InkStroke,InkTool,strokePath} from "../lib/ink";
import {deleteInkDraft,loadInkDraft,saveInkDraft} from "../lib/offlineQueue";

type Props={id:string;noteId:string;width?:number;height?:number;strokes?:InkStroke[];version?:number;transcript?:string;ocrStatus?:string;onSaved:()=>void};
export function InkEditor({id,noteId,width=900,height=420,strokes:initial=[],version=0,transcript="",ocrStatus="pending",onSaved}:Props){
  const svg=useRef<SVGSVGElement>(null),active=useRef<InkStroke|null>(null),lasso=useRef<InkPoint|null>(null),penActive=useRef(false),[strokes,setStrokes]=useState(initial),[redo,setRedo]=useState<InkStroke[][]>([]),[selected,setSelected]=useState<string[]>([]),[tool,setTool]=useState<InkTool>("pen"),[color,setColor]=useState("#e8eef5"),[size,setSize]=useState(3),[canvasHeight,setCanvasHeight]=useState(height),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[text,setText]=useState(transcript);
  useEffect(()=>{loadInkDraft(id).then(draft=>{if(draft?.strokes.length)setStrokes(draft.strokes as InkStroke[])}).catch(()=>{})},[id]);
  function persist(next:InkStroke[]){setStrokes(next);void saveInkDraft({id,noteId,width,height:canvasHeight,strokes:next})}
  function down(event:React.PointerEvent<SVGSVGElement>){if(!acceptInkPointer(event.pointerType,penActive.current))return;if(event.pointerType==="pen")penActive.current=true;event.currentTarget.setPointerCapture(event.pointerId);const points=(event.nativeEvent.getCoalescedEvents?.()||[event.nativeEvent]).map(item=>inkPoint(item,event.currentTarget.getBoundingClientRect()));if(tool==="eraser"){persist(eraseAt(strokes,points[0],size*3));setRedo([]);return}if(tool==="lasso"){lasso.current=points[0];return}active.current={id:crypto.randomUUID(),tool,color,width:size,points};setStrokes([...strokes,active.current])}
  function move(event:React.PointerEvent<SVGSVGElement>){if(!active.current)return;const next=event.nativeEvent.getCoalescedEvents?.()||[event.nativeEvent],rect=event.currentTarget.getBoundingClientRect();active.current={...active.current,points:[...active.current.points,...next.map(item=>inkPoint(item,rect))]};setStrokes(items=>[...items.slice(0,-1),active.current!])}
  function up(event:React.PointerEvent<SVGSVGElement>){if(active.current){active.current=null;persist(strokes);setRedo([])}if(lasso.current){const end=inkPoint(event,event.currentTarget.getBoundingClientRect()),left=Math.min(lasso.current.x,end.x),right=Math.max(lasso.current.x,end.x),top=Math.min(lasso.current.y,end.y),bottom=Math.max(lasso.current.y,end.y);setSelected(strokes.filter(stroke=>stroke.points.some(point=>point.x>=left&&point.x<=right&&point.y>=top&&point.y<=bottom)).map(stroke=>stroke.id));lasso.current=null}if(event.pointerType==="pen")penActive.current=false}
  function undo(){if(!strokes.length)return;setRedo(items=>[...items,strokes]);persist(strokes.slice(0,-1))}
  function redoStroke(){const next=redo.at(-1);if(!next)return;persist(next);setRedo(items=>items.slice(0,-1))}
  async function save(){setSaving(true);setMessage("");try{const response=await fetch(`/api/v1/notes/${noteId}/ink`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({id,width,height:canvasHeight,strokes,version})}),data=await response.json();if(!response.ok)throw new Error(data.error?.message||"Ink save failed");await deleteInkDraft(id);setMessage("Saved · OCR queued");onSaved()}catch(error){setMessage((error as Error).message||"Saved offline")}finally{setSaving(false)}}
  async function saveTranscript(){const response=await fetch(`/api/v1/ink/${id}/transcript`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({transcript:text,equations:[],version})});if(response.ok){setMessage("Transcript indexed");onSaved()}else setMessage((await response.json()).error?.message||"Transcript save failed")}
  return <section className="ink-workspace" aria-label="Handwriting block"><div className="ink-toolbar" role="toolbar" aria-label="Ink tools">{[["pen",PenNib],["highlighter",HighlighterCircle],["eraser",Trash],["lasso",Selection]].map(([name,Icon])=><button key={name as string} className={tool===name?"active":""} aria-pressed={tool===name} aria-label={name as string} onClick={()=>setTool(name as InkTool)}><Icon/></button>)}<input type="color" aria-label="Ink color" value={color} onChange={event=>setColor(event.target.value)}/><label>Width<input type="range" min="1" max="28" value={size} onChange={event=>setSize(Number(event.target.value))}/></label><label>Height<input aria-label="Canvas height" type="range" min="240" max="1200" step="20" value={canvasHeight} onChange={event=>setCanvasHeight(Number(event.target.value))}/></label>{selected.length>0&&<><button aria-label="Duplicate selection" onClick={()=>persist([...strokes,...strokes.filter(stroke=>selected.includes(stroke.id)).map(stroke=>({...stroke,id:crypto.randomUUID(),points:stroke.points.map(point=>({...point,x:Math.min(width,point.x+12),y:Math.min(canvasHeight,point.y+12)}))}))])}><Copy/></button><button aria-label="Delete selection" onClick={()=>{persist(strokes.filter(stroke=>!selected.includes(stroke.id)));setSelected([])}}><Trash/></button></>}<button aria-label="Undo" disabled={!strokes.length} onClick={undo}><ArrowCounterClockwise/></button><button aria-label="Redo" disabled={!redo.length} onClick={redoStroke}><ArrowClockwise/></button><button className="primary" disabled={saving} onClick={save}><FloppyDisk/>{saving?"Saving…":"Save ink"}</button></div><svg ref={svg} className="ink-canvas" viewBox={`0 0 ${width} ${canvasHeight}`} style={{aspectRatio:`${width}/${canvasHeight}`}} role="img" aria-label="Pressure-aware handwriting canvas" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}>{strokes.filter(stroke=>stroke.tool!=="eraser").map(stroke=><path key={stroke.id} d={strokePath(stroke)} fill="none" stroke={stroke.color} strokeWidth={stroke.width} opacity={selected.includes(stroke.id)?.5:stroke.tool==="highlighter"?.35:1} strokeLinecap="round" strokeLinejoin="round"/>)}</svg><div className="ink-transcript"><label>OCR transcript <small>{ocrStatus}</small><textarea value={text} onChange={event=>setText(event.target.value)} placeholder="OCR appears here; strokes remain authoritative."/></label><button className="secondary" onClick={saveTranscript}>Save correction</button>{message&&<span role="status">{message}</span>}</div></section>}
