"use client";
import {useEffect,useState} from "react";
import {ArrowDown,ArrowUp,Copy,PenNib,Plus,Trash} from "@phosphor-icons/react";
import {InkEditor} from "./InkEditor";
import type {InkStroke} from "../lib/ink";

type Block={id:string;position:number;kind:"markdown"|"ink";markdown:string;version:number;inkVersion?:number;width?:number;height?:number;strokes?:InkStroke[];transcript?:string;ocrStatus?:string;taskProposals?:{id:string;text:string;state:string}[]};
export function MixedNoteEditor({noteId}:{noteId:string}){const [blocks,setBlocks]=useState<Block[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true);async function load(){const response=await fetch(`/api/v1/notes/${noteId}/blocks`),data=await response.json();if(!response.ok)throw new Error(data.error?.message||"Could not load blocks");setBlocks(data.blocks);setLoading(false)}useEffect(()=>{load().catch(reason=>{setError(reason.message);setLoading(false)})},[noteId]);
  async function markdown(block:Block,value:string){setBlocks(items=>items.map(item=>item.id===block.id?{...item,markdown:value}:item));const response=await fetch(`/api/v1/notes/${noteId}/blocks/${block.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({markdown:value,version:block.version})});if(response.ok)await load();else setError((await response.json()).error?.message||"Save failed")}
  async function add(kind:"markdown"|"ink",source?:Block){if(kind==="markdown"){await fetch(`/api/v1/notes/${noteId}/blocks`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({markdown:source?.markdown||""})})}else{await fetch(`/api/v1/notes/${noteId}/ink`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({id:crypto.randomUUID(),width:900,height:420,strokes:source?.strokes||[]})})}await load()}
  async function remove(block:Block){const response=await fetch(`/api/v1/notes/${noteId}/blocks/${block.id}`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({version:block.version})});if(response.ok)await load();else setError((await response.json()).error?.message||"Delete failed")}
  async function move(index:number,delta:number){const ids=blocks.map(block=>block.id),next=index+delta;if(next<0||next>=ids.length)return;[ids[index],ids[next]]=[ids[next],ids[index]];const response=await fetch(`/api/v1/notes/${noteId}/blocks`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids})});if(response.ok)await load();else setError((await response.json()).error?.message||"Reorder failed")}
  if(loading)return <div className="mixed-editor-loading">Loading document…</div>;return <div className="mixed-note-editor">{error&&<div className="tutor-error" role="alert">{error}</div>}{blocks.map((block,index)=><article className="note-block" key={block.id}><nav aria-label={`${block.kind} block controls`}><span>{block.kind}</span><button aria-label="Move block up" disabled={!index} onClick={()=>move(index,-1)}><ArrowUp/></button><button aria-label="Move block down" disabled={index===blocks.length-1} onClick={()=>move(index,1)}><ArrowDown/></button><button aria-label="Duplicate block" onClick={()=>add(block.kind,block)}><Copy/></button><button aria-label="Remove block" disabled={blocks.length===1} onClick={()=>remove(block)}><Trash/></button></nav>{block.kind==="markdown"?<textarea aria-label="Markdown block" defaultValue={block.markdown} onBlur={event=>markdown(block,event.currentTarget.value)} spellCheck/>:<><InkEditor id={block.id} noteId={noteId} width={block.width} height={block.height} strokes={block.strokes} version={block.inkVersion} transcript={block.transcript} ocrStatus={block.ocrStatus} onSaved={load}/>{block.taskProposals?.some(item=>item.state==="review")&&<aside className="ink-task-proposals"><strong>Task proposals · review only</strong>{block.taskProposals.filter(item=>item.state==="review").map(item=><span key={item.id}>{item.text}</span>)}</aside>}</>}</article>)}<footer><button className="secondary" onClick={()=>add("markdown")}><Plus/>Typed block</button><button className="secondary" onClick={()=>add("ink")}><PenNib/>Ink block</button></footer></div>}
