"use client";
import {CSSProperties,FormEvent,PointerEvent,useEffect,useState} from "react";
import {ArrowsIn,ArrowsOut,Minus,PaperPlaneTilt,Sparkle,X} from "@phosphor-icons/react";
import {MarkdownContent} from "./MarkdownContent";
type Message={id?:string;role:"user"|"assistant";text:string;citations?:string[];replacement?:string;provider?:string;insertedNoteId?:string};
type Props={kind:"note"|"code";context:{id?:string;title?:string;content?:string;name?:string;language?:string;code?:string};onApply:(value:string)=>void;onClose:()=>void};
const modeKey="noema-tutor-mobile-mode";
export function TutorPanel({kind,context,onApply,onClose}:Props){
  const [messages,setMessages]=useState<Message[]>([]),[sessionId,setSessionId]=useState<string|null>(null),[question,setQuestion]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState(""),[mode,setMode]=useState<"minimized"|"sheet"|"full">("sheet"),[height,setHeight]=useState(58),[width,setWidth]=useState(360);
  useEffect(()=>{const stored=localStorage.getItem(modeKey);setMode(stored==="full"||stored==="minimized"?stored:"sheet");const savedWidth=Number(localStorage.getItem("noema-tutor-width"));if(savedWidth)setWidth(Math.max(320,Math.min(720,savedWidth)));const escape=(event:KeyboardEvent)=>{if(event.key==="Escape")onClose()};addEventListener("keydown",escape);return()=>removeEventListener("keydown",escape)},[onClose]);
  useEffect(()=>{const subjectId=context.id||context.name;if(!subjectId)return;fetch(`/api/v1/tutor?kind=${kind}&subjectId=${encodeURIComponent(subjectId)}`).then(response=>response.json()).then(data=>{setSessionId(data.sessionId);setMessages(data.messages||[])}).catch(()=>{})},[kind,context.id,context.name]);
  const changeMode=(value:"minimized"|"sheet"|"full")=>{setMode(value);localStorage.setItem(modeKey,value)};
  async function ask(event:FormEvent){event.preventDefault();const text=question.trim();if(!text||loading)return;const next=[...messages,{role:"user" as const,text}];setMessages(next);setQuestion("");setLoading(true);setError("");try{const response=await fetch("/api/v1/tutor",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,...context,sessionId,question:text})}),data=await response.json();if(!response.ok)throw new Error(data.error?.message||"Tutor unavailable");setSessionId(data.sessionId);setMessages([...next,{id:data.messageId,role:"assistant",text:data.answer,citations:data.citations,replacement:data.replacement,provider:data.provider}])}catch(reason){setError(reason instanceof Error?reason.message:"Tutor unavailable")}finally{setLoading(false)}}
  async function apply(message:Message){if(kind==="code"){onApply(message.replacement||"");return}if(!message.id||!context.id)return;setError("");const response=await fetch(`/api/v1/tutor/messages/${message.id}/insert`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({noteId:context.id})}),data=await response.json();if(!response.ok){setError(data.error?.message||"Insertion failed");return}setMessages(current=>current.map(item=>item.id===message.id?{...item,insertedNoteId:context.id}:item));onApply(message.text)}
  function resize(event:PointerEvent<HTMLDivElement>){if(mode!=="sheet")return;event.currentTarget.setPointerCapture(event.pointerId);const move=(next:globalThis.PointerEvent)=>setHeight(Math.max(35,Math.min(85,100-next.clientY/innerHeight*100))),stop=()=>{removeEventListener("pointermove",move);removeEventListener("pointerup",stop)};addEventListener("pointermove",move);addEventListener("pointerup",stop)}
  function resizeWidth(event:PointerEvent<HTMLDivElement>){if(mode!=="sheet"||innerWidth<=820)return;event.currentTarget.setPointerCapture(event.pointerId);const move=(next:globalThis.PointerEvent)=>{const value=Math.max(320,Math.min(720,innerWidth-next.clientX));setWidth(value);localStorage.setItem("noema-tutor-width",String(value))},stop=()=>{removeEventListener("pointermove",move);removeEventListener("pointerup",stop)};addEventListener("pointermove",move);addEventListener("pointerup",stop)}
  return <aside role="dialog" aria-modal={mode==="full"} className={`tutor-panel ${mode}`} style={{"--tutor-height":`${height}dvh`,"--tutor-width":`${width}px`} as CSSProperties} aria-label={`${kind==="note"?"Note":"Coding"} tutor`}><div className="tutor-width-drag" onPointerDown={resizeWidth}><span className="sr-only">Drag to resize tutor width</span></div><div className="tutor-drag" onPointerDown={resize}><span className="sr-only">Drag to resize tutor height</span></div><header><div onClick={()=>mode==="minimized"&&changeMode("sheet")}><Sparkle/><span><strong>{kind==="note"?"Note Tutor":"Coding Tutor"}</strong><small>{kind==="note"?context.title:context.name}</small></span></div><div><button className="icon-button" aria-label={mode==="minimized"?"Restore tutor":"Minimize tutor"} onClick={()=>changeMode(mode==="minimized"?"sheet":"minimized")}><Minus/></button><button className="icon-button" aria-label={mode==="full"?"Restore tutor":"Maximize tutor"} onClick={()=>changeMode(mode==="full"?"sheet":"full")}>{mode==="full"?<ArrowsIn/>:<ArrowsOut/>}</button><button className="icon-button" aria-label="Close tutor" onClick={onClose}><X/></button></div></header><div className="tutor-thread" aria-live="polite">{!messages.length&&<div className="tutor-empty"><Sparkle/><h3>Ask in context</h3><p>{kind==="note"?"Explore this note, work through the math, or connect related ideas.":"Explain behavior, diagnose an error, or improve the current buffer."}</p></div>}{messages.map((message,index)=><article className={message.role} key={message.id||index}><small>{message.role==="user"?"You":`Noema Tutor${message.provider?` · ${message.provider}`:""}`}</small><div className="tutor-message-content"><MarkdownContent text={message.text}/></div>{message.citations?.map(citation=><a key={citation}>{citation}</a>)}{message.role==="assistant"&&(kind==="note"||message.replacement)&&<button className="secondary" disabled={!!message.insertedNoteId} onClick={()=>apply(message)}>{message.insertedNoteId?"Added to note":kind==="note"?"Add to note":"Apply to editor"}</button>}</article>)}{loading&&<div className="tutor-thinking"><i/><span>Thinking with current context…</span></div>}{error&&<div className="tutor-error" role="alert">{error}</div>}</div><form onSubmit={ask}><label><span className="sr-only">Ask the tutor</span><textarea value={question} onChange={event=>setQuestion(event.target.value)} placeholder={kind==="note"?"Ask about this note":"Ask about this code"} rows={2}/></label><button className="primary icon-button" disabled={loading||!question.trim()} aria-label="Send question"><PaperPlaneTilt/></button></form></aside>;
}
