"use client";

import {CSSProperties,FormEvent,PointerEvent,useEffect,useState} from "react";
import {ArrowsIn,ArrowsOut,Minus,PaperPlaneTilt,Sparkle,X} from "@phosphor-icons/react";

type Message={role:"user"|"assistant";text:string;citations?:string[];replacement?:string};
type Props={kind:"note"|"code";context:{id?:string;title?:string;content?:string;name?:string;language?:string;code?:string};onApply:(value:string)=>void;onClose:()=>void};
const modeKey="lifeos-tutor-mobile-mode";

export function TutorPanel({kind,context,onApply,onClose}:Props){
  const [messages,setMessages]=useState<Message[]>([]),[question,setQuestion]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState(""),[mode,setMode]=useState<"sheet"|"full">("sheet"),[height,setHeight]=useState(58);
  useEffect(()=>{setMode(localStorage.getItem(modeKey)==="full"?"full":"sheet");const escape=(event:KeyboardEvent)=>{if(event.key==="Escape")onClose()};addEventListener("keydown",escape);return()=>removeEventListener("keydown",escape)},[onClose]);
  const changeMode=(value:"sheet"|"full")=>{setMode(value);localStorage.setItem(modeKey,value)};
  async function ask(event:FormEvent){event.preventDefault();const text=question.trim();if(!text||loading)return;const next=[...messages,{role:"user" as const,text}];setMessages(next);setQuestion("");setLoading(true);setError("");try{const response=await fetch("/api/v1/tutor",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,...context,question:text,messages:next})});const data=await response.json();if(!response.ok)throw new Error(data.error?.message||"Tutor unavailable");setMessages([...next,{role:"assistant",text:data.answer,citations:data.citations,replacement:data.replacement}])}catch(reason){setError(reason instanceof Error?reason.message:"Tutor unavailable")}finally{setLoading(false)}}
  function resize(event:PointerEvent<HTMLDivElement>){if(mode!=="sheet")return;event.currentTarget.setPointerCapture(event.pointerId);const move=(next:globalThis.PointerEvent)=>setHeight(Math.max(35,Math.min(85,100-next.clientY/innerHeight*100)));const stop=()=>{removeEventListener("pointermove",move);removeEventListener("pointerup",stop)};addEventListener("pointermove",move);addEventListener("pointerup",stop)}
  return <aside role="dialog" aria-modal={mode==="full"} className={`tutor-panel ${mode}`} style={{"--tutor-height":`${height}dvh`} as CSSProperties} aria-label={`${kind==="note"?"Note":"Coding"} tutor`}><div className="tutor-drag" onPointerDown={resize}><span className="sr-only">Drag to resize tutor</span></div><header><div><Sparkle/><span><strong>{kind==="note"?"Note Tutor":"Coding Tutor"}</strong><small>{kind==="note"?context.title:context.name}</small></span></div><div><button className="icon-button tutor-expand" aria-label={mode==="full"?"Use bottom sheet":"Open full screen"} onClick={()=>changeMode(mode==="full"?"sheet":"full")}>{mode==="full"?<ArrowsIn/>:<ArrowsOut/>}</button><button className="icon-button" aria-label="Close tutor" onClick={onClose}><X/></button></div></header><div className="tutor-thread" aria-live="polite">{!messages.length&&<div className="tutor-empty"><Sparkle/><h3>Ask in context</h3><p>{kind==="note"?"Explore this note, work through the math, or connect related ideas.":"Explain behavior, diagnose an error, or improve the current buffer."}</p></div>}{messages.map((message,index)=><article className={message.role} key={index}><small>{message.role==="user"?"You":"LifeOS Tutor"}</small><p>{message.text}</p>{message.citations?.map(citation=><a key={citation}>{citation}</a>)}{message.role==="assistant"&&(kind==="note"||message.replacement)&&<button className="secondary" onClick={()=>onApply(kind==="note"?message.text:message.replacement||"")}>{kind==="note"?"Add to note":"Apply to editor"}</button>}</article>)}{loading&&<div className="tutor-thinking"><i/><span>Thinking with current context…</span></div>}{error&&<div className="tutor-error" role="alert">{error}</div>}</div><form onSubmit={ask}><label><span className="sr-only">Ask the tutor</span><textarea value={question} onChange={event=>setQuestion(event.target.value)} placeholder={kind==="note"?"Ask about this note":"Ask about this code"} rows={2}/></label><button className="primary icon-button" disabled={loading||!question.trim()} aria-label="Send question"><PaperPlaneTilt/></button></form><button className="tutor-minimize" onClick={()=>changeMode("sheet")}><Minus/>Minimize</button></aside>}
