"use client";
import {useEffect,useState} from "react";
import {ArrowClockwise,Bell,Check,Warning} from "@phosphor-icons/react";
import {ModuleShell} from "../components/ModuleShell";
type Notice={id:string;kind:string;title:string;body:string;read_at:string|null;related_type:string|null;related_id:string|null;created_at:string};
type Delivery={id:string;notification_id:string;state:string;attempts:number;error:string|null;provider_status:number|null};
const href=(item:Notice)=>item.related_type==="task"?`/tasks?open=${item.related_id}`:item.related_type==="event"?`/calendar?open=${item.related_id}`:item.related_type==="note"?`/vault?open=${item.related_id}`:item.related_type==="project"?`/projects?open=${item.related_id}`:null;
export default function NotificationsPage(){
  const [notices,setNotices]=useState<Notice[]>([]),[deliveries,setDeliveries]=useState<Delivery[]>([]),[filter,setFilter]=useState("all"),[error,setError]=useState("");
  const load=()=>Promise.all([fetch("/api/v1/notifications").then(r=>r.json()),fetch("/api/v1/notification-deliveries").then(r=>r.json())]).then(([a,b])=>{setNotices(a.notifications||[]);setDeliveries(b.deliveries||[])}).catch(reason=>setError(reason.message));
  useEffect(()=>{void load();const source=new EventSource("/api/v1/notifications/events");source.addEventListener("snapshot",event=>{const data=JSON.parse((event as MessageEvent).data);setNotices(data.notifications);setDeliveries(data.deliveries)});return()=>source.close()},[]);
  async function allRead(){await fetch("/api/v1/notifications/read-all",{method:"POST"});setNotices(current=>current.map(item=>({...item,read_at:item.read_at||new Date().toISOString()})))}
  async function deliveryAction(id:string,action:"retry"|"resolve"){const response=await fetch(`/api/v1/notification-deliveries/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})});if(response.ok)void load();else setError((await response.json()).error?.message||"Action failed")}
  const shown=notices.filter(item=>filter==="all"||filter==="unread"&&!item.read_at||item.kind===filter),groups=new Map<string,Notice[]>();for(const item of shown){const day=new Date(item.created_at).toDateString();groups.set(day,[...(groups.get(day)||[]),item])}
  return <ModuleShell active="Notifications" title="Notifications" action={<button className="secondary" onClick={()=>void allRead()}><Check/>Mark all read</button>}><div className="module-header"><div><h2>Delivery and activity</h2><p>Review notifications and resolve delivery failures.</p></div><select value={filter} onChange={event=>setFilter(event.target.value)}><option value="all">All</option><option value="unread">Unread</option>{[...new Set(notices.map(item=>item.kind))].map(kind=><option key={kind}>{kind}</option>)}</select></div>{error&&<p role="alert">{error}</p>}{[...groups].map(([day,items])=><section className="audit-list" key={day}><h3>{day}</h3>{items.map(item=>{const related=href(item),attempts=deliveries.filter(delivery=>delivery.notification_id===item.id),failed=attempts.filter(delivery=>["failed","permanent-failure"].includes(delivery.state));return <article key={item.id}><span className="audit-icon">{failed.length?<Warning/>:<Bell/>}</span><div><strong>{item.title}</strong><span>{item.body||item.kind}</span><small>{attempts.length?attempts.map(delivery=>`${delivery.state}${delivery.provider_status?` (${delivery.provider_status})`:""}`).join(", "):"No push delivery requested"}</small>{failed.map(delivery=><small key={delivery.id}>{delivery.error||"Delivery failed"} <button onClick={()=>void deliveryAction(delivery.id,"retry")}><ArrowClockwise/>Retry</button> <button onClick={()=>void deliveryAction(delivery.id,"resolve")}>Resolve</button></small>)}</div>{related&&<a className="secondary" href={related}>Open</a>}</article>})}</section>)}{!shown.length&&<p>No notifications match this filter.</p>}</ModuleShell>
}
