"use client";

import {FormEvent, useEffect, useState} from "react";
import {CaretLeft, CaretRight, Clock, Plus, VideoCamera, X} from "@phosphor-icons/react";
import {ModuleShell} from "../components/ModuleShell";
import {Event, useAppState} from "../components/AppState";

const monday=()=>{const date=new Date(),day=(date.getDay()+6)%7;date.setDate(date.getDate()-day);date.setHours(0,0,0,0);return date};
const weekDays=()=>Array.from({length:7},(_,day)=>{const date=monday();date.setDate(date.getDate()+day);return date});
const days=weekDays().map(date=>date.toLocaleDateString(undefined,{weekday:"short",day:"numeric"}));
const blankEvent=():Event=>{const day=(new Date().getDay()+6)%7;return {id:crypto.randomUUID(),title:"",day,time:"09:00",top:76,height:58,location:"",timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,allDay:false,recurrence:null}};
const positionFor=(time:string)=>76+(Number(time.slice(0,2))-9)*51+Number(time.slice(3))*0.85;
const reminderValue=(value?:string|null)=>value?new Date(new Date(value).getTime()-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16):"";
type SyncStatus={calendars:{id:string;name:string}[];writes:{id:string;state:string}[];conflicts:{id:string;localSnapshot:{title:string};googleSnapshot:{summary?:string}}[]};
export default function CalendarPage(){const {events,saveEvent}=useAppState();const [draft,setDraft]=useState<Event|null>(null),[sync,setSync]=useState<SyncStatus>({calendars:[],writes:[],conflicts:[]});const [view,setView]=useState<"Day"|"Week"|"Month"|"Agenda">("Week");const today=(new Date().getDay()+6)%7,agenda=events.filter(event=>event.day===today),dates=weekDays(),period=dates[0].toLocaleDateString(undefined,{month:"short",day:"numeric"})+"–"+dates[6].toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"});useEffect(()=>{const id=new URLSearchParams(location.search).get("open"),event=events.find(item=>item.id===id);if(event)setDraft({...event})},[events]);useEffect(()=>{fetch("/api/v1/calendar-sync").then(response=>response.ok?response.json():null).then(value=>value&&setSync(value)).catch(()=>{})},[]);async function resolveConflict(id:string,choice:"local"|"google"|"duplicate"){const response=await fetch(`/api/v1/calendar-sync/conflicts/${id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({choice})});if(response.ok)location.reload()}function submit(e:FormEvent){e.preventDefault();if(!draft?.title.trim())return;const start=dates[draft.day];start.setHours(draft.allDay?0:Number(draft.time.slice(0,2)),draft.allDay?0:Number(draft.time.slice(3)),0,0);const duration=draft.allDay?86400000:draft.startAt&&draft.endAt?new Date(draft.endAt).getTime()-new Date(draft.startAt).getTime():3600000;saveEvent({...draft,title:draft.title.trim(),startAt:start.toISOString(),endAt:new Date(start.getTime()+duration).toISOString(),timezone:draft.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone,top:positionFor(draft.time),location:draft.location?.trim()});setDraft(null)}return <ModuleShell active="Calendar" title="Calendar" action={<button className="primary top-primary" onClick={()=>setDraft(blankEvent())}><Plus/>New event</button>}>
  <div className="calendar-toolbar"><div><button className="icon-button" aria-label="Previous period"><CaretLeft/></button><button className="icon-button" aria-label="Next period"><CaretRight/></button><button className="secondary">Today</button><h2>{view==="Month"?new Date().toLocaleDateString(undefined,{month:"long",year:"numeric"}):view==="Day"||view==="Agenda"?new Date().toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"}):period}</h2></div><div className="view-switch" role="group" aria-label="Calendar view">{(["Day","Week","Month","Agenda"] as const).map(item=><button className={view===item?"active":""} onClick={()=>setView(item)} key={item}>{item}</button>)}</div></div>
  {(sync.writes.length>0||sync.conflicts.length>0)&&<section className="auth-result" aria-label="Calendar sync status"><strong>{sync.conflicts.length?`${sync.conflicts.length} calendar conflict${sync.conflicts.length===1?"":"s"}`:`${sync.writes.length} change${sync.writes.length===1?"":"s"} waiting to sync`}</strong>{sync.conflicts.map(conflict=><div key={conflict.id}><small>Noema: {conflict.localSnapshot.title} · Google: {conflict.googleSnapshot.summary||"Deleted event"}</small><div className="inspector-actions"><button className="secondary" onClick={()=>void resolveConflict(conflict.id,"local")}>Keep Noema</button><button className="secondary" onClick={()=>void resolveConflict(conflict.id,"google")}>Keep Google</button><button className="secondary" onClick={()=>void resolveConflict(conflict.id,"duplicate")}>Keep both</button></div></div>)}</section>}
  <div className="calendar-layout">
    {view==="Week"&&<section className="week" aria-label="Week calendar"><div className="week-head"><span/><>{days.map(day=><strong className={day.includes("24")?"active":""} key={day}>{day}</strong>)}</></div><div className="week-body"><div className="times">{["08:00","10:00","12:00","14:00","16:00"].map(t=><time key={t}>{t}</time>)}</div><div className="week-grid">{days.map(day=><div key={day}/>) }{events.map(event=><button className={`calendar-event ${event.active?"active":""} ${draft?.id===event.id?"selected":""}`} style={{gridColumn:event.day+1,top:event.top,height:event.height}} key={event.id} onClick={()=>setDraft({...event})}><time>{event.time}</time><strong>{event.title}</strong></button>)}</div></div></section>}
    {view==="Day"&&<section className="day-view"><div className="times">{["08:00","10:00","12:00","14:00","16:00"].map(t=><time key={t}>{t}</time>)}</div><div>{agenda.map(event=><button style={{top:event.top,height:event.height}} key={event.id} onClick={()=>setDraft({...event})}><time>{event.time}</time><strong>{event.title}</strong><small>{event.location}</small></button>)}</div></section>}
    {view==="Month"&&<section className="month-view">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(day=><strong key={day}>{day}</strong>)}{Array.from({length:35},(_,index)=>{const date=index-1;return <button className={date===24?"active":""} key={index}><span>{date>0&&date<=31?date:""}</span>{date===24&&agenda.slice(0,2).map(event=><small key={event.id}>{event.time} {event.title}</small>)}</button>})}</section>}
    {view==="Agenda"&&<section className="mobile-agenda-view">{agenda.map(event=><button key={event.id} onClick={()=>setDraft({...event})}><time>{event.time}</time><span><strong>{event.title}</strong><small>{event.location||"No location"}</small></span><CaretRight/></button>)}</section>}
    {draft?<aside className="object-inspector calendar-inspector"><div className="object-inspector-head"><div><span>{events.some(event=>event.id===draft.id)?"Edit event":"New event"}</span><small>{period}</small></div><button className="icon-button" aria-label="Close event inspector" onClick={()=>setDraft(null)}><X/></button></div><form onSubmit={submit}><label>Event name<input autoFocus value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="Event name" required/></label><div className="field-row"><label>Day<select value={draft.day} onChange={e=>setDraft({...draft,day:Number(e.target.value)})}>{days.map((day,index)=><option value={index} key={day}>{day}</option>)}</select></label><label>Time<input type="time" value={draft.time} disabled={draft.allDay} onChange={e=>setDraft({...draft,time:e.target.value})}/></label></div><label><input type="checkbox" checked={!!draft.allDay} onChange={e=>setDraft({...draft,allDay:e.target.checked})}/> All day</label><label>Repeat<select value={draft.recurrence?.frequency||""} onChange={e=>setDraft({...draft,recurrence:e.target.value?{frequency:e.target.value}:null})}><option value="">Does not repeat</option><option value="daily">Daily</option><option value="weekly">Weekly</option></select></label>{!events.some(event=>event.id===draft.id)&&sync.calendars.length>0&&<label>Google calendar<select value={draft.googleCalendarId||""} onChange={e=>setDraft({...draft,googleCalendarId:e.target.value||undefined})}><option value="">Noema only</option>{sync.calendars.map(calendar=><option value={calendar.id} key={calendar.id}>{calendar.name}</option>)}</select></label>}<label>Time zone<input value={draft.timezone||""} onChange={e=>setDraft({...draft,timezone:e.target.value})} required/></label><label>Location or link<input value={draft.location||""} onChange={e=>setDraft({...draft,location:e.target.value})} placeholder="Optional"/></label><label>Reminder<input type="datetime-local" value={reminderValue(draft.reminderAt)} onChange={e=>setDraft({...draft,reminderAt:e.target.value?new Date(e.target.value).toISOString():null})}/></label><div className="inspector-actions"><button type="button" className="secondary" onClick={()=>setDraft(null)}>Cancel</button><button className="primary">Save event</button></div></form></aside>:<aside className="agenda"><h3>{new Date().toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"})}</h3>{agenda.map((event,index)=><button className="agenda-row" key={event.id} onClick={()=>setDraft({...event})}><span>{index?<VideoCamera/>:<Clock/>}</span><div><time>{event.allDay?"All day":event.time}</time><strong>{event.title}</strong>{event.location&&<small>{event.location}</small>}</div></button>)}<button className="secondary" onClick={()=>setDraft(blankEvent())}>Add today</button></aside>}
  </div>
  </ModuleShell>}
