"use client";

import {FormEvent, useState} from "react";
import {CaretLeft, CaretRight, Clock, Plus, VideoCamera, X} from "@phosphor-icons/react";
import {ModuleShell} from "../components/ModuleShell";
import {Event, useAppState} from "../components/AppState";

const days=["Mon 20","Tue 21","Wed 22","Thu 23","Fri 24","Sat 25","Sun 26"];
const blankEvent=():Event=>({id:crypto.randomUUID(),title:"",day:4,time:"09:00",top:76,height:58,location:""});
const positionFor=(time:string)=>76+(Number(time.slice(0,2))-9)*51+Number(time.slice(3))*0.85;
export default function CalendarPage(){const {events,saveEvent}=useAppState();const [draft,setDraft]=useState<Event|null>(null);const [view,setView]=useState<"Day"|"Week"|"Month"|"Agenda">("Week");const agenda=events.filter(event=>event.day===4);function submit(e:FormEvent){e.preventDefault();if(!draft?.title.trim())return;saveEvent({...draft,title:draft.title.trim(),top:positionFor(draft.time),location:draft.location?.trim()});setDraft(null)}return <ModuleShell active="Calendar" title="Calendar" action={<button className="primary top-primary" onClick={()=>setDraft(blankEvent())}><Plus/>New event</button>}>
  <div className="calendar-toolbar"><div><button className="icon-button" aria-label="Previous period"><CaretLeft/></button><button className="icon-button" aria-label="Next period"><CaretRight/></button><button className="secondary">Today</button><h2>{view==="Month"?"July 2026":view==="Day"||view==="Agenda"?"Friday, July 24":"July 20–26, 2026"}</h2></div><div className="view-switch" role="group" aria-label="Calendar view">{(["Day","Week","Month","Agenda"] as const).map(item=><button className={view===item?"active":""} onClick={()=>setView(item)} key={item}>{item}</button>)}</div></div>
  <div className="calendar-layout">
    {view==="Week"&&<section className="week" aria-label="Week calendar"><div className="week-head"><span/><>{days.map(day=><strong className={day.includes("24")?"active":""} key={day}>{day}</strong>)}</></div><div className="week-body"><div className="times">{["08:00","10:00","12:00","14:00","16:00"].map(t=><time key={t}>{t}</time>)}</div><div className="week-grid">{days.map(day=><div key={day}/>) }{events.map(event=><button className={`calendar-event ${event.active?"active":""} ${draft?.id===event.id?"selected":""}`} style={{gridColumn:event.day+1,top:event.top,height:event.height}} key={event.id} onClick={()=>setDraft({...event})}><time>{event.time}</time><strong>{event.title}</strong></button>)}</div></div></section>}
    {view==="Day"&&<section className="day-view"><div className="times">{["08:00","10:00","12:00","14:00","16:00"].map(t=><time key={t}>{t}</time>)}</div><div>{agenda.map(event=><button style={{top:event.top,height:event.height}} key={event.id} onClick={()=>setDraft({...event})}><time>{event.time}</time><strong>{event.title}</strong><small>{event.location}</small></button>)}</div></section>}
    {view==="Month"&&<section className="month-view">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(day=><strong key={day}>{day}</strong>)}{Array.from({length:35},(_,index)=>{const date=index-1;return <button className={date===24?"active":""} key={index}><span>{date>0&&date<=31?date:""}</span>{date===24&&agenda.slice(0,2).map(event=><small key={event.id}>{event.time} {event.title}</small>)}</button>})}</section>}
    {view==="Agenda"&&<section className="mobile-agenda-view">{agenda.map(event=><button key={event.id} onClick={()=>setDraft({...event})}><time>{event.time}</time><span><strong>{event.title}</strong><small>{event.location||"No location"}</small></span><CaretRight/></button>)}</section>}
    {draft?<aside className="object-inspector calendar-inspector"><div className="object-inspector-head"><div><span>{events.some(event=>event.id===draft.id)?"Edit event":"New event"}</span><small>Week of July 20–26</small></div><button className="icon-button" aria-label="Close event inspector" onClick={()=>setDraft(null)}><X/></button></div><form onSubmit={submit}><label>Event name<input autoFocus value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="Event name" required/></label><div className="field-row"><label>Day<select value={draft.day} onChange={e=>setDraft({...draft,day:Number(e.target.value)})}>{days.map((day,index)=><option value={index} key={day}>{day}</option>)}</select></label><label>Time<input type="time" value={draft.time} onChange={e=>setDraft({...draft,time:e.target.value})}/></label></div><label>Location or link<input value={draft.location||""} onChange={e=>setDraft({...draft,location:e.target.value})} placeholder="Optional"/></label><div className="inspector-actions"><button type="button" className="secondary" onClick={()=>setDraft(null)}>Cancel</button><button className="primary">Save event</button></div></form></aside>:<aside className="agenda"><h3>Friday, July 24</h3>{agenda.map((event,index)=><button className="agenda-row" key={event.id} onClick={()=>setDraft({...event})}><span>{index?<VideoCamera/>:<Clock/>}</span><div><time>{event.time}</time><strong>{event.title}</strong>{event.location&&<small>{event.location}</small>}</div></button>)}<button className="secondary" onClick={()=>setDraft(blankEvent())}>Add to Friday</button></aside>}
  </div>
  </ModuleShell>}
