"use client";

import {ChangeEvent, useEffect, useState} from "react";
import {ArrowLeft, BookOpen, Clock, DownloadSimple, FileText, Folder, MagnifyingGlass, Plus, Sparkle, Star, Tag, Trash, UploadSimple, X} from "@phosphor-icons/react";
import {ModuleShell} from "../components/ModuleShell";
import {Note, useAppState} from "../components/AppState";
import {TutorPanel} from "../components/TutorPanel";

const blankNote=():Note=>({id:crypto.randomUUID(),title:"Untitled note",excerpt:"",content:"# Untitled note\n\n",tags:[],time:"Now",ai:false,source:"Created in LifeOS"});
const renderMarkdown=(text:string)=>text.split("\n").map((line,index)=>line.startsWith("# ")?<h1 key={index}>{line.slice(2)}</h1>:line.startsWith("## ")?<h2 key={index}>{line.slice(3)}</h2>:line.startsWith("- ")?<li key={index}>{line.slice(2)}</li>:line?<p key={index}>{line.replaceAll("**","")}</p>:<br key={index}/>);

export default function VaultPage(){
  const {notes,saveNote,trashNote}=useAppState();
  const [query,setQuery]=useState("");
  const [view,setView]=useState("All notes");
  const [draft,setDraft]=useState<Note|null>(null);
  const [mode,setMode]=useState<"write"|"split"|"read">("write");
  const [tutorOpen,setTutorOpen]=useState(false);
  useEffect(()=>{const id=new URLSearchParams(location.search).get("open"),note=notes.find(item=>item.id===id);if(note)setDraft({...note,content:note.content||`# ${note.title}\n\n${note.excerpt}`})},[notes]);
  const filtered=notes.filter(note=>view==="Trash"?note.trashed:!note.trashed).filter(note=>view==="Favorites"?note.favorite:view==="Courses"?note.tags.some(tag=>["course","networking","database","study","operating-systems"].includes(tag)):view==="Projects"?note.tags.some(tag=>["revou","partnership","project"].includes(tag)):true).filter(note=>`${note.title} ${note.excerpt} ${note.tags}`.toLowerCase().includes(query.toLowerCase()));
  function update(content:string){if(!draft)return;const title=content.match(/^# (.+)$/m)?.[1]||draft.title;setDraft({...draft,title,content,excerpt:content.replace(/[#*_>-]/g,"").trim().slice(0,140)})}
  function save(){if(draft){saveNote({...draft,time:"Now"});setDraft(null)}}
  function exportNote(){if(!draft)return;const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([draft.content],{type:"text/markdown"}));link.download=`${draft.title.toLowerCase().replace(/[^a-z0-9]+/g,"-")}.md`;link.click();URL.revokeObjectURL(link.href)}
  function importNote(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;file.text().then(content=>setDraft({...blankNote(),title:file.name.replace(/\.md$/i,""),content,source:`Imported Markdown · ${file.name}`}))}
  if(draft)return <ModuleShell active="Vault" title="Note editor" action={<button className="primary top-primary" onClick={save}>Save note</button>}><section className="note-workspace"><header className="note-toolbar"><button className="icon-button" aria-label="Back to notes" onClick={()=>setDraft(null)}><ArrowLeft/></button><div className="mode-switch" role="group" aria-label="Editor view">{(["write","split","read"] as const).map(item=><button className={mode===item?"active":""} onClick={()=>setMode(item)} key={item}>{item}</button>)}</div><button className="secondary" onClick={()=>setTutorOpen(true)}><Sparkle/>Ask tutor</button><button className="secondary" onClick={exportNote}><DownloadSimple/>Export</button><button className="icon-button danger" aria-label="Move note to trash" onClick={()=>{trashNote(draft.id);setDraft(null)}}><Trash/></button></header><div className={`note-editor ${mode}`}><textarea aria-label="Markdown note" value={draft.content} onChange={e=>update(e.target.value)} spellCheck/>{mode!=="write"&&<article className="markdown-preview">{renderMarkdown(draft.content)}</article>}</div><aside className="note-inspector"><div className="object-inspector-head"><div><span>Note details</span><small>Portable Markdown with its source intact.</small></div><X/></div><label>Title<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Tags<input value={draft.tags.join(", ")} onChange={e=>setDraft({...draft,tags:e.target.value.split(",").map(tag=>tag.trim()).filter(Boolean)})}/></label><div><small>Source</small><strong>{draft.source}</strong></div><div><small>Relationships</small><strong>{draft.tags.length||0} related topics</strong></div>{draft.ai&&<div className="ai-provenance"><Sparkle/><span><strong>AI-assisted</strong><small>Generated content remains identified.</small></span></div>}</aside></section>{tutorOpen&&<TutorPanel kind="note" context={{id:draft.id,title:draft.title,content:draft.content}} onApply={value=>update(`${draft.content.trim()}\n\n${value.trim()}\n`)} onClose={()=>setTutorOpen(false)}/>}</ModuleShell>;
  return <ModuleShell active="Vault" title="Vault" action={<button className="primary top-primary" onClick={()=>setDraft(blankNote())}><Plus/>New note</button>}><div className="module-header vault-header"><div><h2>Your knowledge, connected</h2><p>Notes stay portable, searchable, and linked to their original sources.</p></div><label className="vault-search"><MagnifyingGlass/><span className="sr-only">Search notes</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search notes…"/></label></div><div className="vault-layout"><nav className="subnav" aria-label="Vault views">{[["All notes",FileText],["Recent",Clock],["Favorites",Star],["Courses",BookOpen],["Projects",Folder],["Tags",Tag],["Trash",Trash]].map(([label,Icon])=><button className={view===label?"active":""} onClick={()=>setView(label as string)} key={label as string}><Icon/><span>{label as string}</span></button>)}</nav><section className="notes"><div className="list-title"><h3>{filtered.length} notes</h3><label className="secondary import-note"><UploadSimple/>Import .md<input type="file" accept=".md,text/markdown" onChange={importNote}/></label></div><div className="note-list">{filtered.map(note=><button className="note-row" key={note.id} onClick={()=>setDraft({...note,content:note.content||`# ${note.title}\n\n${note.excerpt}`})}><FileText/><div><strong>{note.title}</strong><p>{note.excerpt}</p><span>{note.tags.map(tag=><small key={tag}>#{tag}</small>)}</span></div><time>{note.time}</time>{note.ai&&<em><Sparkle/>Generated</em>}</button>)}{!filtered.length&&<div className="empty-state"><MagnifyingGlass/><h3>No matching notes</h3><p>Try a broader title, tag, or topic.</p></div>}</div></section><aside className="vault-context"><Sparkle/><h3>Connections</h3><p>LifeOS found three notes related to your current Computer Networks course.</p><button className="secondary">Review suggestions</button></aside></div></ModuleShell>}
