"use client";
import {useEffect, useState} from "react";
import {ArrowLeft, ArrowRight, CalendarBlank, ChatCircle, CheckSquare, Circle, FileText, Link as LinkIcon, Plus, Users} from "@phosphor-icons/react";
import {ModuleShell} from "../components/ModuleShell";
import {useAppState} from "../components/AppState";

const sampleProjects=[
  {name:"RevoU Partnership",status:"Active",summary:"Finalize the partnership proposal and prepare for stakeholder review.",tasks:"6 of 9",next:"Meeting with Dian · Today"},
  {name:"LifeOS",status:"Active",summary:"Build the personal workspace foundation and connect core daily workflows.",tasks:"14 of 22",next:"Frontend review · Tomorrow"},
  {name:"Operating Systems Exam",status:"Planned",summary:"Complete the four-week revision plan and practice assessments.",tasks:"3 of 18",next:"Study block · Friday"},
];

export default function ProjectsPage(){const {projects:stored}=useAppState();const projects=[...stored.map(project=>({...project,tasks:"0",next:"No next event"})),...sampleProjects.filter(sample=>!stored.some(project=>project.name===sample.name))];const [selected,setSelected]=useState<(typeof projects)[number]|null>(null);const [tab,setTab]=useState("Overview");useEffect(()=>{const id=new URLSearchParams(location.search).get("open"),project=projects.find(item=>"id" in item&&item.id===id);if(project)setSelected(project)},[stored]);if(selected)return <ModuleShell active="Projects" title={selected.name} action={<button className="secondary" onClick={()=>setSelected(null)}><ArrowLeft/>Projects</button>}><div className="workspace-head"><div><h2>{selected.name}</h2><p>{selected.summary}</p></div><span className="status-live"><Circle weight="fill"/>{selected.status}</span></div><nav className="workspace-tabs">{["Overview","Tasks","Calendar","Notes","Activity"].map(item=><button className={tab===item?"active":""} onClick={()=>setTab(item)} key={item}>{item}</button>)}</nav><div className="project-workspace"><section><div className="list-title"><h3>{tab}</h3><span>Updated today</span></div>{tab==="Overview"&&<><article className="workspace-summary"><strong>Next outcome</strong><p>{selected.summary}</p><span><CheckSquare/>{selected.tasks} tasks complete</span></article><h3>Recent work</h3></>}{tab==="Tasks"&&["Review partnership proposal","Prepare questions for Dian","Send revised scope"].map((item,index)=><article className="workspace-row" key={item}><CheckSquare/><span><strong>{item}</strong><small>{index?"Upcoming":"Due today"}</small></span><button>Open</button></article>)}{tab==="Calendar"&&["Meeting with Dian · Today, 13:00","Stakeholder review · Friday, 10:00"].map(item=><article className="workspace-row" key={item}><CalendarBlank/><span><strong>{item}</strong><small>Linked event</small></span></article>)}{tab==="Notes"&&["Proposal draft","Meeting preparation","Partnership research"].map(item=><article className="workspace-row" key={item}><FileText/><span><strong>{item}</strong><small>Vault note</small></span></article>)}{tab==="Activity"&&["Proposal moved to review","Dian meeting rescheduled","Scope note updated"].map(item=><article className="workspace-row" key={item}><ChatCircle/><span><strong>{item}</strong><small>Today</small></span></article>)}</section><aside className="workspace-context"><h3>Project context</h3><div><Users/><span><strong>2 people</strong><small>Tim, Dian</small></span></div><div><LinkIcon/><span><strong>8 relationships</strong><small>Tasks, events, and notes</small></span></div><button className="secondary"><Plus/>Link item</button></aside></div></ModuleShell>;return <ModuleShell active="Projects" title="Projects" action={<button className="primary top-primary"><Plus/>New project</button>}>
  <div className="module-header"><div><h2>Move connected work forward</h2><p>Two active projects have work scheduled this week.</p></div></div>
  <div className="project-layout"><section className="project-list"><div className="list-title"><h3>Active and planned</h3><span>{projects.length} projects</span></div>{projects.map((project,i)=><button className="project-row" key={project.name} onClick={()=>setSelected(project)}><span className="project-glyph">{project.name.slice(0,2)}</span><div><span className="project-title"><strong>{project.name}</strong><small className={i<2?"active":""}><Circle weight="fill"/>{project.status}</small></span><p>{project.summary}</p><span className="project-meta"><em><CheckSquare/>{project.tasks} tasks</em><em><CalendarBlank/>{project.next}</em></span></div><ArrowRight/></button>)}</section><aside className="project-attention"><h3>Needs attention</h3><article><FileText/><div><strong>Proposal draft</strong><span>Ready for your review</span></div><button onClick={()=>setSelected(projects[0])}>Open</button></article><article><Users/><div><strong>Dian meeting</strong><span>Preparation is incomplete</span></div><button onClick={()=>setSelected(projects[0])}>Prepare</button></article></aside></div>
  </ModuleShell>}
