"use client";

import {FormEvent,useEffect,useState} from "react";
import {CheckCircle,Clock,Plus,ShareNetwork,ShieldCheck,Trash,WarningCircle} from "@phosphor-icons/react";
import {ModuleShell} from "../components/ModuleShell";

type Workspace={id:string;name:string;role:"viewer"|"editor"|"admin"|"owner";version:number};
type Member={userId:string;email:string;role:Workspace["role"];joinedAt:string};
type Invitation={id:string;email:string;role:string;expiresAt:string;acceptedAt:string|null;revokedAt:string|null};
type Detail={workspace:Workspace;members:Member[];invitations:Invitation[]};
type Presence={userId:string;email:string;location:string;objectType:string|null;objectId:string|null;lastSeenAt:string};
type Conflict={id:string;object_type:string;object_id:string;actor:string;created_at:string;base_version:number};
export default function CollaborationPage(){
  const [workspaces,setWorkspaces]=useState<Workspace[]>([]),[active,setActive]=useState(""),[detail,setDetail]=useState<Detail|null>(null),[presence,setPresence]=useState<Presence[]>([]),[conflicts,setConflicts]=useState<Conflict[]>([]),[name,setName]=useState(""),[inviteEmail,setInviteEmail]=useState(""),[inviteRole,setInviteRole]=useState("viewer"),[inviteLink,setInviteLink]=useState(""),[error,setError]=useState(""),[status,setStatus]=useState("");
  async function json(url:string,init?:RequestInit){const response=await fetch(url,init),value=await response.json();if(!response.ok)throw new Error(value.error?.message||"Collaboration request failed");return value}
  async function load(){try{const value=await json("/api/v1/workspaces");setWorkspaces(value.workspaces);setActive(current=>current||value.workspaces[0]?.id||"")}catch(reason){setError(reason instanceof Error?reason.message:"Workspaces are unavailable")}}
  async function loadDetail(id:string){if(!id)return;try{setDetail(await json(`/api/v1/workspaces/${id}`));if(["editor","admin","owner"].includes(workspaces.find(item=>item.id===id)?.role||""))setConflicts((await json(`/api/v1/workspaces/${id}/conflicts`)).conflicts)}catch(reason){setError(reason instanceof Error?reason.message:"Workspace is unavailable")}}
  useEffect(()=>{void load()},[]);useEffect(()=>{if(!active)return;void loadDetail(active);const heartbeat=()=>json(`/api/v1/workspaces/${active}/presence`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({location:"collaboration"})}).then(value=>setPresence(value.presence)).catch(()=>{});void heartbeat();const timer=setInterval(heartbeat,30000);return()=>clearInterval(timer)},[active]);
  async function create(event:FormEvent){event.preventDefault();setError("");try{const workspace=await json("/api/v1/workspaces",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name})});setName("");await load();setActive(workspace.id)}catch(reason){setError(reason instanceof Error?reason.message:"Workspace could not be created")}}
  async function invite(event:FormEvent){event.preventDefault();setError("");try{const value=await json(`/api/v1/workspaces/${active}/invitations`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:inviteEmail,role:inviteRole})}),link=`${location.origin}/join?token=${encodeURIComponent(value.token)}&email=${encodeURIComponent(value.email)}`;setInviteLink(link);setInviteEmail("");setStatus("Invitation created. Copy the link now; the token is shown once.");await loadDetail(active)}catch(reason){setError(reason instanceof Error?reason.message:"Invitation failed")}}
  async function member(member:Member,input:object){setError("");try{await json(`/api/v1/workspaces/${active}/members/${member.userId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)});setStatus(`${member.email} updated`);await Promise.all([load(),loadDetail(active)])}catch(reason){setError(reason instanceof Error?reason.message:"Member update failed")}}
  async function revoke(invitation:Invitation){try{await json(`/api/v1/workspaces/${active}/invitations/${invitation.id}`,{method:"DELETE"});await loadDetail(active)}catch(reason){setError(reason instanceof Error?reason.message:"Invitation could not be revoked")}}
  const access=workspaces.find(item=>item.id===active)?.role||"viewer",canManage=["admin","owner"].includes(access);
  return <ModuleShell active="Collaboration" title="Collaboration"><div className="module-header"><div><h2>Shared workspaces</h2><p>Invite collaborators with explicit roles, see current presence, attribute discussions, and recover edit conflicts.</p></div><form className="workspace-create" onSubmit={create}><input aria-label="New workspace name" value={name} onChange={event=>setName(event.target.value)} placeholder="Workspace name" required maxLength={100}/><button className="primary"><Plus/>Create</button></form></div>
    <section className="permission-note"><ShieldCheck/><span><strong>Workspace boundaries are deny-by-default</strong><small>Invites expire and can be used once. Role changes, revocation, comments, conflicts, and actor identity remain auditable.</small></span></section>
    {error&&<p className="auth-error" role="alert"><WarningCircle/>{error}</p>}{status&&<p className="success-note" role="status"><CheckCircle/>{status}</p>}
    <div className="workspace-tabs" role="tablist" aria-label="Workspaces">{workspaces.map(item=><button role="tab" aria-selected={active===item.id} key={item.id} onClick={()=>setActive(item.id)}><ShareNetwork/><span>{item.name}<small>{item.role}</small></span></button>)}</div>
    {detail&&<div className="collaboration-grid"><section><div className="list-title"><h3>Members</h3><span>{detail.members.length}</span></div><div className="member-list">{detail.members.map(item=><article key={item.userId}><span><strong>{item.email}</strong><small>Joined {new Date(item.joinedAt).toLocaleDateString()}</small></span>{canManage&&item.role!=="owner"?<><select aria-label={`${item.email} role`} value={item.role} onChange={event=>void member(item,{role:event.target.value})}><option>viewer</option><option>editor</option>{access==="owner"&&<option>admin</option>}</select><button className="danger-link" aria-label={`Revoke ${item.email}`} onClick={()=>void member(item,{revoke:true})}><Trash/></button></>:<em>{item.role}</em>}</article>)}</div></section>
      <section><div className="list-title"><h3>Live presence</h3><span>{presence.length} active</span></div>{presence.length?<div className="presence-list">{presence.map(item=><article key={item.userId}><i/><span><strong>{item.email}</strong><small>{item.location}{item.objectType?` · ${item.objectType}`:""} · {new Date(item.lastSeenAt).toLocaleTimeString()}</small></span></article>)}</div>:<p>No active collaborators.</p>}</section>
      {canManage&&<section><div className="list-title"><h3>Invite member</h3><span>Expires in 7 days</span></div><form className="invite-form" onSubmit={invite}><label>Email <input type="email" value={inviteEmail} onChange={event=>setInviteEmail(event.target.value)} required/></label><label>Role <select value={inviteRole} onChange={event=>setInviteRole(event.target.value)}><option>viewer</option><option>editor</option><option>admin</option></select></label><button className="primary">Create invitation</button></form>{inviteLink&&<label className="invite-link">One-time invitation link <textarea readOnly value={inviteLink} onFocus={event=>event.currentTarget.select()}/></label>}<div className="invite-list">{detail.invitations.map(item=><article key={item.id}><Clock/><span><strong>{item.email}</strong><small>{item.role} · expires {new Date(item.expiresAt).toLocaleString()}</small></span>{!item.acceptedAt&&!item.revokedAt&&<button className="danger-link" onClick={()=>void revoke(item)}>Revoke</button>}</article>)}</div></section>}
      <section><div className="list-title"><h3>Recoverable conflicts</h3><span>{conflicts.length} open</span></div>{conflicts.length?<div className="conflict-list">{conflicts.map(item=><article key={item.id}><WarningCircle/><span><strong>{item.object_type} · {item.object_id}</strong><small>{item.actor} preserved base version {item.base_version} · {new Date(item.created_at).toLocaleString()}</small></span></article>)}</div>:<p>No unresolved edit conflicts.</p>}</section></div>}
  </ModuleShell>
}
