import {randomUUID} from "node:crypto";
import {getDatabase} from "./db.mjs";
const now=()=>new Date().toISOString(),parse=row=>({...row,geometry:JSON.parse(row.geometry_json),geometry_json:undefined});
function geometry(kind,value){if(!value||typeof value!=="object")throw new Error("Annotation geometry is required");if(kind==="ink"){if(!Array.isArray(value.points)||!value.points.length||value.points.length>10000)throw new Error("Ink requires points");return {points:value.points.map(point=>{if(!Array.isArray(point)||point.length!==2||point.some(n=>typeof n!=="number"||n<0||n>1))throw new Error("Ink coordinates must be normalized");return point})}}const result={x:Number(value.x),y:Number(value.y),width:Number(value.width),height:Number(value.height)};if(Object.values(result).some(n=>!Number.isFinite(n)||n<0||n>1)||result.x+result.width>1||result.y+result.height>1)throw new Error("Annotation coordinates must be normalized");return result}
function target(type,id,db){if(type==null&&id==null)return;if(![["note","notes"],["course","courses"]].some(([name,table])=>name===type&&db.prepare(`SELECT 1 FROM ${table} WHERE id=?`).get(id)))throw Object.assign(new Error("Linked note or course not found"),{status:404})}
export const listAnnotations=(assetId,db=getDatabase())=>db.prepare("SELECT * FROM pdf_annotations WHERE asset_id=? ORDER BY page,created_at").all(assetId).map(parse);
export function saveAnnotation(assetId,input,db=getDatabase(),actor=null){const asset=db.prepare("SELECT mime FROM assets WHERE id=?").get(assetId);if(!asset||asset.mime!=="application/pdf")throw Object.assign(new Error("PDF asset not found"),{status:404});const id=input.id||randomUUID(),before=db.prepare("SELECT * FROM pdf_annotations WHERE id=? AND asset_id=?").get(id,assetId);if(before&&input.version!==before.version)throw Object.assign(new Error("Annotation changed in another session"),{status:409,code:"VERSION_CONFLICT"});const page=Number(input.page),kind=String(input.kind||"");if(!Number.isInteger(page)||page<1)throw new Error("Page must be a positive integer");if(!["highlight","ink","text"].includes(kind))throw new Error("Invalid annotation kind");target(input.linkType,input.linkId,db);const time=now(),shape=geometry(kind,input.geometry);db.prepare("INSERT INTO pdf_annotations(id,asset_id,page,kind,geometry_json,content,color,comment,link_type,link_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET page=excluded.page,kind=excluded.kind,geometry_json=excluded.geometry_json,content=excluded.content,color=excluded.color,comment=excluded.comment,link_type=excluded.link_type,link_id=excluded.link_id,updated_at=excluded.updated_at,version=pdf_annotations.version+1").run(id,assetId,page,kind,JSON.stringify(shape),String(input.content||"").slice(0,10000),String(input.color||"#f5d90a").slice(0,20),String(input.comment||"").slice(0,10000),input.linkType||null,input.linkId||null,before?.created_at||time,time);db.prepare("INSERT INTO audit_events(id,actor_id,action,object_type,object_id,summary,created_at) VALUES(?,?,?,?,?,?,?)").run(randomUUID(),actor,before?"update":"create","pdf_annotation",id,`${kind} on page ${page}`,time);return parse(db.prepare("SELECT * FROM pdf_annotations WHERE id=?").get(id))}
export function deleteAnnotation(id,assetId,db=getDatabase(),actor=null){const row=db.prepare("SELECT * FROM pdf_annotations WHERE id=? AND asset_id=?").get(id,assetId);if(!row)throw Object.assign(new Error("Annotation not found"),{status:404});db.prepare("DELETE FROM pdf_annotations WHERE id=?").run(id);db.prepare("INSERT INTO audit_events(id,actor_id,action,object_type,object_id,summary,created_at) VALUES(?,?,?,?,?,?,?)").run(randomUUID(),actor,"delete","pdf_annotation",id,`Deleted ${row.kind} on page ${row.page}`,now());return {ok:true}}
export function exportAnnotations(assetId,db=getDatabase()){const asset=db.prepare("SELECT id,name,sha256 FROM assets WHERE id=? AND mime='application/pdf'").get(assetId);if(!asset)throw Object.assign(new Error("PDF asset not found"),{status:404});return {format:"lifeos-pdf-annotations",version:1,asset,annotations:listAnnotations(assetId,db)}}
