import {createHash,randomUUID} from "node:crypto";
import {getDatabase} from "./db.mjs";

const now=()=>new Date().toISOString();
const canonical=value=>value&&typeof value==="object"?(Array.isArray(value)?`[${value.map(canonical).join(",")}]`:`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${canonical(value[key])}`).join(",")}}`):JSON.stringify(value);
export const actionHash=(type,action)=>createHash("sha256").update(`${type}\n${canonical(action)}`).digest("hex");
const view=row=>({...row,details:JSON.parse(row.details_json),details_json:undefined,userId:row.user_id,sessionId:row.session_id,mfaVerifiedAt:row.mfa_verified_at,actionType:row.action_type,actionHash:row.action_hash,expiresAt:row.expires_at,approvedAt:row.approved_at,consumedAt:row.consumed_at,createdAt:row.created_at});
function details(input){const commands=Array.isArray(input.commands)?input.commands.map(String):[],files=Array.isArray(input.files)?input.files.map(String):[],diff=String(input.diff||"");if(commands.length>50||files.length>500||diff.length>500_000)throw new Error("Approval details exceed limits");if(commands.some(command=>!command||command.length>2000)||files.some(file=>!file||file.length>1000))throw new Error("Invalid approval details");return {summary:String(input.summary||"").slice(0,500),commands,files,diff}}
export function createApproval(user,input,db=getDatabase(),ttlSeconds=600){if(!user.mfa_verified_at||Date.now()-Date.parse(user.mfa_verified_at)>10*60_000)throw Object.assign(new Error("Recent MFA verification is required"),{status:403,code:"MFA_REQUIRED"});const actionType=String(input.actionType||"").trim(),risk=String(input.risk||"").toLowerCase();if(!actionType||actionType.length>100)throw new Error("Action type is required");if(!["low","medium","high","critical"].includes(risk))throw new Error("Risk must be low, medium, high, or critical");if(!input.action||typeof input.action!=="object"||Array.isArray(input.action))throw new Error("Action must be an object");const id=randomUUID(),created=now(),expires=new Date(Date.now()+Math.min(Math.max(ttlSeconds,30),600)*1000).toISOString(),hash=actionHash(actionType,input.action);db.prepare("INSERT INTO approvals(id,user_id,session_id,mfa_verified_at,action_type,action_hash,risk,details_json,expires_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").run(id,user.id,user.session_id,user.mfa_verified_at,actionType,hash,risk,JSON.stringify(details(input)),expires,created);return view(db.prepare("SELECT * FROM approvals WHERE id=?").get(id))}
export function listApprovals(userId,db=getDatabase()){return db.prepare("SELECT * FROM approvals WHERE user_id=? ORDER BY created_at DESC LIMIT 100").all(userId).map(view)}
export function approve(id,user,db=getDatabase()){const time=now(),result=db.prepare("UPDATE approvals SET status='approved',approved_at=? WHERE id=? AND user_id=? AND session_id=? AND status='pending' AND expires_at>?").run(time,id,user.id,user.session_id,time);if(!result.changes)throw Object.assign(new Error("Approval is unavailable, expired, or belongs to another session"),{status:409,code:"APPROVAL_UNAVAILABLE"});return view(db.prepare("SELECT * FROM approvals WHERE id=?").get(id))}
export function consumeApproval(id,user,actionType,action,db=getDatabase()){const time=now(),hash=actionHash(actionType,action);db.exec("BEGIN IMMEDIATE");try{const record=db.prepare("SELECT * FROM approvals WHERE id=? AND user_id=? AND session_id=?").get(id,user.id,user.session_id);if(!record||record.status!=="approved"||record.expires_at<=time||record.action_type!==actionType||record.action_hash!==hash)throw Object.assign(new Error("Approval does not match this exact action or is no longer valid"),{status:403,code:"APPROVAL_REQUIRED"});const changed=db.prepare("UPDATE approvals SET status='consumed',consumed_at=? WHERE id=? AND status='approved'").run(time,id).changes;if(!changed)throw Object.assign(new Error("Approval was already consumed"),{status:409,code:"APPROVAL_CONSUMED"});db.exec("COMMIT");return true}catch(error){db.exec("ROLLBACK");throw error}}
