import {randomUUID} from "node:crypto";
import {getDatabase} from "./db.mjs";

export const canvasObjectTypes=["text","note","task","event","project","asset","ink"];
const finite=(value,name,min,max)=>{const number=Number(value);if(!Number.isFinite(number)||number<min||number>max)throw new Error(`${name} is outside its allowed range`);return number};
const text=(value,name,max)=>{if(typeof value!=="string"||!value.trim())throw new Error(`${name} is required`);if(value.length>max)throw new Error(`${name} is too long`);return value.trim()};
const viewport=value=>({x:finite(value?.x,"viewport x",-1e6,1e6),y:finite(value?.y,"viewport y",-1e6,1e6),zoom:finite(value?.zoom,"viewport zoom",.1,8)});
const object=value=>{if(!canvasObjectTypes.includes(value?.type))throw new Error("Unknown canvas object type");const result={id:text(value.id,"object id",100),type:value.type,x:finite(value.x,"object x",-1e6,1e6),y:finite(value.y,"object y",-1e6,1e6),width:finite(value.width,"object width",80,4000),height:finite(value.height,"object height",48,4000),title:text(value.title||value.type,"object title",300)};if(value.refId!=null)result.refId=text(value.refId,"object reference",200);if(value.payload!=null){const encoded=JSON.stringify(value.payload);if(encoded.length>20000)throw new Error("Object payload is too large");result.payload=JSON.parse(encoded)}return result};
const objects=value=>{if(!Array.isArray(value))throw new Error("objects must be an array");if(value.length>500)throw new Error("Canvas supports at most 500 objects");const result=value.map(object);if(new Set(result.map(item=>item.id)).size!==result.length)throw new Error("Object IDs must be unique");return result};
const view=row=>({...row,viewport:JSON.parse(row.viewport_json),objects:JSON.parse(row.objects_json),viewport_json:undefined,objects_json:undefined});

export function saveCanvas(userId,workspaceId,input,db=getDatabase()){const id=input.id||randomUUID(),before=db.prepare("SELECT * FROM canvases WHERE id=? AND workspace_id=?").get(id,workspaceId);if(input.id&&!before)throw Object.assign(new Error("Canvas not found"),{status:404});if(before&&Number(input.version)!==before.version)throw Object.assign(new Error(`Expected version ${before.version}`),{status:409,code:"VERSION_CONFLICT"});const time=new Date().toISOString(),state=objects(input.objects||[]);db.prepare(`INSERT INTO canvases(id,workspace_id,user_id,name,viewport_json,objects_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,viewport_json=excluded.viewport_json,objects_json=excluded.objects_json,updated_at=excluded.updated_at,version=canvases.version+1`).run(id,workspaceId,userId,text(input.name,"name",200),JSON.stringify(viewport(input.viewport||{x:0,y:0,zoom:1})),JSON.stringify(state),before?.created_at||time,time);return view(db.prepare("SELECT * FROM canvases WHERE id=? AND workspace_id=?").get(id,workspaceId))}
export const listCanvases=(workspaceId,db=getDatabase())=>db.prepare("SELECT * FROM canvases WHERE workspace_id=? ORDER BY updated_at DESC,id").all(workspaceId).map(view);
export function getCanvas(workspaceId,id,db=getDatabase()){const row=db.prepare("SELECT * FROM canvases WHERE id=? AND workspace_id=?").get(id,workspaceId);if(!row)throw Object.assign(new Error("Canvas not found"),{status:404});return view(row)}
