import {randomUUID} from "node:crypto";
import {existsSync,lstatSync,mkdirSync,readFileSync,readdirSync,realpathSync,renameSync,statSync,writeFileSync} from "node:fs";
import {basename,dirname,extname,join,resolve,sep} from "node:path";

const extensions=new Set([".py",".js",".mjs",".cjs",".ts",".c",".h",".cpp",".cc",".cxx",".hpp",".hh",".java",".go",".rs",".sh",".bash",".rb",".php",".lua",".sql",".html",".css",".json",".yaml",".yml",".toml",".md",".txt"]);
const languages={".py":"python",".js":"javascript",".mjs":"javascript",".cjs":"javascript",".c":"c",".h":"c",".cpp":"cpp",".cc":"cpp",".cxx":"cpp",".hpp":"cpp",".hh":"cpp",".java":"java",".go":"go",".rs":"rust",".sh":"bash",".bash":"bash"};
const ignored=new Set([".git",".stfolder",".stversions","node_modules","target","build","dist","__pycache__",".venv","venv",".idea",".vscode","bin","obj",".cache"]),limit=1024*1024;
const language=path=>languages[extname(path).toLowerCase()]||null;
function root(path){const value=realpathSync(path);if(!statSync(value).isDirectory())throw new Error("Saved code directory is not a directory");return value}
function target(rootPath,relative){const clean=String(relative||"").replaceAll("\\","/").replace(/^\/+/,""),path=resolve(rootPath,clean);if(!clean||path===rootPath||!path.startsWith(rootPath+sep))throw new Error("Path is outside the saved code directory");if(!extensions.has(extname(clean).toLowerCase()))throw new Error("File extension is not allowed");return {clean,path}}
function safeExisting(rootPath,path){if(lstatSync(path).isSymbolicLink()||realpathSync(path)!==path||!path.startsWith(rootPath+sep))throw new Error("Saved code symlink is not allowed")}

export function listCodeFiles(rootPath){const base=root(rootPath),files=[];function walk(path,relative,depth){if(depth>8||files.length>=2000)return;for(const entry of readdirSync(path,{withFileTypes:true})){if(entry.isSymbolicLink())continue;const next=join(path,entry.name),rel=relative?`${relative}/${entry.name}`:entry.name;if(entry.isDirectory()){if(!ignored.has(entry.name)&&!entry.name.startsWith("."))walk(next,rel,depth+1)}else if(entry.isFile()&&extensions.has(extname(entry.name).toLowerCase()))files.push({path:rel,name:entry.name,language:language(rel)})}}walk(base,"",0);files.sort((a,b)=>a.path.localeCompare(b.path));return {files}}
export function readCodeFile(rootPath,relative){const base=root(rootPath),item=target(base,relative);if(lstatSync(item.path).isSymbolicLink())throw new Error("Saved code symlink is not allowed");if(!existsSync(item.path)||!statSync(item.path).isFile())throw new Error("Saved code file not found");safeExisting(base,item.path);if(statSync(item.path).size>limit)throw new Error("File exceeds the 1 MiB edit limit");return {path:item.clean,content:readFileSync(item.path,"utf8"),language:language(item.clean)}}
export function saveCodeFile(rootPath,relative,content=""){const base=root(rootPath),item=target(base,relative);if(typeof content!=="string"||Buffer.byteLength(content)>limit)throw new Error("File exceeds the 1 MiB edit limit");mkdirSync(dirname(item.path),{recursive:true,mode:0o700});if(realpathSync(dirname(item.path))!==dirname(item.path))throw new Error("Saved code symlink is not allowed");if(existsSync(item.path))safeExisting(base,item.path);const temporary=join(dirname(item.path),`.${basename(item.path)}.${randomUUID()}.tmp`);writeFileSync(temporary,content,{encoding:"utf8",mode:0o600,flag:"wx"});renameSync(temporary,item.path);return {path:item.clean,language:language(item.clean)}}
