import {randomUUID} from "node:crypto";
import {getDatabase} from "./db.mjs";

export const widgetTypes=["tasks","events","notes","captures","projects","notifications","automations","study"];
const text=(value,name,max=300)=>{if(typeof value!=="string"||!value.trim())throw new Error(`${name} is required`);if(value.length>max)throw new Error(`${name} is too long`);return value.trim()};
const widget=(value,index)=>{const type=widgetTypes.includes(value?.type)?value.type:null;if(!type)throw new Error("Unknown dashboard widget type");const x=Number(value.x),y=Number(value.y),w=Number(value.w),h=Number(value.h);if(![x,y,w,h].every(Number.isInteger)||x<0||y<0||w<2||h<1||x+w>12||y>100||h>12)throw new Error("Widget layout is outside the 12-column grid");return {id:String(value.id||randomUUID()).slice(0,100),type,title:String(value.title||type[0].toUpperCase()+type.slice(1)).slice(0,100),x,y,w,h,config:value.config&&typeof value.config==="object"&&!Array.isArray(value.config)?value.config:{},order:index}};
const layout=value=>{if(!Array.isArray(value))throw new Error("layout must be an array");if(value.length>20)throw new Error("Dashboard supports at most 20 widgets");const widgets=value.map(widget),ids=new Set(widgets.map(item=>item.id));if(ids.size!==widgets.length)throw new Error("Widget IDs must be unique");for(let i=0;i<widgets.length;i++)for(let j=i+1;j<widgets.length;j++){const a=widgets[i],b=widgets[j],overlap=a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;if(overlap)throw new Error("Dashboard widgets cannot overlap")}return widgets};
const rowView=row=>({...row,layout:JSON.parse(row.layout_json),layout_json:undefined});

export function saveDashboard(userId,input,db=getDatabase()){const id=input.id||randomUUID(),before=db.prepare("SELECT * FROM dashboards WHERE id=? AND user_id=?").get(id,userId);if(input.id&&!before)throw Object.assign(new Error("Dashboard not found"),{status:404});if(before&&input.version!==before.version)throw Object.assign(new Error(`Expected version ${before.version}`),{status:409,code:"VERSION_CONFLICT"});const time=new Date().toISOString(),position=before?.position??db.prepare("SELECT COUNT(*) count FROM dashboards WHERE user_id=?").get(userId).count,widgets=layout(input.layout||[]);db.prepare(`INSERT INTO dashboards(id,user_id,name,position,layout_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,layout_json=excluded.layout_json,updated_at=excluded.updated_at,version=dashboards.version+1`).run(id,userId,text(input.name,"name"),position,JSON.stringify(widgets),before?.created_at||time,time);return rowView(db.prepare("SELECT * FROM dashboards WHERE id=?").get(id))}
export const listDashboards=(userId,db=getDatabase())=>db.prepare("SELECT * FROM dashboards WHERE user_id=? ORDER BY position,id").all(userId).map(rowView);
export function duplicateDashboard(userId,id,db=getDatabase()){const source=db.prepare("SELECT * FROM dashboards WHERE id=? AND user_id=?").get(id,userId);if(!source)throw Object.assign(new Error("Dashboard not found"),{status:404});return saveDashboard(userId,{name:`${source.name} copy`,layout:JSON.parse(source.layout_json)},db)}
export function deleteDashboard(userId,id,version,db=getDatabase()){const row=db.prepare("SELECT version FROM dashboards WHERE id=? AND user_id=?").get(id,userId);if(!row)throw Object.assign(new Error("Dashboard not found"),{status:404});if(Number(version)!==row.version)throw Object.assign(new Error(`Expected version ${row.version}`),{status:409,code:"VERSION_CONFLICT"});return {deleted:db.prepare("DELETE FROM dashboards WHERE id=? AND user_id=?").run(id,userId).changes}}
export function reorderDashboards(userId,ids,db=getDatabase()){if(!Array.isArray(ids)||new Set(ids).size!==ids.length)throw new Error("ids must be unique");const current=db.prepare("SELECT id FROM dashboards WHERE user_id=? ORDER BY id").all(userId).map(row=>row.id).sort();if(ids.length!==current.length||!ids.slice().sort().every((id,index)=>id===current[index]))throw new Error("ids must contain every dashboard exactly once");db.exec("BEGIN IMMEDIATE");try{const update=db.prepare("UPDATE dashboards SET position=?,updated_at=?,version=version+1 WHERE id=? AND user_id=?"),time=new Date().toISOString();ids.forEach((id,index)=>update.run(index,time,id,userId));db.exec("COMMIT");return listDashboards(userId,db)}catch(error){db.exec("ROLLBACK");throw error}}

const widgetData=(type,db)=>({
  tasks:()=>db.prepare("SELECT id,title,project,due,completed FROM tasks WHERE archived=0 ORDER BY completed,due LIMIT 8").all(),events:()=>db.prepare("SELECT id,title,start_at AS startAt,location FROM events WHERE deleted_at IS NULL ORDER BY start_at LIMIT 8").all(),notes:()=>db.prepare("SELECT id,title,excerpt,updated_at AS updatedAt FROM notes WHERE trashed=0 ORDER BY updated_at DESC LIMIT 8").all(),captures:()=>db.prepare("SELECT id,source,status,source_label AS sourceLabel,created_at AS createdAt FROM captures ORDER BY created_at DESC LIMIT 8").all(),projects:()=>db.prepare("SELECT id,name,status,updated_at AS updatedAt FROM projects ORDER BY updated_at DESC LIMIT 8").all(),notifications:()=>db.prepare("SELECT id,title,kind,read_at AS readAt,created_at AS createdAt FROM notifications ORDER BY created_at DESC LIMIT 8").all(),automations:()=>db.prepare("SELECT id,name,enabled,last_run_at AS lastRunAt FROM automations ORDER BY name LIMIT 8").all(),study:()=>db.prepare("SELECT a.id,a.title,a.due_at AS dueAt,a.status,c.name AS course FROM assignments a JOIN courses c ON c.id=a.course_id ORDER BY a.due_at LIMIT 8").all(),
})[type]();
export function dashboardView(userId,id,db=getDatabase()){const dashboard=listDashboards(userId,db).find(item=>item.id===id);if(!dashboard)throw Object.assign(new Error("Dashboard not found"),{status:404});return {...dashboard,widgets:dashboard.layout.map(item=>({...item,data:widgetData(item.type,db)}))}}
