import {randomUUID} from "node:crypto";
import {getDatabase} from "./db.mjs";

const now=()=>new Date().toISOString();
export function enqueueJob(kind,input,db=getDatabase()){const id=randomUUID(),time=now();db.prepare("INSERT INTO jobs(id,kind,state,input_json,created_at,updated_at) VALUES(?,?,?,?,?,?)").run(id,kind,"queued",JSON.stringify(input),time,time);addJobEvent(id,"queued",{},db);return id}
export function addJobEvent(id,type,data,db=getDatabase()){db.prepare("INSERT INTO job_events(job_id,type,data_json,created_at) VALUES(?,?,?,?)").run(id,type,JSON.stringify(data),now())}
export function claimJob(kinds,leaseSeconds=60,db=getDatabase()){
  const placeholders=kinds.map(()=>"?").join(",");db.exec("BEGIN IMMEDIATE");try{const job=db.prepare(`SELECT * FROM jobs WHERE state='queued' AND kind IN (${placeholders}) ORDER BY created_at LIMIT 1`).get(...kinds);if(!job){db.exec("COMMIT");return null}const lease=new Date(Date.now()+leaseSeconds*1000).toISOString();db.prepare("UPDATE jobs SET state='claimed',lease_until=?,updated_at=?,version=version+1 WHERE id=? AND state='queued'").run(lease,now(),job.id);db.exec("COMMIT");addJobEvent(job.id,"claimed",{leaseUntil:lease},db);return {...job,state:"claimed",input:JSON.parse(job.input_json)}}catch(error){db.exec("ROLLBACK");throw error}}
export function finishJob(id,result,db=getDatabase()){db.prepare("UPDATE jobs SET state='completed',result_json=?,lease_until=NULL,updated_at=?,version=version+1 WHERE id=?").run(JSON.stringify(result),now(),id);addJobEvent(id,"completed",result,db)}
export function failJob(id,error,db=getDatabase()){db.prepare("UPDATE jobs SET state='failed',error=?,lease_until=NULL,updated_at=?,version=version+1 WHERE id=?").run(String(error).slice(0,4000),now(),id);addJobEvent(id,"failed",{message:String(error)},db)}
export function cancelJob(id,db=getDatabase()){const result=db.prepare("UPDATE jobs SET cancel_requested=1,updated_at=?,version=version+1 WHERE id=? AND state IN ('queued','claimed','running')").run(now(),id);if(result.changes)addJobEvent(id,"cancel-requested",{},db);return result.changes===1}
export function getJob(id,db=getDatabase()){const job=db.prepare("SELECT * FROM jobs WHERE id=?").get(id);if(!job)return null;return {...job,input:JSON.parse(job.input_json),result:job.result_json?JSON.parse(job.result_json):null,events:db.prepare("SELECT * FROM job_events WHERE job_id=? ORDER BY id").all(id).map(e=>({...e,data:JSON.parse(e.data_json)}))}}
