import {randomUUID} from "node:crypto";
import {getDatabase} from "./db.mjs";
import {enqueueJob} from "./jobs.mjs";

const now=()=>new Date().toISOString();
const text=(value,name,max=1000)=>{if(typeof value!=="string"||!value.trim())throw new Error(`${name} is required`);if(value.length>max)throw new Error(`${name} is too long`);return value.trim()};
const version=(input,row)=>{if(row&&input.version!==row.version)throw Object.assign(new Error(`Expected version ${row.version}`),{status:409,code:"VERSION_CONFLICT"})};

export function saveCourse(input,db=getDatabase()){const id=input.id||randomUUID(),before=db.prepare("SELECT * FROM courses WHERE id=?").get(id);version(input,before);const time=now();db.prepare(`INSERT INTO courses(id,code,name,term,color,archived,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET code=excluded.code,name=excluded.name,term=excluded.term,color=excluded.color,archived=excluded.archived,updated_at=excluded.updated_at,version=courses.version+1`).run(id,String(input.code||"").slice(0,50),text(input.name,"name",300),String(input.term||"").slice(0,100),String(input.color||"").slice(0,30),input.archived?1:0,before?.created_at||time,time);return db.prepare("SELECT * FROM courses WHERE id=?").get(id)}
export const listCourses=(db=getDatabase())=>db.prepare("SELECT * FROM courses ORDER BY archived,name").all();

export function saveAssignment(input,db=getDatabase()){const id=input.id||randomUUID(),course=db.prepare("SELECT id FROM courses WHERE id=?").get(input.courseId);if(!course)throw Object.assign(new Error("Course not found"),{status:404});const before=db.prepare("SELECT * FROM assignments WHERE id=?").get(id);version(input,before);const status=["todo","doing","submitted","graded"].includes(input.status)?input.status:"todo",time=now(),score=input.score==null?null:Number(input.score);if(score!=null&&(!Number.isFinite(score)||score<0))throw new Error("score must be non-negative");db.prepare(`INSERT INTO assignments(id,course_id,title,due_at,status,score,source,external_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET course_id=excluded.course_id,title=excluded.title,due_at=excluded.due_at,status=excluded.status,score=excluded.score,source=excluded.source,external_id=excluded.external_id,updated_at=excluded.updated_at,version=assignments.version+1`).run(id,input.courseId,text(input.title,"title",500),input.dueAt||null,status,score,input.source||null,input.externalId||null,before?.created_at||time,time);return db.prepare("SELECT * FROM assignments WHERE id=?").get(id)}
export const listAssignments=(courseId=null,db=getDatabase())=>courseId?db.prepare("SELECT * FROM assignments WHERE course_id=? ORDER BY due_at").all(courseId):db.prepare("SELECT * FROM assignments ORDER BY due_at").all();

export function saveCard(input,db=getDatabase()){const id=input.id||randomUUID(),before=db.prepare("SELECT * FROM study_cards WHERE id=?").get(id);version(input,before);if(input.courseId&&!db.prepare("SELECT id FROM courses WHERE id=?").get(input.courseId))throw Object.assign(new Error("Course not found"),{status:404});const time=now();db.prepare(`INSERT INTO study_cards(id,course_id,front,back,due_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET course_id=excluded.course_id,front=excluded.front,back=excluded.back,updated_at=excluded.updated_at,version=study_cards.version+1`).run(id,input.courseId||null,text(input.front,"front",5000),text(input.back,"back",10000),before?.due_at||time,before?.created_at||time,time);return db.prepare("SELECT * FROM study_cards WHERE id=?").get(id)}
export function reviewCard(id,rating,db=getDatabase()){rating=Number(rating);if(!Number.isInteger(rating)||rating<0||rating>5)throw new Error("rating must be between 0 and 5");const card=db.prepare("SELECT * FROM study_cards WHERE id=?").get(id);if(!card)throw Object.assign(new Error("Card not found"),{status:404});const repetitions=rating<3?0:card.repetitions+1,interval=rating<3?1:repetitions===1?1:repetitions===2?6:Math.max(1,Math.round(card.interval_days*card.ease)),ease=Math.max(1.3,card.ease+(0.1-(5-rating)*(0.08+(5-rating)*0.02))),reviewed=now(),due=new Date(Date.now()+interval*86400000).toISOString();db.prepare("UPDATE study_cards SET due_at=?,interval_days=?,ease=?,repetitions=?,updated_at=?,version=version+1 WHERE id=?").run(due,interval,ease,repetitions,reviewed,id);db.prepare("INSERT INTO card_reviews(id,card_id,rating,reviewed_at,next_due_at) VALUES(?,?,?,?,?)").run(randomUUID(),id,rating,reviewed,due);return db.prepare("SELECT * FROM study_cards WHERE id=?").get(id)}
export const dueCards=(limit=50,db=getDatabase())=>db.prepare("SELECT * FROM study_cards WHERE due_at<=? ORDER BY due_at LIMIT ?").all(now(),Math.min(Math.max(Number(limit)||50,1),200));

export function saveQuiz(input,db=getDatabase()){const id=input.id||randomUUID(),before=db.prepare("SELECT * FROM quizzes WHERE id=?").get(id);version(input,before);const questions=Array.isArray(input.questions)?input.questions.slice(0,100).map((question,index)=>({id:String(question.id||index+1),prompt:text(question.prompt,"prompt",2000),choices:Array.isArray(question.choices)?question.choices.slice(0,10).map(String):[],answer:Number(question.answer)})):[];if(!questions.length||questions.some(question=>!Number.isInteger(question.answer)||question.answer<0||question.answer>=question.choices.length))throw new Error("Quiz questions require choices and a valid answer index");const time=now();db.prepare(`INSERT INTO quizzes(id,course_id,title,questions_json,created_at,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET course_id=excluded.course_id,title=excluded.title,questions_json=excluded.questions_json,updated_at=excluded.updated_at,version=quizzes.version+1`).run(id,input.courseId||null,text(input.title,"title",500),JSON.stringify(questions),before?.created_at||time,time);return {id,title:input.title,questionCount:questions.length,version:(before?.version||0)+1}}
export function listQuizzes(db=getDatabase()){return db.prepare("SELECT id,course_id,title,questions_json,version FROM quizzes ORDER BY updated_at DESC").all().map(row=>({...row,questions:JSON.parse(row.questions_json).map(({answer,...question})=>question),questions_json:undefined}))}
export function submitQuiz(id,answers,db=getDatabase()){const quiz=db.prepare("SELECT * FROM quizzes WHERE id=?").get(id);if(!quiz)throw Object.assign(new Error("Quiz not found"),{status:404});const questions=JSON.parse(quiz.questions_json);if(!Array.isArray(answers)||answers.length!==questions.length)throw new Error("One answer is required per question");const correct=questions.reduce((count,question,index)=>count+(Number(answers[index])===question.answer?1:0),0),score=correct/questions.length*100,attempt={id:randomUUID(),quizId:id,score,correct,total:questions.length,submittedAt:now()};db.prepare("INSERT INTO quiz_attempts(id,quiz_id,answers_json,score,submitted_at) VALUES(?,?,?,?,?)").run(attempt.id,id,JSON.stringify(answers),score,attempt.submittedAt);return attempt}

export function createNotification(input,db=getDatabase()){const id=randomUUID(),created=now(),relatedType=input.relatedType?String(input.relatedType).slice(0,50):null,relatedId=input.relatedId?String(input.relatedId).slice(0,200):null;if((relatedType&&!relatedId)||(!relatedType&&relatedId))throw new Error("Related type and ID are required together");db.prepare("INSERT INTO notifications(id,kind,title,body,related_type,related_id,created_at) VALUES(?,?,?,?,?,?,?)").run(id,String(input.kind||"info").slice(0,50),text(input.title,"title",500),String(input.body||"").slice(0,4000),relatedType,relatedId,created);const insert=db.prepare("INSERT OR IGNORE INTO notification_deliveries(id,notification_id,subscription_id,next_attempt_at,created_at,updated_at) VALUES(?,?,?,?,?,?)");for(const subscription of db.prepare("SELECT id FROM push_subscriptions").all())insert.run(randomUUID(),id,subscription.id,created,created,created);return db.prepare("SELECT * FROM notifications WHERE id=?").get(id)}
export const listNotifications=(db=getDatabase())=>db.prepare("SELECT * FROM notifications ORDER BY created_at DESC LIMIT 200").all();
export function readNotification(id,db=getDatabase()){const result=db.prepare("UPDATE notifications SET read_at=? WHERE id=?").run(now(),id);if(!result.changes)throw Object.assign(new Error("Notification not found"),{status:404});return {ok:true}}
export function readAllNotifications(db=getDatabase()){return {updated:db.prepare("UPDATE notifications SET read_at=? WHERE read_at IS NULL").run(now()).changes}}
export function deliverDueReminders(date=new Date(),db=getDatabase()){const due=date.toISOString(),sent=[];db.exec("BEGIN IMMEDIATE");try{for(const [table,kind] of [["tasks","task"],["events","event"]])for(const row of db.prepare(`SELECT id,title,reminder_at FROM ${table} WHERE reminder_at<=? AND reminder_sent_at IS NULL ${table==="tasks"?"AND completed=0 AND archived=0":""} ORDER BY reminder_at LIMIT 100`).all(due)){if(db.prepare(`UPDATE ${table} SET reminder_sent_at=? WHERE id=? AND reminder_sent_at IS NULL`).run(due,row.id).changes){sent.push(createNotification({kind:`${kind}-reminder`,title:row.title,body:`Reminder scheduled for ${row.reminder_at}`},db))}}db.exec("COMMIT");return sent}catch(error){db.exec("ROLLBACK");throw error}}
export function savePushSubscription(input,db=getDatabase()){const endpoint=text(input.endpoint,"endpoint",4000),keys=input.keys&&typeof input.keys==="object"?input.keys:{};if(!endpoint.startsWith("https://"))throw new Error("Push endpoint must use HTTPS");const id=randomUUID(),time=now();db.prepare("INSERT INTO push_subscriptions(id,endpoint,keys_json,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(endpoint) DO UPDATE SET keys_json=excluded.keys_json,updated_at=excluded.updated_at").run(id,endpoint,JSON.stringify(keys),time,time);return {ok:true}}

export function saveAutomation(input,db=getDatabase()){const id=input.id||randomUUID(),before=db.prepare("SELECT * FROM automations WHERE id=?").get(id);version(input,before);const trigger=["manual","schedule","capture"].includes(input.triggerKind)?input.triggerKind:"manual",action=["skill","notification"].includes(input.actionKind)?input.actionKind:"notification";if(trigger==="schedule"&&!input.schedule)throw new Error("schedule is required");const time=now();db.prepare(`INSERT INTO automations(id,name,trigger_kind,schedule,action_kind,config_json,enabled,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,trigger_kind=excluded.trigger_kind,schedule=excluded.schedule,action_kind=excluded.action_kind,config_json=excluded.config_json,enabled=excluded.enabled,updated_at=excluded.updated_at,version=automations.version+1`).run(id,text(input.name,"name",300),trigger,input.schedule||null,action,JSON.stringify(input.config||{}),input.enabled===false?0:1,before?.created_at||time,time);return db.prepare("SELECT * FROM automations WHERE id=?").get(id)}
export const listAutomations=(db=getDatabase())=>db.prepare("SELECT * FROM automations ORDER BY name").all();
export function startAutomationRun(id,db=getDatabase()){const automation=db.prepare("SELECT * FROM automations WHERE id=? AND enabled=1").get(id);if(!automation)throw Object.assign(new Error("Enabled automation not found"),{status:404});const runId=randomUUID(),started=now();db.prepare("INSERT INTO automation_runs(id,automation_id,state,started_at) VALUES(?,?,?,?)").run(runId,id,"running",started);db.prepare("UPDATE automations SET last_run_at=? WHERE id=?").run(started,id);return db.prepare("SELECT * FROM automation_runs WHERE id=?").get(runId)}
export function finishAutomationRun(id,output,error=null,db=getDatabase()){const state=error?"failed":"completed",result=db.prepare("UPDATE automation_runs SET state=?,finished_at=?,output_json=?,error=? WHERE id=? AND state='running'").run(state,now(),output==null?null:JSON.stringify(output),error?String(error).slice(0,4000):null,id);if(!result.changes)throw Object.assign(new Error("Running automation not found"),{status:404});return db.prepare("SELECT * FROM automation_runs WHERE id=?").get(id)}
export const automationRuns=(automationId,db=getDatabase())=>db.prepare("SELECT * FROM automation_runs WHERE automation_id=? ORDER BY started_at DESC LIMIT 100").all(automationId);
export function executeAutomation(id,db=getDatabase()){const automation=db.prepare("SELECT * FROM automations WHERE id=? AND enabled=1").get(id);if(!automation)throw Object.assign(new Error("Enabled automation not found"),{status:404});const run=startAutomationRun(id,db),config=JSON.parse(automation.config_json);try{let output;if(automation.action_kind==="notification")output={notificationId:createNotification({kind:"automation",title:config.title||automation.name,body:config.body||""},db).id};else output={jobId:enqueueJob("skill-run",{skill:text(config.skill,"skill",100),input:config.input||{}},db)};finishAutomationRun(run.id,output,null,db);return {...run,state:"completed",output}}catch(error){finishAutomationRun(run.id,null,error,db);throw error}}
const cronDue=(schedule,last,date)=>{const parts=String(schedule||"").trim().split(/\s+/);if(parts.length!==5)return false;const minute=parts[0]==="*"||Number(parts[0])===date.getMinutes(),hour=parts[1]==="*"||Number(parts[1])===date.getHours(),lastMinute=last?new Date(last).toISOString().slice(0,16):"";return minute&&hour&&lastMinute!==date.toISOString().slice(0,16)};
export function runScheduledAutomations(date=new Date(),db=getDatabase()){const due=db.prepare("SELECT id,schedule,last_run_at FROM automations WHERE enabled=1 AND trigger_kind='schedule'").all().filter(row=>cronDue(row.schedule,row.last_run_at,date));return due.map(row=>executeAutomation(row.id,db))}
export function automationMetrics(id,db=getDatabase()){const rows=db.prepare("SELECT state,COUNT(*) count FROM automation_runs WHERE automation_id=? GROUP BY state").all(id),total=rows.reduce((sum,row)=>sum+row.count,0);return {total,states:Object.fromEntries(rows.map(row=>[row.state,row.count])),lastRun:db.prepare("SELECT state,started_at AS startedAt,finished_at AS finishedAt,error FROM automation_runs WHERE automation_id=? ORDER BY started_at DESC LIMIT 1").get(id)||null}}
