import {randomUUID} from "node:crypto";
import {getDatabase} from "./db.mjs";
import {cancelJob,enqueueJob,getJob,retryJob} from "./jobs.mjs";

const now=()=>new Date().toISOString();
const text=(value,name,max=1000)=>{if(typeof value!=="string"||!value.trim())throw new Error(`${name} is required`);if(value.length>max)throw new Error(`${name} is too long`);return value.trim()};
const version=(input,row)=>{if(row&&input.version!==row.version)throw Object.assign(new Error(`Expected version ${row.version}`),{status:409,code:"VERSION_CONFLICT"})};
const scoped=(db,table,id,workspaceId)=>{const row=workspaceId?db.prepare(`SELECT * FROM ${table} WHERE id=? AND workspace_id=?`).get(id,workspaceId):db.prepare(`SELECT * FROM ${table} WHERE id=?`).get(id);if(!row&&workspaceId&&db.prepare(`SELECT id FROM ${table} WHERE id=?`).get(id))throw Object.assign(new Error(`${table.slice(0,-1)} not found`),{status:404});return row};

export function saveCourse(input,db=getDatabase(),workspaceId=null){const id=input.id||randomUUID(),before=scoped(db,"courses",id,workspaceId);version(input,before);const time=now();db.prepare(`INSERT INTO courses(id,code,name,term,color,archived,created_at,updated_at,workspace_id) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET code=excluded.code,name=excluded.name,term=excluded.term,color=excluded.color,archived=excluded.archived,updated_at=excluded.updated_at,version=courses.version+1`).run(id,String(input.code||"").slice(0,50),text(input.name,"name",300),String(input.term||"").slice(0,100),String(input.color||"").slice(0,30),input.archived?1:0,before?.created_at||time,time,workspaceId);return scoped(db,"courses",id,workspaceId)}
export const listCourses=(db=getDatabase(),workspaceId=null)=>db.prepare(`SELECT * FROM courses${workspaceId?" WHERE workspace_id=?":""} ORDER BY archived,name`).all(...(workspaceId?[workspaceId]:[]));

export function saveAssignment(input,db=getDatabase(),workspaceId=null){const id=input.id||randomUUID(),course=scoped(db,"courses",input.courseId,workspaceId);if(!course)throw Object.assign(new Error("Course not found"),{status:404});const before=scoped(db,"assignments",id,workspaceId);version(input,before);const status=["todo","doing","submitted","graded"].includes(input.status)?input.status:"todo",time=now(),score=input.score==null?null:Number(input.score);if(score!=null&&(!Number.isFinite(score)||score<0))throw new Error("score must be non-negative");db.prepare(`INSERT INTO assignments(id,course_id,title,due_at,status,score,source,external_id,created_at,updated_at,workspace_id) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET course_id=excluded.course_id,title=excluded.title,due_at=excluded.due_at,status=excluded.status,score=excluded.score,source=excluded.source,external_id=excluded.external_id,updated_at=excluded.updated_at,version=assignments.version+1`).run(id,input.courseId,text(input.title,"title",500),input.dueAt||null,status,score,input.source||null,input.externalId||null,before?.created_at||time,time,workspaceId);return scoped(db,"assignments",id,workspaceId)}
export const listAssignments=(courseId=null,db=getDatabase(),workspaceId=null)=>db.prepare(`SELECT * FROM assignments WHERE 1=1${courseId?" AND course_id=?":""}${workspaceId?" AND workspace_id=?":""} ORDER BY due_at`).all(...(courseId?[courseId]:[]),...(workspaceId?[workspaceId]:[]));

export function saveCard(input,db=getDatabase(),workspaceId=null){const id=input.id||randomUUID(),before=scoped(db,"study_cards",id,workspaceId);version(input,before);if(input.courseId&&!scoped(db,"courses",input.courseId,workspaceId))throw Object.assign(new Error("Course not found"),{status:404});const time=now();db.prepare(`INSERT INTO study_cards(id,course_id,front,back,due_at,created_at,updated_at,workspace_id) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET course_id=excluded.course_id,front=excluded.front,back=excluded.back,updated_at=excluded.updated_at,version=study_cards.version+1`).run(id,input.courseId||null,text(input.front,"front",5000),text(input.back,"back",10000),before?.due_at||time,before?.created_at||time,time,workspaceId);return scoped(db,"study_cards",id,workspaceId)}
export function reviewCard(id,rating,db=getDatabase(),workspaceId=null){rating=Number(rating);if(!Number.isInteger(rating)||rating<0||rating>5)throw new Error("rating must be between 0 and 5");const card=scoped(db,"study_cards",id,workspaceId);if(!card)throw Object.assign(new Error("Card not found"),{status:404});const repetitions=rating<3?0:card.repetitions+1,interval=rating<3?1:repetitions===1?1:repetitions===2?6:Math.max(1,Math.round(card.interval_days*card.ease)),ease=Math.max(1.3,card.ease+(0.1-(5-rating)*(0.08+(5-rating)*0.02))),reviewed=now(),due=new Date(Date.now()+interval*86400000).toISOString();db.prepare("UPDATE study_cards SET due_at=?,interval_days=?,ease=?,repetitions=?,updated_at=?,version=version+1 WHERE id=?").run(due,interval,ease,repetitions,reviewed,id);db.prepare("INSERT INTO card_reviews(id,card_id,rating,reviewed_at,next_due_at) VALUES(?,?,?,?,?)").run(randomUUID(),id,rating,reviewed,due);return scoped(db,"study_cards",id,workspaceId)}
export const dueCards=(limit=50,db=getDatabase(),workspaceId=null)=>db.prepare(`SELECT * FROM study_cards WHERE due_at<=?${workspaceId?" AND workspace_id=?":""} ORDER BY due_at LIMIT ?`).all(now(),...(workspaceId?[workspaceId]:[]),Math.min(Math.max(Number(limit)||50,1),200));

export function saveQuiz(input,db=getDatabase(),workspaceId=null){const id=input.id||randomUUID(),before=scoped(db,"quizzes",id,workspaceId);version(input,before);if(input.courseId&&!scoped(db,"courses",input.courseId,workspaceId))throw Object.assign(new Error("Course not found"),{status:404});const questions=Array.isArray(input.questions)?input.questions.slice(0,100).map((question,index)=>({id:String(question.id||index+1),prompt:text(question.prompt,"prompt",2000),choices:Array.isArray(question.choices)?question.choices.slice(0,10).map(String):[],answer:Number(question.answer)})):[];if(!questions.length||questions.some(question=>!Number.isInteger(question.answer)||question.answer<0||question.answer>=question.choices.length))throw new Error("Quiz questions require choices and a valid answer index");const time=now();db.prepare(`INSERT INTO quizzes(id,course_id,title,questions_json,created_at,updated_at,workspace_id) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET course_id=excluded.course_id,title=excluded.title,questions_json=excluded.questions_json,updated_at=excluded.updated_at,version=quizzes.version+1`).run(id,input.courseId||null,text(input.title,"title",500),JSON.stringify(questions),before?.created_at||time,time,workspaceId);return {id,title:input.title,questionCount:questions.length,version:(before?.version||0)+1}}
export function listQuizzes(db=getDatabase(),workspaceId=null){return db.prepare(`SELECT id,course_id,title,questions_json,version FROM quizzes${workspaceId?" WHERE workspace_id=?":""} ORDER BY updated_at DESC`).all(...(workspaceId?[workspaceId]:[])).map(row=>({...row,questions:JSON.parse(row.questions_json).map(({answer,...question})=>question),questions_json:undefined}))}
export function submitQuiz(id,answers,db=getDatabase(),workspaceId=null){const quiz=scoped(db,"quizzes",id,workspaceId);if(!quiz)throw Object.assign(new Error("Quiz not found"),{status:404});const questions=JSON.parse(quiz.questions_json);if(!Array.isArray(answers)||answers.length!==questions.length)throw new Error("One answer is required per question");const correct=questions.reduce((count,question,index)=>count+(Number(answers[index])===question.answer?1:0),0),score=correct/questions.length*100,attempt={id:randomUUID(),quizId:id,score,correct,total:questions.length,submittedAt:now()};db.prepare("INSERT INTO quiz_attempts(id,quiz_id,answers_json,score,submitted_at) VALUES(?,?,?,?,?)").run(attempt.id,id,JSON.stringify(answers),score,attempt.submittedAt);return attempt}

export function createNotification(input,db=getDatabase()){const id=randomUUID(),created=now(),relatedType=input.relatedType?String(input.relatedType).slice(0,50):null,relatedId=input.relatedId?String(input.relatedId).slice(0,200):null;if((relatedType&&!relatedId)||(!relatedType&&relatedId))throw new Error("Related type and ID are required together");db.prepare("INSERT INTO notifications(id,kind,title,body,related_type,related_id,created_at) VALUES(?,?,?,?,?,?,?)").run(id,String(input.kind||"info").slice(0,50),text(input.title,"title",500),String(input.body||"").slice(0,4000),relatedType,relatedId,created);const insert=db.prepare("INSERT OR IGNORE INTO notification_deliveries(id,notification_id,subscription_id,next_attempt_at,created_at,updated_at) VALUES(?,?,?,?,?,?)");for(const subscription of db.prepare("SELECT id FROM push_subscriptions").all())insert.run(randomUUID(),id,subscription.id,created,created,created);return db.prepare("SELECT * FROM notifications WHERE id=?").get(id)}
export const listNotifications=(db=getDatabase())=>db.prepare("SELECT * FROM notifications ORDER BY created_at DESC LIMIT 200").all();
export function readNotification(id,db=getDatabase()){const result=db.prepare("UPDATE notifications SET read_at=? WHERE id=?").run(now(),id);if(!result.changes)throw Object.assign(new Error("Notification not found"),{status:404});return {ok:true}}
export function readAllNotifications(db=getDatabase()){return {updated:db.prepare("UPDATE notifications SET read_at=? WHERE read_at IS NULL").run(now()).changes}}
export function deliverDueReminders(date=new Date(),db=getDatabase()){const due=date.toISOString(),sent=[];db.exec("BEGIN IMMEDIATE");try{for(const [table,kind] of [["tasks","task"],["events","event"]])for(const row of db.prepare(`SELECT id,title,reminder_at FROM ${table} WHERE reminder_at<=? AND reminder_sent_at IS NULL ${table==="tasks"?"AND completed=0 AND archived=0":""} ORDER BY reminder_at LIMIT 100`).all(due)){if(db.prepare(`UPDATE ${table} SET reminder_sent_at=? WHERE id=? AND reminder_sent_at IS NULL`).run(due,row.id).changes){sent.push(createNotification({kind:`${kind}-reminder`,title:row.title,body:`Reminder scheduled for ${row.reminder_at}`},db))}}db.exec("COMMIT");return sent}catch(error){db.exec("ROLLBACK");throw error}}
export function savePushSubscription(input,db=getDatabase()){const endpoint=text(input.endpoint,"endpoint",4000),keys=input.keys&&typeof input.keys==="object"?input.keys:{};if(!endpoint.startsWith("https://"))throw new Error("Push endpoint must use HTTPS");const id=randomUUID(),time=now();db.prepare("INSERT INTO push_subscriptions(id,endpoint,keys_json,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(endpoint) DO UPDATE SET keys_json=excluded.keys_json,updated_at=excluded.updated_at").run(id,endpoint,JSON.stringify(keys),time,time);return {ok:true}}
export function deletePushSubscription(endpoint,db=getDatabase()){if(typeof endpoint!=="string"||!endpoint.startsWith("https://"))throw new Error("Valid push endpoint required");return {deleted:db.prepare("DELETE FROM push_subscriptions WHERE endpoint=?").run(endpoint).changes}}

const cronField=(value,min,max)=>value==="*"||/^\d+$/.test(value)&&Number(value)>=min&&Number(value)<=max;
const validCron=value=>{const fields=String(value||"").trim().split(/\s+/);return fields.length===5&&cronField(fields[0],0,59)&&cronField(fields[1],0,23)&&cronField(fields[2],1,31)&&cronField(fields[3],1,12)&&cronField(fields[4],0,6)};
const normalizeStep=(step,name)=>{const kind=step?.kind;if(kind==="notification")return {kind,config:{title:text(step.config?.title||name,"notification title",500),body:String(step.config?.body||"").slice(0,4000)}};if(kind==="skill")return {kind,config:{skill:text(step.config?.skill,"skill",100),input:step.config?.input&&typeof step.config.input==="object"?step.config.input:{}}};throw new Error("workflow steps must be notification or skill actions")};
const automationDefinition=input=>{const trigger=["manual","schedule","capture"].includes(input.triggerKind)?input.triggerKind:"manual",requested=["skill","notification","workflow"].includes(input.actionKind)?input.actionKind:"notification",schedule=trigger==="schedule"?String(input.schedule||"").trim():null,config=input.config&&typeof input.config==="object"&&!Array.isArray(input.config)?{...input.config}:{},name=text(input.name,"name",300);if(trigger==="schedule"&&!validCron(schedule))throw new Error("schedule must be a five-field cron expression using * or numeric values");const steps=Array.isArray(config.steps)?config.steps.slice(0,10).map(step=>normalizeStep(step,name)):[];if((config.steps||requested==="workflow")&&!steps.length)throw new Error("workflow requires at least one step");if(steps.filter(step=>step.kind==="skill").length>1||steps.some((step,index)=>step.kind==="skill"&&index!==steps.length-1))throw new Error("a workflow may have one skill step, and it must be last");const action=steps.length?"workflow":requested;if(!steps.length){if(action==="skill")text(config.skill,"skill",100);else text(config.title||name,"notification title",500)}const conditions=Array.isArray(config.conditions)?config.conditions.slice(0,10).map(condition=>{const field=["source","text"].includes(condition?.field)?condition.field:null,operator=["equals","contains"].includes(condition?.operator)?condition.operator:null,value=String(condition?.value||"").trim();if(!field||!operator||!value||value.length>500)throw new Error("conditions require a source/text field, equals/contains operator, and value");return {field,operator,value}}):[];config.conditions=conditions;if(steps.length)config.steps=steps;return {name,trigger,action,schedule,config}}
const stepLabel=step=>step.kind==="skill"?`Run skill: ${step.config.skill}`:`Create notification: ${step.config.title}`;
export function previewAutomation(input){const value=automationDefinition(input),steps=value.config.steps||[normalizeStep({kind:value.action,config:value.config},value.name)];return {trigger:value.trigger==="schedule"?`Schedule: ${value.schedule}`:value.trigger==="capture"?"When a capture is created":"Manual only",conditions:value.config.conditions,actions:steps.map(stepLabel),action:steps.map(stepLabel).join(" → "),enabled:input.enabled!==false}}
export function saveAutomation(input,db=getDatabase()){const id=input.id||randomUUID(),before=db.prepare("SELECT * FROM automations WHERE id=?").get(id);version(input,before);const value=automationDefinition(input),time=now();db.prepare(`INSERT INTO automations(id,name,trigger_kind,schedule,action_kind,config_json,enabled,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,trigger_kind=excluded.trigger_kind,schedule=excluded.schedule,action_kind=excluded.action_kind,config_json=excluded.config_json,enabled=excluded.enabled,updated_at=excluded.updated_at,version=automations.version+1`).run(id,value.name,value.trigger,value.schedule,value.action,JSON.stringify(value.config),input.enabled===false?0:1,before?.created_at||time,time);return db.prepare("SELECT * FROM automations WHERE id=?").get(id)}
export const listAutomations=(db=getDatabase())=>db.prepare("SELECT * FROM automations ORDER BY name").all();
export function deleteAutomation(id,expectedVersion,db=getDatabase()){const row=db.prepare("SELECT version FROM automations WHERE id=?").get(id);if(!row)throw Object.assign(new Error("Automation not found"),{status:404});if(expectedVersion!==row.version)throw Object.assign(new Error(`Expected version ${row.version}`),{status:409,code:"VERSION_CONFLICT"});return {deleted:db.prepare("DELETE FROM automations WHERE id=?").run(id).changes}}
export function startAutomationRun(id,db=getDatabase(),allowDisabled=false){const automation=db.prepare(`SELECT * FROM automations WHERE id=?${allowDisabled?"":" AND enabled=1"}`).get(id);if(!automation)throw Object.assign(new Error(allowDisabled?"Automation not found":"Enabled automation not found"),{status:404});const runId=randomUUID(),started=now();db.prepare("INSERT INTO automation_runs(id,automation_id,state,started_at) VALUES(?,?,?,?)").run(runId,id,"running",started);db.prepare("UPDATE automations SET last_run_at=? WHERE id=?").run(started,id);return db.prepare("SELECT * FROM automation_runs WHERE id=?").get(runId)}
export function finishAutomationRun(id,output,error=null,db=getDatabase()){const state=error?"failed":"completed",result=db.prepare("UPDATE automation_runs SET state=?,finished_at=?,output_json=?,error=? WHERE id=? AND state IN ('queued','running','cancelling')").run(state,now(),output==null?null:JSON.stringify(output),error?String(error).slice(0,4000):null,id);if(!result.changes)throw Object.assign(new Error("Active automation run not found"),{status:404});return db.prepare("SELECT * FROM automation_runs WHERE id=?").get(id)}
const runView=(run,db)=>({...run,steps:db.prepare("SELECT id,position,kind,config_json,state,output_json,error,started_at,finished_at FROM automation_run_steps WHERE run_id=? ORDER BY position").all(run.id)});
export const automationRuns=(automationId,db=getDatabase())=>db.prepare("SELECT * FROM automation_runs WHERE automation_id=? ORDER BY started_at DESC LIMIT 100").all(automationId).map(run=>runView(run,db));
const conditionMatches=(condition,context)=>{const actual=String(context[condition.field]||"");return condition.operator==="equals"?actual===condition.value:actual.toLocaleLowerCase().includes(condition.value.toLocaleLowerCase())};
function advanceAutomationRun(runId,context,db){for(;;){const step=db.prepare("SELECT * FROM automation_run_steps WHERE run_id=? AND state='pending' ORDER BY position LIMIT 1").get(runId);if(!step){const outputs=db.prepare("SELECT position,kind,output_json FROM automation_run_steps WHERE run_id=? ORDER BY position").all(runId).map(item=>({position:item.position,kind:item.kind,output:item.output_json?JSON.parse(item.output_json):null}));return finishAutomationRun(runId,{steps:outputs},null,db)}const config=JSON.parse(step.config_json),started=now();db.prepare("UPDATE automation_run_steps SET state='running',started_at=? WHERE id=? AND state='pending'").run(started,step.id);if(step.kind==="notification"){try{const output={notificationId:createNotification({kind:"automation",title:config.title,body:config.body||""},db).id};db.prepare("UPDATE automation_run_steps SET state='completed',output_json=?,finished_at=? WHERE id=?").run(JSON.stringify(output),now(),step.id);continue}catch(error){db.prepare("UPDATE automation_run_steps SET state='failed',error=?,finished_at=? WHERE id=?").run(String(error).slice(0,4000),now(),step.id);throw error}}const jobId=enqueueJob("skill-run",{skill:config.skill,input:{...(config.input||{}),trigger:context},automationRunId:runId,automationRunStepId:step.id},db);db.prepare("UPDATE automation_run_steps SET state='queued',output_json=? WHERE id=?").run(JSON.stringify({jobId}),step.id);db.prepare("UPDATE automation_runs SET state='queued',job_id=?,output_json=? WHERE id=?").run(jobId,JSON.stringify({jobId}),runId);return runView(db.prepare("SELECT * FROM automation_runs WHERE id=?").get(runId),db)}}
export function executeAutomation(id,db=getDatabase(),context={},allowDisabled=false){const automation=db.prepare(`SELECT * FROM automations WHERE id=?${allowDisabled?"":" AND enabled=1"}`).get(id);if(!automation)throw Object.assign(new Error(allowDisabled?"Automation not found":"Enabled automation not found"),{status:404});const run=startAutomationRun(id,db,allowDisabled),config=JSON.parse(automation.config_json);try{const conditions=Array.isArray(config.conditions)?config.conditions:[];if(!conditions.every(condition=>conditionMatches(condition,context))){db.prepare("UPDATE automation_runs SET state='skipped',finished_at=?,output_json=? WHERE id=?").run(now(),JSON.stringify({reason:"Conditions did not match",context:{source:context.source||null}}),run.id);return runView(db.prepare("SELECT * FROM automation_runs WHERE id=?").get(run.id),db)}const steps=config.steps||[normalizeStep({kind:automation.action_kind,config},automation.name)],insert=db.prepare("INSERT INTO automation_run_steps(id,run_id,position,kind,config_json) VALUES(?,?,?,?,?)");steps.forEach((step,position)=>insert.run(randomUUID(),run.id,position,step.kind,JSON.stringify(step.config)));return advanceAutomationRun(run.id,context,db)}catch(error){finishAutomationRun(run.id,null,error,db);throw error}}
export const testAutomation=(id,db=getDatabase())=>executeAutomation(id,db,{test:true},true);
export function completeAutomationSkillStep(runId,stepId,result,db=getDatabase()){const changed=db.prepare("UPDATE automation_run_steps SET state='completed',output_json=?,error=NULL,finished_at=? WHERE id=? AND run_id=? AND state IN ('queued','running')").run(JSON.stringify(result),now(),stepId,runId).changes;if(!changed)throw new Error("Active automation step not found");const outputs=db.prepare("SELECT position,kind,output_json FROM automation_run_steps WHERE run_id=? ORDER BY position").all(runId).map(item=>({position:item.position,kind:item.kind,output:item.output_json?JSON.parse(item.output_json):null}));return finishAutomationRun(runId,{steps:outputs},null,db)}
export function failAutomationSkillStep(runId,stepId,state,error,db=getDatabase()){const terminal=["failed","cancelled"].includes(state)?state:"failed",time=now();db.prepare("UPDATE automation_run_steps SET state=?,error=?,finished_at=? WHERE id=? AND run_id=? AND state IN ('queued','running')").run(terminal,terminal==="cancelled"?null:String(error||"Automation skill failed").slice(0,4000),time,stepId,runId);db.prepare("UPDATE automation_runs SET state=?,finished_at=?,error=? WHERE id=?").run(terminal,time,terminal==="cancelled"?null:String(error||"Automation skill failed").slice(0,4000),runId)}
export function cancelAutomationRun(automationId,runId,db=getDatabase()){const run=db.prepare("SELECT * FROM automation_runs WHERE id=? AND automation_id=?").get(runId,automationId);if(!run?.job_id||!["queued","running","cancelling"].includes(run.state)||!cancelJob(run.job_id,db))throw Object.assign(new Error("Automation run is not cancellable"),{status:409});const job=getJob(run.job_id,db),state=job.state==="cancelled"?"cancelled":"cancelling",time=now();db.prepare("UPDATE automation_runs SET state=?,finished_at=CASE WHEN ?='cancelled' THEN ? ELSE NULL END WHERE id=?").run(state,state,time,runId);if(state==="cancelled")db.prepare("UPDATE automation_run_steps SET state='cancelled',finished_at=? WHERE run_id=? AND state IN ('queued','running')").run(time,runId);return runView(db.prepare("SELECT * FROM automation_runs WHERE id=?").get(runId),db)}
export function retryAutomationRun(automationId,runId,db=getDatabase()){const run=db.prepare("SELECT * FROM automation_runs WHERE id=? AND automation_id=? AND state='failed'").get(runId,automationId);if(!run?.job_id)throw Object.assign(new Error("Failed automation run not found"),{status:404});retryJob(run.job_id,db);db.prepare("UPDATE automation_runs SET state='queued',finished_at=NULL,error=NULL WHERE id=?").run(runId);db.prepare("UPDATE automation_run_steps SET state='queued',error=NULL,finished_at=NULL WHERE run_id=? AND state='failed'").run(runId);return runView(db.prepare("SELECT * FROM automation_runs WHERE id=?").get(runId),db)}
const cronDue=(schedule,last,date)=>{const parts=String(schedule||"").trim().split(/\s+/);if(parts.length!==5)return false;const minute=parts[0]==="*"||Number(parts[0])===date.getMinutes(),hour=parts[1]==="*"||Number(parts[1])===date.getHours(),lastMinute=last?new Date(last).toISOString().slice(0,16):"";return minute&&hour&&lastMinute!==date.toISOString().slice(0,16)};
export function runScheduledAutomations(date=new Date(),db=getDatabase()){const due=db.prepare("SELECT id,schedule,last_run_at FROM automations WHERE enabled=1 AND trigger_kind='schedule'").all().filter(row=>cronDue(row.schedule,row.last_run_at,date));return due.map(row=>executeAutomation(row.id,db))}
export function runCaptureAutomations(capture,db=getDatabase()){return db.prepare("SELECT id FROM automations WHERE enabled=1 AND trigger_kind='capture' ORDER BY id").all().map(({id})=>{try{return executeAutomation(id,db,{id:capture.id,source:capture.source,text:capture.text})}catch(error){return {automation_id:id,state:"failed",error:String(error.message||error)}}})}
export function automationMetrics(id,db=getDatabase()){const rows=db.prepare("SELECT state,COUNT(*) count FROM automation_runs WHERE automation_id=? GROUP BY state").all(id),total=rows.reduce((sum,row)=>sum+row.count,0);return {total,states:Object.fromEntries(rows.map(row=>[row.state,row.count])),lastRun:db.prepare("SELECT state,started_at AS startedAt,finished_at AS finishedAt,error FROM automation_runs WHERE automation_id=? ORDER BY started_at DESC LIMIT 1").get(id)||null}}
