import {createCipheriv,createDecipheriv,createHash,randomBytes} from "node:crypto";
import {createReadStream,mkdtempSync,readdirSync,readFileSync,renameSync,rmSync,statSync,statfsSync,writeFileSync} from "node:fs";
import {extname,join,resolve} from "node:path";
import {tmpdir} from "node:os";
import {openDatabase,getDatabase} from "./db.mjs";
import {ensureDataDirs,loadConfig} from "./config.mjs";
import {createCapture,importMarkdown,saveEvent,saveTask} from "./core.mjs";
import {storeAsset} from "./objects.mjs";

const secret=/pass(word)?|secret|token|authorization|cookie|api.?key/i;
export function redact(value){if(Array.isArray(value))return value.map(redact);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value).map(([key,item])=>[key,secret.test(key)?"[REDACTED]":redact(item)]));return value}
export function log(level,event,data={},write=console.log){write(JSON.stringify({timestamp:new Date().toISOString(),level,event,...redact(data)}))}

export function healthReport(db=getDatabase(),config=loadConfig()){const disk=statfsSync(config.dataDir),freeBytes=disk.bavail*disk.bsize,quick=db.prepare("PRAGMA quick_check").get().quick_check,foreignKeys=db.prepare("PRAGMA foreign_key_check").all().length;return {ok:quick==="ok"&&!foreignKeys&&freeBytes>=config.minFreeBytes,database:quick,foreignKeyErrors:foreignKeys,freeBytes,diskAlert:freeBytes<config.minFreeBytes,jobs:db.prepare("SELECT state,COUNT(*) count FROM jobs GROUP BY state").all(),checkedAt:new Date().toISOString()}}

const keyFor=config=>{if(config.backupKey.length<32)throw new Error("NOEMA_BACKUP_KEY must contain at least 32 characters");return createHash("sha256").update(config.backupKey).digest()};
export function createBackup(config=ensureDataDirs(loadConfig()),db=getDatabase(config)){const stamp=new Date().toISOString().replace(/[:.]/g,"-"),work=join(config.backupsDir,`.${stamp}.sqlite`),target=join(config.backupsDir,`${stamp}.noema-backup`);db.prepare("VACUUM INTO ?").run(work);const iv=randomBytes(12),cipher=createCipheriv("aes-256-gcm",keyFor(config),iv),encrypted=Buffer.concat([cipher.update(readFileSync(work)),cipher.final()]),tag=cipher.getAuthTag(),temp=`${target}.tmp`;writeFileSync(temp,Buffer.concat([Buffer.from("NOEMA01"),iv,tag,encrypted]),{mode:0o600});renameSync(temp,target);rmSync(work,{force:true});const backups=readdirSync(config.backupsDir).filter(name=>name.endsWith(".noema-backup")||name.endsWith(".lifeos-backup")).sort().reverse();for(const name of backups.slice(config.backupRetention))rmSync(join(config.backupsDir,name));return {path:target,size:encrypted.length+35,retained:Math.min(backups.length,config.backupRetention)}}
export function verifyBackup(path,config=loadConfig()){const source=readFileSync(path),magic=source.subarray(0,7).toString();if(magic!=="NOEMA01"&&magic!=="LIFEOS1")throw new Error("Invalid backup format");const decipher=createDecipheriv("aes-256-gcm",keyFor(config),source.subarray(7,19));decipher.setAuthTag(source.subarray(19,35));const plain=Buffer.concat([decipher.update(source.subarray(35)),decipher.final()]),dir=mkdtempSync(join(tmpdir(),"noema-restore-")),database=join(dir,"verify.sqlite");try{writeFileSync(database,plain,{mode:0o600});const db=openDatabase(database);try{const result=db.prepare("PRAGMA integrity_check").get().integrity_check;if(result!=="ok")throw new Error(`Backup integrity check failed: ${result}`);return {ok:true,size:plain.length}}finally{db.close()}}finally{rmSync(dir,{recursive:true,force:true})}}

const exportTables=["tasks","events","notes","note_versions","note_links","note_blocks","note_ink_blocks","note_optimizations","tutor_sessions","tutor_messages","captures","projects","task_dependencies","assets","capture_assets","pdf_annotations","courses","assignments","study_cards","card_reviews","quizzes","quiz_attempts","notifications","automations","automation_runs","automation_run_steps","jobs","job_events","audit_events"];
export function exportWorkspace(db=getDatabase()){return {format:"noema-workspace",version:1,exportedAt:new Date().toISOString(),data:Object.fromEntries(exportTables.map(table=>[table,redact(db.prepare(`SELECT * FROM ${table}`).all())]))}}

const mimes={".pdf":"application/pdf",".docx":"application/vnd.openxmlformats-officedocument.wordprocessingml.document",".txt":"text/plain",".md":"text/markdown",".csv":"text/csv",".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg",".webp":"image/webp",".gif":"image/gif",".mp3":"audio/mpeg",".wav":"audio/wav",".ogg":"audio/ogg",".webm":"audio/webm",".m4a":"audio/mp4"};
export async function importV1(root,db=getDatabase(),config=ensureDataDirs(loadConfig())){const base=resolve(root),result={notes:0,tasks:0,events:0,attachments:0};for(const name of readdirSync(base)){const path=join(base,name);if(name.endsWith(".md")){importMarkdown(readFileSync(path,"utf8"),db);result.notes++}else if(name==="tasks.json"){const rows=JSON.parse(readFileSync(path,"utf8"));if(!Array.isArray(rows))throw new Error("tasks.json must contain an array");for(const row of rows){saveTask(row,db);result.tasks++}}else if(name==="events.json"){const rows=JSON.parse(readFileSync(path,"utf8"));if(!Array.isArray(rows))throw new Error("events.json must contain an array");for(const row of rows){saveEvent(row,db);result.events++}}else if(name==="attachments"&&statSync(path).isDirectory())for(const file of readdirSync(path)){const mime=mimes[extname(file).toLowerCase()];if(!mime)continue;const asset=await storeAsset({stream:createReadStream(join(path,file)),name:file,mime},config,db);createCapture({text:file,source:"file",sourceLabel:"v1 attachment",assetIds:[asset.id]},db);result.attachments++}}return result}
