import {randomUUID} from "node:crypto";
import {getDatabase} from "./db.mjs";

const now=()=>new Date().toISOString(),types={task:["tasks","title"],event:["events","title"],note:["notes","title"],asset:["assets","name"],capture:["captures","text"],automation:["automations","name"]};
const project=(id,db)=>{const value=db.prepare("SELECT * FROM projects WHERE id=?").get(id);if(!value)throw Object.assign(new Error("Project not found"),{status:404});return value};
const audit=(db,actor,action,id,summary)=>db.prepare("INSERT INTO audit_events(id,actor_id,action,object_type,object_id,summary,created_at) VALUES(?,?,?,?,?,?,?)").run(randomUUID(),actor,action,"project",id,summary,now());
export function linkProject(input,db=getDatabase(),actor=null){project(input.projectId,db);const type=String(input.objectType||""),target=types[type],objectId=String(input.objectId||"");if(!target)throw new Error("Unsupported relationship type");if(!db.prepare(`SELECT 1 FROM ${target[0]} WHERE id=?`).get(objectId))throw Object.assign(new Error("Linked object not found"),{status:404});const time=now();db.prepare("INSERT OR IGNORE INTO project_links(project_id,object_type,object_id,label,created_at) VALUES(?,?,?,?,?)").run(input.projectId,type,objectId,String(input.label||"").slice(0,100),time);audit(db,actor,"link",input.projectId,`Linked ${type}`);return {projectId:input.projectId,objectType:type,objectId,createdAt:time}}
export function unlinkProject(projectId,type,objectId,db=getDatabase(),actor=null){const changed=db.prepare("DELETE FROM project_links WHERE project_id=? AND object_type=? AND object_id=?").run(projectId,type,objectId).changes;if(!changed)throw Object.assign(new Error("Relationship not found"),{status:404});audit(db,actor,"unlink",projectId,`Unlinked ${type}`);return {ok:true}}
export function saveMilestone(projectId,input,db=getDatabase(),actor=null){project(projectId,db);const id=input.id||randomUUID(),title=String(input.title||"").trim();if(!title||title.length>300)throw new Error("Milestone title is required");const status=["planned","active","completed"].includes(input.status)?input.status:"planned",time=now();db.prepare("INSERT INTO project_milestones(id,project_id,title,due_at,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,due_at=excluded.due_at,status=excluded.status,updated_at=excluded.updated_at").run(id,projectId,title,input.dueAt||null,status,time,time);audit(db,actor,"milestone",projectId,title);return db.prepare("SELECT * FROM project_milestones WHERE id=?").get(id)}
export function saveBlocker(projectId,input,db=getDatabase(),actor=null){project(projectId,db);const id=input.id||randomUUID(),title=String(input.title||"").trim();if(!title||title.length>500)throw new Error("Blocker title is required");const time=now(),resolved=input.resolved?time:null;db.prepare("INSERT INTO project_blockers(id,project_id,title,resolved_at,created_at,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,resolved_at=excluded.resolved_at,updated_at=excluded.updated_at").run(id,projectId,title,resolved,time,time);audit(db,actor,"blocker",projectId,title);return db.prepare("SELECT * FROM project_blockers WHERE id=?").get(id)}
export function projectWorkspace(id,db=getDatabase()){const item=project(id,db),links=db.prepare("SELECT * FROM project_links WHERE project_id=? ORDER BY created_at DESC").all(id).map(link=>{const target=types[link.object_type],row=db.prepare(`SELECT * FROM ${target[0]} WHERE id=?`).get(link.object_id);return {...link,object:row?{...row,display:row[target[1]]}:null}}),ids=[id,...links.map(link=>link.object_id)],marks=ids.map(()=>"?").join(",");return {project:item,links,milestones:db.prepare("SELECT * FROM project_milestones WHERE project_id=? ORDER BY due_at").all(id),blockers:db.prepare("SELECT * FROM project_blockers WHERE project_id=? ORDER BY resolved_at,created_at DESC").all(id),activity:db.prepare(`SELECT * FROM audit_events WHERE object_id IN (${marks}) ORDER BY created_at DESC LIMIT 100`).all(...ids)}}
