import {createHash,randomUUID} from "node:crypto";
import {lstatSync,readFileSync,readdirSync,realpathSync,renameSync,statSync,unlinkSync,writeFileSync} from "node:fs";
import {basename,dirname,isAbsolute,relative,resolve,sep} from "node:path";
import {spawn,spawnSync} from "node:child_process";
import {getDatabase} from "./db.mjs";

const maxFile=512*1024,maxOutput=256*1024,now=()=>new Date().toISOString(),hash=value=>createHash("sha256").update(value).digest("hex");
const commands={status:["git","status","--short","--branch"],diff:["git","diff","--stat","--patch"],test:["npm","test"],build:["npm","run","build"],typecheck:["npx","tsc","--noEmit"]};
const inside=(root,target)=>target===root||target.startsWith(root+sep);
const fail=(message,status=400,code)=>{throw Object.assign(new Error(message),{status,code})};
function allowed(path,roots){const target=realpathSync(resolve(path)),root=roots.map(item=>realpathSync(resolve(item))).find(item=>inside(item,target));if(!root)fail("Repository path is outside LIFEOS_REPOSITORY_ROOTS",403,"PATH_FORBIDDEN");if(!statSync(target).isDirectory())fail("Repository path must be a directory");if(spawnSync("git",["-C",target,"rev-parse","--show-toplevel"],{encoding:"utf8",shell:false}).status!==0)fail("Path is not a Git repository");return target}
function repository(userId,id,db=getDatabase()){const row=db.prepare("SELECT * FROM repositories WHERE id=? AND user_id=?").get(id,userId);if(!row)fail("Repository not found",404);return row}
function target(repoPath,input="",forWrite=false){if(typeof input!=="string"||isAbsolute(input)||input.includes("\0"))fail("Path must be repository-relative");const clean=input.replaceAll("\\","/"),parts=clean.split("/");if(parts.includes(".."))fail("Path traversal is not allowed",403,"PATH_FORBIDDEN");const candidate=resolve(repoPath,clean||".");if(!inside(repoPath,candidate))fail("Path traversal is not allowed",403,"PATH_FORBIDDEN");const existing=forWrite?dirname(candidate):candidate,parent=realpathSync(existing);if(!inside(repoPath,parent))fail("Symlink escape is not allowed",403,"PATH_FORBIDDEN");if(!forWrite&&lstatSync(candidate).isSymbolicLink())fail("Symbolic links cannot be opened",403,"PATH_FORBIDDEN");if(forWrite){try{if(lstatSync(candidate).isSymbolicLink())fail("Symbolic links cannot be edited",403,"PATH_FORBIDDEN")}catch(error){if(error.code!=="ENOENT")throw error}}return candidate}
const fileView=(repoPath,path)=>{const value=readFileSync(target(repoPath,path));if(value.length>maxFile)fail("File exceeds 512 KiB",413);if(value.includes(0))fail("Binary files cannot be edited",415);return {path,content:value.toString("utf8"),hash:hash(value),size:value.length}};
const audit=(db,userId,action,id,summary)=>db.prepare("INSERT INTO audit_events(id,actor_id,action,object_type,object_id,summary,created_at) VALUES(?,?,?,?,?,?,?)").run(randomUUID(),userId,action,"repository",id,summary,now());

export function registerRepository(userId,input,roots,db=getDatabase()){const path=allowed(input.path,roots),name=String(input.name||basename(path)).trim().slice(0,100);if(!name)fail("Repository name is required");const id=randomUUID(),time=now();try{db.prepare("INSERT INTO repositories(id,user_id,name,path,created_at,updated_at) VALUES(?,?,?,?,?,?)").run(id,userId,name,path,time,time)}catch(error){if(String(error.message).includes("UNIQUE"))fail("Repository is already registered",409);throw error}audit(db,userId,"register",id,`Registered repository ${name}`);return repository(userId,id,db)}
export const listRepositories=(userId,db=getDatabase())=>db.prepare("SELECT id,name,path,created_at,updated_at FROM repositories WHERE user_id=? ORDER BY name").all(userId);
export function browseRepository(userId,id,path="",db=getDatabase()){const repo=repository(userId,id,db),absolute=target(repo.path,path),stat=statSync(absolute);if(stat.isFile())return {repository:repo,file:fileView(repo.path,path)};if(!stat.isDirectory())fail("Unsupported filesystem entry");const entries=readdirSync(absolute,{withFileTypes:true}).filter(item=>item.name!==".git"&&!item.isSymbolicLink()).slice(0,500).map(item=>({name:item.name,path:[path,item.name].filter(Boolean).join("/"),type:item.isDirectory()?"directory":item.isFile()?"file":"other",size:item.isFile()?statSync(resolve(absolute,item.name)).size:null}));return {repository:repo,path,entries}}
export function saveFiles(userId,id,changes,db=getDatabase()){const repo=repository(userId,id,db);if(!Array.isArray(changes)||!changes.length||changes.length>50)fail("changes must contain 1-50 files");const prepared=changes.map(change=>{const path=String(change.path||""),content=String(change.content??"");if(!path||Buffer.byteLength(content)>maxFile)fail("Each file needs a path and must be at most 512 KiB");const absolute=target(repo.path,path,true);let before=null;try{before=readFileSync(absolute)}catch(error){if(error.code!=="ENOENT")throw error}const current=before?hash(before):null;if(change.expectedHash!==current)fail(`File changed: ${path}`,409,"VERSION_CONFLICT");return {path,absolute,content,before}});try{for(const item of prepared){const temp=`${item.absolute}.lifeos-${randomUUID()}`;writeFileSync(temp,item.content,{mode:item.before?lstatSync(item.absolute).mode:0o600});renameSync(temp,item.absolute)}}catch(error){for(const item of prepared)try{if(item.before)writeFileSync(item.absolute,item.before);else unlinkSync(item.absolute)}catch{}throw error}audit(db,userId,"edit",id,`Edited ${prepared.length} repository file(s)`);return {files:prepared.map(item=>fileView(repo.path,item.path))}}
function execute(argv,cwd,{timeoutMs=120000,isolate=true}={}){return new Promise((resolvePromise,reject)=>{let command=argv;if(isolate){if(spawnSync("which",["bwrap"],{shell:false}).status!==0)fail("Bubblewrap is required for repository commands",503,"ISOLATION_UNAVAILABLE");command=["bwrap","--unshare-all","--die-with-parent","--ro-bind","/usr","/usr","--ro-bind-try","/lib","/lib","--ro-bind-try","/lib64","/lib64","--ro-bind","/bin","/bin","--proc","/proc","--dev","/dev","--tmpfs","/tmp","--bind",cwd,"/work","--chdir","/work","--",...argv]}const child=spawn(command[0],command.slice(1),{cwd,env:{PATH:process.env.PATH||"/usr/bin:/bin",HOME:"/tmp",LANG:"C.UTF-8"},stdio:["ignore","pipe","pipe"]});let output="",truncated=false,done=false;const collect=chunk=>{const value=chunk.toString();if(Buffer.byteLength(output)+Buffer.byteLength(value)<=maxOutput)output+=value;else truncated=true};child.stdout.on("data",collect);child.stderr.on("data",collect);const timer=setTimeout(()=>child.kill("SIGKILL"),Math.min(Math.max(timeoutMs,1000),120000));child.on("error",error=>{clearTimeout(timer);if(!done){done=true;reject(error)}});child.on("close",code=>{clearTimeout(timer);if(!done){done=true;resolvePromise({exitCode:code,output,truncated})}})})}
export async function runRepositoryCommand(userId,id,commandId,options={},db=getDatabase()){const repo=repository(userId,id,db),argv=commands[commandId];if(!argv)fail("Command is not allowlisted");const runId=randomUUID(),started=now();db.prepare("INSERT INTO repository_command_runs(id,repository_id,user_id,command_id,command_text,state,started_at) VALUES(?,?,?,?,?,'running',?)").run(runId,id,userId,commandId,argv.join(" "),started);try{const result=await execute(argv,repo.path,options),finished=now();db.prepare("UPDATE repository_command_runs SET state='finished',exit_code=?,output=?,truncated=?,finished_at=? WHERE id=?").run(result.exitCode,result.output,result.truncated?1:0,finished,runId);audit(db,userId,"command",id,`Ran allowlisted command: ${commandId}`);return {id:runId,commandId,state:"finished",...result,startedAt:started,finishedAt:finished}}catch(error){db.prepare("UPDATE repository_command_runs SET state='failed',output=?,finished_at=? WHERE id=?").run(String(error.message),now(),runId);throw error}}
export function repositoryGit(userId,id,db=getDatabase()){const repo=repository(userId,id,db),run=args=>spawnSync("git",["-C",repo.path,...args],{encoding:"utf8",shell:false,maxBuffer:maxOutput});return {status:run(["status","--short","--branch"]).stdout,diff:run(["diff","--stat","--patch"]).stdout,history:run(["log","-20","--pretty=format:%h%x09%aI%x09%s"]).stdout.split("\n").filter(Boolean).map(line=>{const [ref,date,...subject]=line.split("\t");return {ref,date,subject:subject.join("\t")}})}}
export function mutateGit(userId,id,input,db=getDatabase()){const repo=repository(userId,id,db);let args;if(input.action==="commit"){const message=String(input.message||"").trim();if(!message||message.length>200)fail("Commit message is required and must be at most 200 characters");if(!Array.isArray(input.paths)||!input.paths.length||input.paths.length>100)fail("Commit paths are required");const paths=input.paths.map(path=>{target(repo.path,String(path),true);return String(path)});let result=spawnSync("git",["-C",repo.path,"add","--",...paths],{encoding:"utf8",shell:false});if(result.status===0)result=spawnSync("git",["-C",repo.path,"commit","-m",message,"--",...paths],{encoding:"utf8",shell:false});if(result.status!==0)fail(result.stderr||result.stdout||"Git commit failed",409);audit(db,userId,"commit",id,message);return {ok:true,output:result.stdout}}if(input.action==="revert"){const ref=String(input.ref||"");if(!/^[0-9a-f]{7,40}$/i.test(ref))fail("A full or abbreviated commit hash is required");const result=spawnSync("git",["-C",repo.path,"revert","--no-edit",ref],{encoding:"utf8",shell:false});if(result.status!==0)fail(result.stderr||result.stdout||"Git revert failed",409);audit(db,userId,"revert",id,`Reverted ${ref}`);return {ok:true,output:result.stdout}}fail("Unsupported Git action")}
export const approvalAction=(id,input)=>input.action==="edit"?{repositoryId:id,changes:input.changes}:input.action==="command"?{repositoryId:id,commandId:input.commandId}:{repositoryId:id,...input};
