import {randomUUID} from "node:crypto";
import {getDatabase} from "./db.mjs";

const defaults={profile:{name:""},preferences:{startPage:"Today",weekStartsOn:"Monday",compactLists:false},notifications:{push:true,reminders:true,jobFailures:true},agentPermissions:{readNotes:true,createDrafts:true,runCode:false,sensitiveActions:false},calendar:{timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC",selectedCalendars:[]},backup:{enabled:false,retentionDays:14},ai:{profile:"fast"}};
const fields={profile:["name"],preferences:["startPage","weekStartsOn","compactLists"],notifications:["push","reminders","jobFailures"],agentPermissions:["readNotes","createDrafts","runCode","sensitiveActions"],calendar:["timezone","selectedCalendars"],backup:["enabled","retentionDays"],ai:["profile"]};
const stamp=()=>new Date().toISOString(),parse=value=>{try{return JSON.parse(value||"{}")}catch{return {}}};
function clean(section,value){if(!value||typeof value!=="object"||Array.isArray(value))throw new Error(`${section} must be an object`);const result={};for(const key of fields[section])if(key in value)result[key]=value[key];if(section==="profile"&&result.name!==undefined){result.name=String(result.name).trim().slice(0,100)}if(section==="ai"&&result.profile!==undefined&&!['fast','balanced','quality'].includes(result.profile))throw new Error("Invalid AI profile");if(section==="preferences"&&result.startPage!==undefined&&!['Today','Capture','Tasks','Calendar','Vault'].includes(result.startPage))throw new Error("Invalid start page");if(section==="preferences"&&result.weekStartsOn!==undefined&&!['Monday','Sunday'].includes(result.weekStartsOn))throw new Error("Invalid first weekday");if(section==="calendar"&&result.selectedCalendars!==undefined){if(!Array.isArray(result.selectedCalendars)||result.selectedCalendars.length>50)throw new Error("Invalid selected calendars");result.selectedCalendars=result.selectedCalendars.map(String)}if(section==="backup"&&result.retentionDays!==undefined&&(!Number.isInteger(result.retentionDays)||result.retentionDays<1||result.retentionDays>365))throw new Error("Backup retention must be 1-365 days");return result}
export function getSettings(userId,db=getDatabase()){let row=db.prepare("SELECT * FROM user_settings WHERE user_id=?").get(userId);if(!row){db.prepare("INSERT INTO user_settings(user_id,updated_at) VALUES(?,?)").run(userId,stamp());row=db.prepare("SELECT * FROM user_settings WHERE user_id=?").get(userId)}return Object.fromEntries(Object.keys(fields).map(section=>[section,{...defaults[section],...parse(row[`${section.replace(/[A-Z]/g,m=>`_${m.toLowerCase()}`)}_json`])}]).concat([["version",row.version],["updatedAt",row.updated_at]]))}
export function saveSettings(userId,input,db=getDatabase()){const current=getSettings(userId,db);if(input.version!==current.version)throw Object.assign(new Error("Settings changed in another session"),{status:409,code:"VERSION_CONFLICT"});const next={};for(const section of Object.keys(fields))next[section]={...current[section],...(section in input?clean(section,input[section]):{})};const time=stamp(),columns=Object.keys(fields).map(section=>`${section.replace(/[A-Z]/g,m=>`_${m.toLowerCase()}`)}_json=?`).join(","),result=db.prepare(`UPDATE user_settings SET ${columns},updated_at=?,version=version+1 WHERE user_id=? AND version=?`).run(...Object.keys(fields).map(section=>JSON.stringify(next[section])),time,userId,current.version);if(!result.changes)throw Object.assign(new Error("Settings changed in another session"),{status:409,code:"VERSION_CONFLICT"});db.prepare("INSERT INTO audit_events(id,actor_id,action,object_type,object_id,summary,created_at) VALUES(?,?,?,?,?,?,?)").run(randomUUID(),userId,"update","settings",userId,"Updated account settings",time);return getSettings(userId,db)}
