import {randomUUID} from "node:crypto";
import {resolve} from "node:path";
import {getDatabase} from "./db.mjs";
import {ensureDataDirs,loadConfig} from "./config.mjs";
import {runAI} from "./ai.mjs";
import {saveNote} from "./core.mjs";

const common="Preserve the user's language. Be concise, concrete, and source-grounded. Never claim an action was performed when it was only proposed.";
const definitions={
  "process-inbox":{mode:"proposal",description:"Turn unprocessed captures into proposed tasks, events, or notes.",instructions:"Classify each capture. When uncertain, propose a note tagged needs-filing. Preserve source text."},
  research:{mode:"proposal",description:"Assess an idea and draft a structured research note.",instructions:"Assess demand, competition, feasibility, differentiation, and next steps. Return a sourced note proposal."},
  "weekly-review":{mode:"proposal",description:"Summarize the last week and propose next-week focuses.",instructions:"Summarize recent notes, open tasks, captures, and three realistic focuses."},
  "refresh-home":{mode:"proposal",description:"Propose a concise, link-rich Home note.",instructions:"Use only domains and notes present in the supplied context. Propose Home.md content."},
  assistant:{mode:"read",description:"Answer questions using Noema context.",instructions:"Act as a read-only personal assistant. Cite relevant note titles."},
  "note-tutor":{mode:"read",description:"Teach from one open note and related notes.",instructions:"Explain step by step. Use Markdown and LaTeX. Cite related notes only when useful."},
  "code-tutor":{mode:"read",description:"Explain and improve the open code buffer.",instructions:"Explain bugs and logic. Return an exact replacement only when a concrete edit helps."},
  "note-augment":{mode:"proposal",description:"Draft an additive study section for an open note.",instructions:"Draft a self-contained Markdown section with a heading, key ideas, LaTeX, and an example. Never remove existing content."},
  "semantic-search":{mode:"read",description:"Find notes by meaning rather than literal keywords.",instructions:"Return only genuinely relevant note citations, ranked by relevance."},
  autosort:{mode:"proposal",description:"Propose safe vault organization changes.",instructions:"Propose moves only. Never modify data. Exclude infrastructure and already-organized content."},
};

export const listSkills=()=>Object.entries(definitions).map(([id,value])=>({id,...value}));
export function getSkill(id){const skill=definitions[id];if(!skill)throw Object.assign(new Error("Unknown skill"),{status:404});return {id,...skill}}
export const workloadForSkill=id=>({assistant:"simple","weekly-review":"schedule","refresh-home":"simple",autosort:"simple",research:"research","code-tutor":"code"}[id]||"note");
export function buildSkillPrompt(id,input,context=""){const skill=getSkill(id);return `You are running the managed Noema skill \"${id}\".\n${skill.instructions}\n${common}\n\nNoema context:\n${context||"No additional context."}\n\nUser input:\n${JSON.stringify(input)}`}

const tutorSchema={type:"object",additionalProperties:false,required:["answer","citations","replacement"],properties:{answer:{type:"string",minLength:1,maxLength:12000},citations:{type:"array",maxItems:8,items:{type:"string",maxLength:500}},replacement:{type:"string",maxLength:50000}}};
const tutorMessages=(sessionId,db)=>db.prepare("SELECT id,role,content AS text,citations_json,replacement,provider,inserted_note_id AS insertedNoteId,inserted_note_version AS insertedNoteVersion,created_at AS createdAt FROM tutor_messages WHERE session_id=? ORDER BY created_at").all(sessionId).map(message=>({...message,citations:JSON.parse(message.citations_json)}));
export function loadTutorSession(kind,subjectId,db=getDatabase(),workspaceId=null){if(kind==="note"&&!db.prepare(`SELECT id FROM notes WHERE id=? AND trashed=0${workspaceId?" AND workspace_id=?":""}`).get(subjectId,...(workspaceId?[workspaceId]:[])))throw Object.assign(new Error("Note not found"),{status:404});const session=db.prepare(`SELECT * FROM tutor_sessions WHERE kind=? AND subject_id=?${workspaceId?" AND workspace_id=?":""} ORDER BY updated_at DESC LIMIT 1`).get(kind,subjectId,...(workspaceId?[workspaceId]:[]));return session?{sessionId:session.id,messages:tutorMessages(session.id,db)}:{sessionId:null,messages:[]}}
export async function runTutor(input,config=ensureDataDirs(loadConfig()),db=getDatabase(config),workspaceId=null){
  const subjectKind=input.kind==="code"?"code":"note",kind=subjectKind==="code"?"code-tutor":"note-tutor",subjectId=String(input.id||input.name||"untitled").slice(0,500),note=subjectKind==="note"?db.prepare(`SELECT * FROM notes WHERE id=? AND trashed=0${workspaceId?" AND workspace_id=?":""}`).get(subjectId,...(workspaceId?[workspaceId]:[])):null;if(subjectKind==="note"&&!note)throw Object.assign(new Error("Note not found"),{status:404});const title=String(note?.title||input.title||input.name||"Untitled").slice(0,300),time=new Date().toISOString();let session=input.sessionId&&db.prepare(`SELECT * FROM tutor_sessions WHERE id=? AND kind=? AND subject_id=?${workspaceId?" AND workspace_id=?":""}`).get(input.sessionId,subjectKind,subjectId,...(workspaceId?[workspaceId]:[]));if(input.sessionId&&!session)throw Object.assign(new Error("Tutor session not found"),{status:404});if(!session){const id=randomUUID();db.prepare("INSERT INTO tutor_sessions(id,kind,subject_id,subject_title,created_at,updated_at,workspace_id) VALUES(?,?,?,?,?,?,?)").run(id,subjectKind,subjectId,title,time,time,workspaceId);session={id}}
  const subject=kind==="code-tutor"?`File: ${title}\nLanguage: ${String(input.language||"unknown").slice(0,50)}\nCode:\n${String(input.code||"").slice(0,50000)}`:`Note: ${title}\nContent:\n${String(note.content).slice(0,50000)}`;
  const related=kind==="note-tutor"?db.prepare(`SELECT title,excerpt FROM notes WHERE trashed=0 AND id<>?${workspaceId?" AND workspace_id=?":""} ORDER BY updated_at DESC LIMIT 8`).all(subjectId,...(workspaceId?[workspaceId]:[])).map(note=>`- [[${note.title}]]: ${note.excerpt}`).join("\n"):"";
  const question=String(input.question||"").slice(0,4000),math=/\b(math|algebra|calculus|equation|proof|derivative|integral|matrix|handwritten)\b|[∫∑√]/i.test(`${subject}\n${question}`);
  db.prepare("INSERT INTO tutor_messages(id,session_id,role,content,created_at) VALUES(?,?,?,?,?)").run(randomUUID(),session.id,"user",question,time);const messages=tutorMessages(session.id,db).slice(-8).map(({role,text})=>({role,text}));
  const prompt=buildSkillPrompt(kind,{subject,messages,question},related),output=await runAI({prompt,cwd:resolve(config.jobsDir,`tutor-${randomUUID()}`),schema:tutorSchema,config,workload:math?"math":workloadForSkill(kind)}),messageId=randomUUID();db.prepare("INSERT INTO tutor_messages(id,session_id,role,content,citations_json,replacement,provider,created_at) VALUES(?,?,?,?,?,?,?,?)").run(messageId,session.id,"assistant",output.result.answer,JSON.stringify(output.result.citations),output.result.replacement||null,output.provider,new Date().toISOString());db.prepare("UPDATE tutor_sessions SET updated_at=? WHERE id=?").run(new Date().toISOString(),session.id);return {...output.result,provider:output.provider,messageId,sessionId:session.id};
}

export function insertTutorMessage(messageId,noteId,db=getDatabase(),actor=null){const workspaceId=typeof actor==="object"&&actor?actor.workspaceId:null,message=db.prepare(`SELECT m.*,s.kind,s.subject_id FROM tutor_messages m JOIN tutor_sessions s ON s.id=m.session_id WHERE m.id=? AND m.role='assistant'${workspaceId?" AND s.workspace_id=?":""}`).get(messageId,...(workspaceId?[workspaceId]:[]));if(!message||message.kind!=="note"||message.subject_id!==noteId)throw Object.assign(new Error("Tutor message not found for this note"),{status:404});if(message.inserted_note_id)throw Object.assign(new Error("Tutor message was already inserted"),{status:409});const note=db.prepare(`SELECT * FROM notes WHERE id=? AND trashed=0${workspaceId?" AND workspace_id=?":""}`).get(noteId,...(workspaceId?[workspaceId]:[]));if(!note)throw Object.assign(new Error("Note not found"),{status:404});db.exec("BEGIN IMMEDIATE");try{const content=`${note.content.trim()}\n\n${message.content.trim()}\n`,saved=saveNote({id:note.id,title:note.title,content,tags:JSON.parse(note.tags_json),ai:true,draft:!!note.draft,source:note.source,favorite:!!note.favorite,trashed:false,version:note.version},db,actor);db.prepare("UPDATE tutor_messages SET inserted_note_id=?,inserted_note_version=? WHERE id=? AND inserted_note_id IS NULL").run(noteId,saved.version,messageId);db.exec("COMMIT");return {noteId,content:saved.content,version:saved.version,provider:message.provider}}catch(error){db.exec("ROLLBACK");throw error}}

export const skillSchema={type:"object",additionalProperties:false,required:["summary","proposals","citations"],properties:{summary:{type:"string",maxLength:4000},proposals:{type:"array",maxItems:30,items:{type:"object",additionalProperties:false,required:["type","title","content"],properties:{type:{enum:["note","task","event","move","answer"]},title:{type:"string",maxLength:500},content:{type:"string",maxLength:20000}}}},citations:{type:"array",maxItems:20,items:{type:"string",maxLength:500}}}};
