import {createHash,randomUUID} from "node:crypto";
import {existsSync,mkdirSync,readFileSync,readdirSync,realpathSync,renameSync,statSync,writeFileSync} from "node:fs";
import {basename,dirname,extname,isAbsolute,join,normalize,relative,resolve,sep} from "node:path";
import {saveNote,saveTask} from "./core.mjs";
import {getDatabase} from "./db.mjs";
import {enqueueJob} from "./jobs.mjs";

const now=()=>new Date().toISOString(),hash=value=>createHash("sha256").update(value).digest("hex");
const fail=(message,status=400)=>Object.assign(new Error(message),{status});
export function safeRelativePath(value){const path=String(value||"").replaceAll("\\","/");if(!path||path.startsWith("/")||path.includes("\0")||path.split("/").some(part=>!part||part==="."||part===".."))throw fail("Invalid vault path");return path}
export function vaultPath(root,value,{mustExist=false}={}){const rel=safeRelativePath(value),base=realpathSync(root),target=resolve(base,rel);if(target!==base&&!target.startsWith(base+sep))throw fail("Vault path escapes its source");if(mustExist){const actual=realpathSync(target);if(actual!==target||!actual.startsWith(base+sep))throw fail("Vault symlinks are not allowed")}return target}
function markdownFiles(root,dir=root){return readdirSync(dir,{withFileTypes:true}).flatMap(entry=>entry.isSymbolicLink()||[".obsidian",".git",".trash"].includes(entry.name)?[]:entry.isDirectory()?markdownFiles(root,join(dir,entry.name)):entry.isFile()&&extname(entry.name).toLowerCase()===".md"?[relative(root,join(dir,entry.name)).replaceAll("\\","/")]:[])}
function title(content,path){return content.match(/^---\r?\n[\s\S]*?^title:\s*["']?(.+?)["']?\s*$[\s\S]*?^---$/mi)?.[1]||content.match(/^#\s+(.+)$/m)?.[1]||basename(path,".md")}
function tags(content){const raw=content.match(/^---\r?\n[\s\S]*?^tags:\s*(.+?)\s*$[\s\S]*?^---$/mi)?.[1];return raw?raw.replace(/^\[|\]$/g,"").split(",").map(v=>v.trim().replace(/^['"]|['"]$/g,"")).filter(Boolean):[]}
function atomicWrite(path,content){mkdirSync(dirname(path),{recursive:true});const temporary=join(dirname(path),`.${basename(path)}.${randomUUID()}.tmp`);writeFileSync(temporary,content,{encoding:"utf8",mode:0o600,flag:"wx"});renameSync(temporary,path)}
function sourceRow(sourceId,workspaceId,db){const row=db.prepare("SELECT * FROM vault_sources WHERE id=? AND workspace_id=?").get(sourceId,workspaceId);if(!row)throw fail("Vault source not found",404);return row}
export function connectVault({rootPath,name="Obsidian",taskFolders=["TODO/"]},workspaceId,db=getDatabase()){if(!isAbsolute(rootPath))throw fail("Vault root must be absolute");const root=realpathSync(rootPath);if(!statSync(root).isDirectory())throw fail("Vault root must be a directory");const folders=taskFolders.map(v=>safeRelativePath(String(v).replace(/\/$/,""))+"/");const existing=db.prepare("SELECT * FROM vault_sources WHERE workspace_id=? AND root_path=?").get(workspaceId,root),time=now(),id=existing?.id||randomUUID();if(existing)db.prepare("UPDATE vault_sources SET name=?,task_folders_json=?,state='connected',updated_at=? WHERE id=?").run(name,JSON.stringify(folders),time,id);else db.prepare("INSERT INTO vault_sources(id,workspace_id,name,root_path,task_folders_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?)").run(id,workspaceId,name,root,JSON.stringify(folders),time,time);return getVaultSource(id,workspaceId,db)}
export function getVaultSource(id,workspaceId,db=getDatabase()){const row=sourceRow(id,workspaceId,db);return {...row,taskFolders:JSON.parse(row.task_folders_json),lastResult:row.last_result_json?JSON.parse(row.last_result_json):null}}
export function listVaultSources(workspaceId,db=getDatabase()){return db.prepare("SELECT id FROM vault_sources WHERE workspace_id=? ORDER BY name").all(workspaceId).map(row=>getVaultSource(row.id,workspaceId,db))}
export function updateVaultSource(id,input,workspaceId,db=getDatabase()){const source=sourceRow(id,workspaceId,db),name=String(input.name||source.name).trim();if(!name||name.length>200)throw fail("Vault source name is required");const folders=(input.taskFolders??JSON.parse(source.task_folders_json)).map(value=>safeRelativePath(String(value).replace(/\/$/,""))+"/");db.prepare("UPDATE vault_sources SET name=?,task_folders_json=?,updated_at=? WHERE id=?").run(name,JSON.stringify([...new Set(folders)]),now(),id);return getVaultSource(id,workspaceId,db)}
export function createVaultNote(sourceId,input,actor,db=getDatabase()){const source=sourceRow(sourceId,actor.workspaceId,db),relativePath=safeRelativePath(String(input.relativePath||""));if(extname(relativePath).toLowerCase()!==".md")throw fail("Vault note path must end in .md");const path=vaultPath(source.root_path,relativePath);if(existsSync(path))throw fail("Vault note already exists",409);const heading=basename(relativePath,".md").replaceAll("-"," "),content=String(input.content||`# ${heading}\n\n`);if(Buffer.byteLength(content)>2_000_000)throw fail("Vault note is too large");atomicWrite(path,content);scanVault(sourceId,actor,db);const entry=db.prepare("SELECT note_id FROM vault_entries WHERE source_id=? AND relative_path=? AND deleted_at IS NULL").get(sourceId,relativePath);return {noteId:entry.note_id,relativePath}}
export function vaultTree(sourceId,workspaceId,db=getDatabase()){sourceRow(sourceId,workspaceId,db);const entries=db.prepare("SELECT relative_path,note_id,sync_state FROM vault_entries WHERE source_id=? AND deleted_at IS NULL ORDER BY relative_path").all(sourceId),root={name:"",path:"",folders:[],notes:[]};for(const entry of entries){const parts=entry.relative_path.split("/"),file=parts.pop();let node=root,path="";for(const part of parts){path=path?`${path}/${part}`:part;let next=node.folders.find(folder=>folder.name===part);if(!next){next={name:part,path,folders:[],notes:[]};node.folders.push(next)}node=next}node.notes.push({name:file,path:entry.relative_path,noteId:entry.note_id,syncState:entry.sync_state})}return root}
export function scanVault(sourceId,actor,db=getDatabase()){
  const source=sourceRow(sourceId,actor.workspaceId,db),seen=new Set(),seenTaskLinks=new Set(),result={created:0,updated:0,written:0,unchanged:0,conflicts:0,tasks:0,removedTasks:0};
  for(const rel of markdownFiles(source.root_path)){seen.add(rel);const path=vaultPath(source.root_path,rel,{mustExist:true}),vaultContent=readFileSync(path,"utf8"),vaultHash=hash(vaultContent);let entry=db.prepare("SELECT * FROM vault_entries WHERE source_id=? AND relative_path=?").get(sourceId,rel);
    if(!entry){const mapped=db.prepare("SELECT * FROM notes WHERE workspace_id=? AND source=?").get(actor.workspaceId,`Obsidian · ${rel}`),note=mapped||saveNote({title:title(vaultContent,rel),content:vaultContent,tags:tags(vaultContent),source:`Obsidian · ${rel}`},db,actor),time=now();db.prepare("INSERT INTO vault_entries(id,source_id,relative_path,parent_path,note_id,vault_hash,noema_hash,last_common_content,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)").run(randomUUID(),sourceId,rel,dirname(rel)==="."?"":dirname(rel),note.id,vaultHash,hash(vaultContent),vaultContent,time,time);result.created++;
    }else{const note=db.prepare("SELECT * FROM notes WHERE id=? AND workspace_id=?").get(entry.note_id,actor.workspaceId),vaultChanged=vaultHash!==entry.vault_hash,noemaChanged=note&&hash(note.content)!==entry.noema_hash;
      if(vaultChanged&&noemaChanged){if(!db.prepare("SELECT 1 FROM vault_conflicts WHERE entry_id=? AND state='open'").get(entry.id))db.prepare("INSERT INTO vault_conflicts(id,entry_id,vault_content,noema_content,base_content,created_at) VALUES(?,?,?,?,?,?)").run(randomUUID(),entry.id,vaultContent,note.content,entry.last_common_content,now());db.prepare("UPDATE vault_entries SET sync_state='conflict',updated_at=? WHERE id=?").run(now(),entry.id);result.conflicts++}
      else if(vaultChanged){saveNote({id:note.id,title:title(vaultContent,rel),content:vaultContent,tags:tags(vaultContent),source:`Obsidian · ${rel}`,version:note.version},db,actor);db.prepare("UPDATE vault_entries SET vault_hash=?,noema_hash=?,last_common_content=?,sync_state='synced',updated_at=? WHERE id=?").run(vaultHash,vaultHash,vaultContent,now(),entry.id);result.updated++}
      else if(noemaChanged){atomicWrite(path,note.content);const next=hash(note.content);db.prepare("UPDATE vault_entries SET vault_hash=?,noema_hash=?,last_common_content=?,sync_state='synced',updated_at=? WHERE id=?").run(next,next,note.content,now(),entry.id);result.written++}else result.unchanged++;
    }
    result.tasks+=syncTasks(source,rel,db,actor,seenTaskLinks);
    db.prepare("INSERT INTO vault_sync_manifests(source_id,relative_path,sha256,scanned_at) VALUES(?,?,?,?) ON CONFLICT(source_id,relative_path) DO UPDATE SET sha256=excluded.sha256,scanned_at=excluded.scanned_at").run(sourceId,rel,vaultHash,now());
  }
  for(const link of db.prepare("SELECT task_id,relative_path,block_id FROM vault_task_links WHERE source_id=?").all(sourceId))if(!seenTaskLinks.has(`${link.relative_path}\0${link.block_id}`)){db.prepare("UPDATE tasks SET archived=1,status='cancelled',updated_at=?,version=version+1 WHERE id=? AND archived=0").run(now(),link.task_id);db.prepare("UPDATE vault_task_links SET line_number=0,updated_at=? WHERE task_id=?").run(now(),link.task_id);result.removedTasks++}
  for(const entry of db.prepare("SELECT id,relative_path FROM vault_entries WHERE source_id=? AND deleted_at IS NULL").all(sourceId))if(!seen.has(entry.relative_path))db.prepare("UPDATE vault_entries SET sync_state='missing',deleted_at=?,updated_at=? WHERE id=?").run(now(),now(),entry.id);
  db.prepare("UPDATE vault_sources SET state='connected',last_sync_at=?,last_result_json=?,updated_at=? WHERE id=?").run(now(),JSON.stringify(result),now(),sourceId);return result;
}
const months={jan:0,january:0,feb:1,february:1,mar:2,march:2,apr:3,april:3,may:4,jun:5,june:5,jul:6,july:6,aug:7,august:7,sep:8,september:8,oct:9,october:9,nov:10,november:10,dec:11,december:11};
export function parseVaultTask(line,path,currentYear=new Date().getFullYear()){
  const match=line.match(/^(\s*- \[([ xX])\]\s+)(.*?)\s*$/);if(!match)return null;let text=match[3],block=text.match(/(?:^|\s)\^([A-Za-z0-9-]+)$/),reminder=null,dueAt=null,scheduledStartAt=null;if(block)text=text.slice(0,block.index).trim();
  const date=text.match(/(?:^|\s)(\d{1,2})\s+([A-Za-z]{3,9})(?:\s+(\d{4}))?(?:\s+(\d{1,2}):(\d{2}))?(?=\s|$)/),month=date&&months[date[2].toLowerCase()];
  if(date&&month!==undefined){const pathYear=path.match(/(?:^|\/)((?:19|20)\d{2})(?:\/|$)/)?.[1],year=Number(date[3]||pathYear||currentYear),day=Number(date[1]),hour=Number(date[4]||0),minute=Number(date[5]||0),iso=`${year}-${String(month+1).padStart(2,"0")}-${String(day).padStart(2,"0")}T${String(hour).padStart(2,"0")}:${String(minute).padStart(2,"0")}:00+07:00`,value=new Date(iso),parts=Number.isNaN(value.getTime())?null:Object.fromEntries(new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Jakarta",year:"numeric",month:"numeric",day:"numeric",hour:"numeric",minute:"numeric",hourCycle:"h23"}).formatToParts(value).map(part=>[part.type,Number(part.value)]));if(parts&&parts.year===year&&parts.month===month+1&&parts.day===day&&parts.hour===hour&&parts.minute===minute){dueAt=value.toISOString();scheduledStartAt=date[4]?dueAt:null;text=(text.slice(0,date.index)+" "+text.slice(date.index+date[0].length)).trim()}}
  const remind=text.match(/(?:^|\s)#remind(\d+)(?=\s|$)/i),minutes=remind&&Number(remind[1]);if(dueAt&&remind&&Number.isInteger(minutes)&&minutes>=0&&minutes<=525600){reminder=minutes;text=text.replace(remind[0]," ").trim()}
  const taskTitle=text.replace(/\s+/g," ").trim();if(!taskTitle)return null;
  return {completed:match[2].toLowerCase()==="x",title:taskTitle,blockId:block?.[1]||null,dueAt,scheduledStartAt,reminderMinutes:reminder,prefix:match[1]}}
function syncTasks(source,rel,db,actor,seenTaskLinks){if(!JSON.parse(source.task_folders_json).some(folder=>rel.startsWith(folder)))return 0;const path=vaultPath(source.root_path,rel,{mustExist:true});let content=readFileSync(path,"utf8"),eol=content.includes("\r\n")?"\r\n":"\n",lines=content.split(/\r?\n/),changed=false,count=0;for(let index=0;index<lines.length;index++){const parsed=parseVaultTask(lines[index],rel);if(!parsed)continue;let blockId=parsed.blockId;if(!blockId){blockId=`noema-${hash(`${rel}:${lines[index]}:${index}`).slice(0,12)}`;lines[index]+=` ^${blockId}`;changed=true}let existing=db.prepare("SELECT * FROM vault_task_links WHERE source_id=? AND relative_path=? AND block_id=?").get(source.id,rel,blockId)||db.prepare("SELECT * FROM vault_task_links WHERE source_id=? AND block_id=?").get(source.id,blockId);if(existing&&existing.relative_path!==rel){db.prepare("UPDATE vault_task_links SET relative_path=? WHERE source_id=? AND relative_path=? AND block_id=?").run(rel,source.id,existing.relative_path,blockId);existing={...existing,relative_path:rel}}seenTaskLinks.add(`${rel}\0${blockId}`);const taskId=existing?.task_id||randomUUID(),fingerprint=hash(lines[index]),reminderAt=parsed.reminderMinutes!=null&&(parsed.scheduledStartAt||parsed.dueAt)?new Date(new Date(parsed.scheduledStartAt||parsed.dueAt).getTime()-parsed.reminderMinutes*60000).toISOString():null,old=existing&&db.prepare("SELECT * FROM tasks WHERE id=?").get(taskId);if(!old||existing.source_fingerprint!==fingerprint||old.archived){saveTask({id:taskId,title:parsed.title,project:parsed.dueAt?"Obsidian":"Inbox",due:parsed.dueAt||"Someday",dueAt:parsed.dueAt,scheduledStartAt:parsed.scheduledStartAt,completed:parsed.completed,reminderAt,archived:false,version:old?.version},db,{...actor,skipVaultWriteback:true});db.prepare("INSERT INTO vault_task_links(source_id,relative_path,block_id,task_id,source_fingerprint,last_representation,line_number,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(source_id,relative_path,block_id) DO UPDATE SET task_id=excluded.task_id,source_fingerprint=excluded.source_fingerprint,last_representation=excluded.last_representation,line_number=excluded.line_number,updated_at=excluded.updated_at").run(source.id,rel,blockId,taskId,fingerprint,lines[index],index+1,now());count++}}
  if(changed)atomicWrite(path,lines.join(eol));return count}
export function listConflicts(sourceId,workspaceId,db=getDatabase()){sourceRow(sourceId,workspaceId,db);return db.prepare("SELECT c.*,e.relative_path FROM vault_conflicts c JOIN vault_entries e ON e.id=c.entry_id WHERE e.source_id=? AND c.state='open' ORDER BY c.created_at").all(sourceId)}
export function resolveConflict(id,resolution,actor,db=getDatabase()){if(!["vault","noema"].includes(resolution))throw fail("Resolution must be vault or noema");const row=db.prepare("SELECT c.*,e.relative_path,e.note_id,s.root_path FROM vault_conflicts c JOIN vault_entries e ON e.id=c.entry_id JOIN vault_sources s ON s.id=e.source_id WHERE c.id=? AND s.workspace_id=? AND c.state='open'").get(id,actor.workspaceId);if(!row)throw fail("Vault conflict not found",404);const content=resolution==="vault"?row.vault_content:row.noema_content,note=db.prepare("SELECT * FROM notes WHERE id=?").get(row.note_id);if(resolution==="vault")saveNote({id:note.id,title:title(content,row.relative_path),content,tags:tags(content),source:`Obsidian · ${row.relative_path}`,version:note.version},db,actor);else atomicWrite(vaultPath(row.root_path,row.relative_path),content);const digest=hash(content);db.prepare("UPDATE vault_entries SET vault_hash=?,noema_hash=?,last_common_content=?,sync_state='synced',updated_at=? WHERE id=?").run(digest,digest,content,now(),row.entry_id);db.prepare("UPDATE vault_conflicts SET state='resolved',resolution=?,resolved_at=? WHERE id=?").run(resolution,now(),id);return {id,resolution}}
export function validateStrokes(input){const width=Number(input.width),height=Number(input.height),strokes=input.strokes;if(!Number.isFinite(width)||!Number.isFinite(height)||width<1||height<1||width>10000||height>10000)throw fail("Invalid ink dimensions");if(!Array.isArray(strokes)||strokes.length>2000)throw fail("Invalid stroke count");let points=0;for(const stroke of strokes){if(!Array.isArray(stroke.points)||!stroke.points.length||stroke.points.length>10000)throw fail("Invalid stroke points");if(!["pen","highlighter","eraser"].includes(stroke.tool))throw fail("Invalid stroke tool");for(const point of stroke.points){points++;for(const key of ["x","y","pressure","time"]){if(!Number.isFinite(point[key]))throw fail("Invalid stroke point")}if(point.x<0||point.x>width||point.y<0||point.y>height||point.pressure<0||point.pressure>1)throw fail("Stroke point out of bounds")}}const json=JSON.stringify(strokes);if(points>100000||Buffer.byteLength(json)>5_000_000)throw fail("Ink payload too large");return {width,height,strokes,json}}
export function strokesToSvg(input){const {width,height,strokes}=validateStrokes(input),paths=strokes.filter(s=>s.tool!=="eraser").map(stroke=>{const color=/^#[0-9a-f]{6}$/i.test(stroke.color)?stroke.color:"#111827",opacity=stroke.tool==="highlighter"?.35:1,line=stroke.points.map((p,i)=>`${i?"L":"M"}${p.x.toFixed(2)} ${p.y.toFixed(2)}`).join(" "),strokeWidth=Math.min(100,Math.max(.25,Number(stroke.width)||2));return `<path d="${line}" fill="none" stroke="${color}" stroke-width="${strokeWidth}" stroke-linecap="round" stroke-linejoin="round" opacity="${opacity}"/>`}).join("");return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}">${paths}</svg>`}
const inkMarker=id=>`<!-- noema:ink:${id} -->\n![[Attachments/Noema Ink/${id}.svg]]\n<!-- /noema:ink:${id} -->`;
function ensureNoteBlocks(noteId,db){if(db.prepare("SELECT 1 FROM note_blocks WHERE note_id=? LIMIT 1").get(noteId))return;const note=db.prepare("SELECT content FROM notes WHERE id=?").get(noteId),time=now();db.prepare("INSERT INTO note_blocks(id,note_id,position,kind,markdown,created_at,updated_at) VALUES(?,?,?,?,?,?,?)").run(randomUUID(),noteId,0,"markdown",note?.content||"",time,time)}
function projection(noteId,db){return db.prepare("SELECT id,kind,markdown FROM note_blocks WHERE note_id=? ORDER BY position").all(noteId).map(block=>block.kind==="ink"?inkMarker(block.id):block.markdown).filter(Boolean).join("\n\n")}
function writeBlockProjection(noteId,actor,db){const note=db.prepare("SELECT * FROM notes WHERE id=? AND workspace_id=?").get(noteId,actor.workspaceId),entry=db.prepare("SELECT e.*,s.root_path FROM vault_entries e JOIN vault_sources s ON s.id=e.source_id WHERE e.note_id=? AND s.workspace_id=?").get(noteId,actor.workspaceId);if(!note||!entry)throw fail("Ink blocks require a vault-backed note",409);if(entry.sync_state==="conflict")throw fail("Resolve the vault conflict before editing blocks",409);const content=projection(noteId,db),path=vaultPath(entry.root_path,entry.relative_path,{mustExist:true});atomicWrite(path,content);const digest=hash(content),time=now();db.prepare("UPDATE notes SET content=?,excerpt=?,updated_at=?,version=version+1 WHERE id=?").run(content,content.replace(/[#*_>!-]/g,"").trim().slice(0,140),time,noteId);db.prepare("UPDATE vault_entries SET vault_hash=?,noema_hash=?,last_common_content=?,sync_state='synced',updated_at=? WHERE id=?").run(digest,digest,content,time,entry.id);return content}
export function listNoteBlocks(noteId,actor,db=getDatabase()){const note=db.prepare("SELECT 1 FROM notes WHERE id=? AND workspace_id=?").get(noteId,actor.workspaceId);if(!note)throw fail("Note not found",404);ensureNoteBlocks(noteId,db);return db.prepare("SELECT b.id,b.position,b.kind,b.markdown,b.version,i.width,i.height,i.strokes_json AS strokesJson,i.transcript,i.equations_json AS equationsJson,i.ocr_status AS ocrStatus,i.svg_path AS svgPath,i.version AS inkVersion FROM note_blocks b LEFT JOIN note_ink_blocks i ON i.block_id=b.id WHERE b.note_id=? ORDER BY b.position").all(noteId).map(row=>({...row,strokes:row.strokesJson?JSON.parse(row.strokesJson):[],equations:row.equationsJson?JSON.parse(row.equationsJson):[],taskProposals:row.kind==="ink"?db.prepare("SELECT id,text,state FROM ink_task_proposals WHERE block_id=? ORDER BY created_at").all(row.id):[]}))}
export function saveMarkdownBlock(noteId,input,actor,db=getDatabase()){const note=db.prepare("SELECT 1 FROM notes WHERE id=? AND workspace_id=?").get(noteId,actor.workspaceId);if(!note)throw fail("Note not found",404);ensureNoteBlocks(noteId,db);const id=input.id||randomUUID(),before=db.prepare("SELECT * FROM note_blocks WHERE id=? AND note_id=? AND kind='markdown'").get(id,noteId),markdown=String(input.markdown??"");if(Buffer.byteLength(markdown)>2_000_000)throw fail("Markdown block too large");if(before&&Number(input.version)!==before.version)throw fail(`Expected version ${before.version}`,409);const time=now(),position=before?.position??db.prepare("SELECT COALESCE(MAX(position),-1)+1 value FROM note_blocks WHERE note_id=?").get(noteId).value;if(before)db.prepare("UPDATE note_blocks SET markdown=?,updated_at=?,version=version+1 WHERE id=?").run(markdown,time,id);else db.prepare("INSERT INTO note_blocks(id,note_id,position,kind,markdown,created_at,updated_at) VALUES(?,?,?,?,?,?,?)").run(id,noteId,position,"markdown",markdown,time,time);writeBlockProjection(noteId,actor,db);return listNoteBlocks(noteId,actor,db).find(block=>block.id===id)}
export function reorderNoteBlocks(noteId,input,actor,db=getDatabase()){const ids=Array.isArray(input.ids)?input.ids.map(String):[],current=db.prepare("SELECT id FROM note_blocks WHERE note_id=? ORDER BY position").all(noteId).map(row=>row.id);if(ids.length!==current.length||new Set(ids).size!==ids.length||ids.some(id=>!current.includes(id)))throw fail("Block order must contain every note block once");db.exec("BEGIN IMMEDIATE");try{for(let i=0;i<ids.length;i++)db.prepare("UPDATE note_blocks SET position=?,updated_at=? WHERE id=? AND note_id=?").run(-i-1,now(),ids[i],noteId);for(let i=0;i<ids.length;i++)db.prepare("UPDATE note_blocks SET position=? WHERE id=? AND note_id=?").run(i,ids[i],noteId);db.exec("COMMIT")}catch(error){db.exec("ROLLBACK");throw error}writeBlockProjection(noteId,actor,db);return listNoteBlocks(noteId,actor,db)}
export function saveInkBlock(noteId,input,actor,db=getDatabase()){
  const note=db.prepare("SELECT * FROM notes WHERE id=? AND workspace_id=?").get(noteId,actor.workspaceId);if(!note)throw fail("Note not found",404);ensureNoteBlocks(noteId,db);const validated=validateStrokes(input),id=input.id||randomUUID(),before=db.prepare("SELECT i.*,b.position FROM note_ink_blocks i JOIN note_blocks b ON b.id=i.block_id WHERE i.block_id=? AND b.note_id=?").get(id,noteId);if(before&&Number(input.version)!==before.version)throw fail(`Expected version ${before.version}`,409);const entry=db.prepare("SELECT e.*,s.root_path FROM vault_entries e JOIN vault_sources s ON s.id=e.source_id WHERE e.note_id=? AND s.workspace_id=?").get(noteId,actor.workspaceId);if(!entry)throw fail("Ink blocks require a vault-backed note",409);const svgRel=`Attachments/Noema Ink/${id}.svg`,jsonRel=`Attachments/Noema Ink/${id}.json`;atomicWrite(vaultPath(entry.root_path,svgRel),strokesToSvg(input));atomicWrite(vaultPath(entry.root_path,jsonRel),JSON.stringify({version:1,width:validated.width,height:validated.height,strokes:validated.strokes}));const time=now(),position=before?.position??db.prepare("SELECT COALESCE(MAX(position),-1)+1 AS value FROM note_blocks WHERE note_id=?").get(noteId).value;
  db.exec("BEGIN IMMEDIATE");try{if(!before)db.prepare("INSERT INTO note_blocks(id,note_id,position,kind,created_at,updated_at) VALUES(?,?,?,?,?,?)").run(id,noteId,position,"ink",time,time);else db.prepare("UPDATE note_blocks SET updated_at=?,version=version+1 WHERE id=?").run(time,id);db.prepare("INSERT INTO note_ink_blocks(block_id,width,height,strokes_json,svg_path,json_path,stroke_hash,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(block_id) DO UPDATE SET width=excluded.width,height=excluded.height,strokes_json=excluded.strokes_json,svg_path=excluded.svg_path,json_path=excluded.json_path,stroke_hash=excluded.stroke_hash,ocr_status='pending',updated_at=excluded.updated_at,version=note_ink_blocks.version+1").run(id,validated.width,validated.height,validated.json,svgRel,jsonRel,hash(validated.json),time);db.exec("COMMIT")}catch(error){db.exec("ROLLBACK");throw error}writeBlockProjection(noteId,actor,db);const jobId=enqueueJob("handwriting-ocr",{blockId:id},db,actor.workspaceId);return {...db.prepare("SELECT * FROM note_ink_blocks WHERE block_id=?").get(id),id,position,jobId}
}
export function deleteNoteBlock(noteId,blockId,input,actor,db=getDatabase()){const row=db.prepare("SELECT b.*,i.svg_path,i.json_path,s.root_path FROM note_blocks b JOIN notes n ON n.id=b.note_id LEFT JOIN note_ink_blocks i ON i.block_id=b.id LEFT JOIN vault_entries e ON e.note_id=n.id LEFT JOIN vault_sources s ON s.id=e.source_id WHERE b.id=? AND b.note_id=? AND n.workspace_id=?").get(blockId,noteId,actor.workspaceId);if(!row)throw fail("Block not found",404);if(Number(input.version)!==row.version)throw fail(`Expected version ${row.version}`,409);if(db.prepare("SELECT COUNT(*) value FROM note_blocks WHERE note_id=?").get(noteId).value===1)throw fail("A note must keep one block",409);db.prepare("DELETE FROM note_blocks WHERE id=?").run(blockId);for(const path of [row.svg_path,row.json_path])if(path&&row.root_path){const target=vaultPath(row.root_path,path);if(existsSync(target))renameSync(target,`${target}.trash-${Date.now()}`)}reorderNoteBlocks(noteId,{ids:db.prepare("SELECT id FROM note_blocks WHERE note_id=? ORDER BY position").all(noteId).map(item=>item.id)},actor,db);return {ok:true}}
export function retryInkOcr(blockId,actor,db=getDatabase()){const row=db.prepare("SELECT i.block_id FROM note_ink_blocks i JOIN note_blocks b ON b.id=i.block_id JOIN notes n ON n.id=b.note_id WHERE i.block_id=? AND n.workspace_id=?").get(blockId,actor.workspaceId);if(!row)throw fail("Ink block not found",404);db.prepare("UPDATE note_ink_blocks SET ocr_status='pending',updated_at=? WHERE block_id=?").run(now(),blockId);return {jobId:enqueueJob("handwriting-ocr",{blockId},db,actor.workspaceId)}}
export function updateInkTranscript(blockId,input,actor,db=getDatabase()){const row=db.prepare("SELECT i.*,n.id AS note_id,n.title,n.content,n.tags_json FROM note_ink_blocks i JOIN note_blocks b ON b.id=i.block_id JOIN notes n ON n.id=b.note_id WHERE i.block_id=? AND n.workspace_id=?").get(blockId,actor.workspaceId);if(!row)throw fail("Ink block not found",404);if(Number(input.version)!==row.version)throw fail(`Expected version ${row.version}`,409);const transcript=String(input.transcript||"").slice(0,100000),equations=Array.isArray(input.equations)?input.equations.slice(0,100):[];db.prepare("UPDATE note_ink_blocks SET transcript=?,equations_json=?,ocr_status='corrected',updated_at=?,version=version+1 WHERE block_id=?").run(transcript,JSON.stringify(equations),now(),blockId);const indexed=[...db.prepare("SELECT i.transcript FROM note_ink_blocks i JOIN note_blocks b ON b.id=i.block_id WHERE b.note_id=?").all(row.note_id).map(item=>item.transcript),row.content].join("\n");db.prepare("DELETE FROM notes_fts WHERE id=?").run(row.note_id);db.prepare("INSERT INTO notes_fts(id,title,content,tags) VALUES(?,?,?,?)").run(row.note_id,row.title,indexed,JSON.parse(row.tags_json).join(" "));return db.prepare("SELECT * FROM note_ink_blocks WHERE block_id=?").get(blockId)}
function moveContext(sourceId,from,to,workspaceId,db){const source=sourceRow(sourceId,workspaceId,db),oldPath=safeRelativePath(from),newPath=safeRelativePath(to);if(extname(oldPath).toLowerCase()!==".md"||extname(newPath).toLowerCase()!==".md")throw fail("Vault note paths must end in .md");const entry=db.prepare("SELECT * FROM vault_entries WHERE source_id=? AND relative_path=? AND deleted_at IS NULL").get(sourceId,oldPath);if(!entry)throw fail("Vault entry not found",404);const sourcePath=vaultPath(source.root_path,oldPath,{mustExist:true}),targetPath=vaultPath(source.root_path,newPath);if(existsSync(targetPath))throw fail("Vault destination already exists",409);const oldNames=[oldPath.slice(0,-3),basename(oldPath,".md")],newNames=[newPath.slice(0,-3),basename(newPath,".md")],changes=[];for(const candidate of db.prepare("SELECT e.*,n.content,n.version,n.title,n.tags_json,n.source FROM vault_entries e JOIN notes n ON n.id=e.note_id WHERE e.source_id=? AND e.deleted_at IS NULL").all(sourceId)){let content=candidate.content;for(let i=0;i<oldNames.length;i++){const pattern=new RegExp(`\\[\\[${oldNames[i].replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}(?=([#|]|\\]\\]))`,"g");content=content.replace(pattern,`[[${newNames[i]}`)}if(content!==candidate.content)changes.push({...candidate,nextContent:content})}return {source,entry,oldPath,newPath,sourcePath,targetPath,changes}}
export function previewVaultMove(sourceId,input,workspaceId,db=getDatabase()){const context=moveContext(sourceId,input.from,input.to,workspaceId,db);return {from:context.oldPath,to:context.newPath,backlinks:context.changes.map(change=>({relativePath:change.relative_path,noteId:change.note_id,replacements:(change.content.match(/\[\[/g)||[]).length}))}}
export function moveVaultEntry(sourceId,input,actor,db=getDatabase()){const context=moveContext(sourceId,input.from,input.to,actor.workspaceId,db),originals=context.changes.map(change=>({path:vaultPath(context.source.root_path,change.relative_path,{mustExist:true}),content:readFileSync(vaultPath(context.source.root_path,change.relative_path,{mustExist:true}),"utf8")}));mkdirSync(dirname(context.targetPath),{recursive:true});renameSync(context.sourcePath,context.targetPath);try{for(const change of context.changes)atomicWrite(change.id===context.entry.id?context.targetPath:vaultPath(context.source.root_path,change.relative_path),change.nextContent);db.exec("BEGIN IMMEDIATE");try{db.prepare("UPDATE vault_entries SET relative_path=?,parent_path=?,vault_hash=?,noema_hash=?,last_common_content=?,updated_at=? WHERE id=?").run(context.newPath,dirname(context.newPath)==="."?"":dirname(context.newPath),hash(readFileSync(context.targetPath,"utf8")),hash(readFileSync(context.targetPath,"utf8")),readFileSync(context.targetPath,"utf8"),now(),context.entry.id);db.prepare("UPDATE vault_sync_manifests SET relative_path=? WHERE source_id=? AND relative_path=?").run(context.newPath,sourceId,context.oldPath);db.prepare("UPDATE vault_task_links SET relative_path=? WHERE source_id=? AND relative_path=?").run(context.newPath,sourceId,context.oldPath);for(const change of context.changes){saveNote({id:change.note_id,title:change.title,content:change.nextContent,tags:JSON.parse(change.tags_json),source:change.id===context.entry.id?`Obsidian · ${context.newPath}`:change.source,version:change.version},db,actor);const digest=hash(change.nextContent);db.prepare("UPDATE vault_entries SET vault_hash=?,noema_hash=?,last_common_content=?,updated_at=? WHERE id=?").run(digest,digest,change.nextContent,now(),change.id)}if(!context.changes.some(change=>change.id===context.entry.id)){const moved=db.prepare("SELECT * FROM notes WHERE id=?").get(context.entry.note_id);saveNote({id:moved.id,title:title(moved.content,context.newPath),content:moved.content,tags:JSON.parse(moved.tags_json),source:`Obsidian · ${context.newPath}`,version:moved.version},db,actor)}db.exec("COMMIT")}catch(error){db.exec("ROLLBACK");throw error}}catch(error){if(existsSync(context.targetPath))renameSync(context.targetPath,context.sourcePath);for(const original of originals)atomicWrite(original.path,original.content);throw error}return {from:context.oldPath,to:context.newPath,updatedBacklinks:context.changes.length}}
export function trashVaultEntry(sourceId,relativePath,actor,db=getDatabase()){const source=sourceRow(sourceId,actor.workspaceId,db),rel=safeRelativePath(relativePath),entry=db.prepare("SELECT * FROM vault_entries WHERE source_id=? AND relative_path=? AND deleted_at IS NULL").get(sourceId,rel);if(!entry)throw fail("Vault entry not found",404);const from=vaultPath(source.root_path,rel,{mustExist:true}),trashRel=`.trash/Noema/${new Date().toISOString().replace(/[:.]/g,"-")}/${rel}`,to=vaultPath(source.root_path,trashRel);mkdirSync(dirname(to),{recursive:true});renameSync(from,to);const time=now();db.exec("BEGIN IMMEDIATE");try{db.prepare("UPDATE vault_entries SET sync_state='trashed',deleted_at=?,updated_at=? WHERE id=?").run(time,time,entry.id);db.prepare("UPDATE notes SET trashed=1,updated_at=?,version=version+1 WHERE id=? AND workspace_id=?").run(time,entry.note_id,actor.workspaceId);db.exec("COMMIT")}catch(error){db.exec("ROLLBACK");renameSync(to,from);throw error}return {relativePath:rel,trashPath:trashRel,recoverable:true}}
let lastAutomaticScan=0;
export function scanConnectedVaults(db=getDatabase(),date=new Date()){if(date.getTime()-lastAutomaticScan<3000)return false;lastAutomaticScan=date.getTime();for(const source of db.prepare("SELECT s.id,s.workspace_id,w.created_by FROM vault_sources s JOIN workspaces w ON w.id=s.workspace_id WHERE s.state IN ('connected','error')").all()){try{scanVault(source.id,{id:source.created_by,workspaceId:source.workspace_id},db)}catch(error){db.prepare("UPDATE vault_sources SET state='error',last_result_json=?,updated_at=? WHERE id=?").run(JSON.stringify({error:String(error.message||error)}),now(),source.id)}}return true}
