"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {ArrowClockwise,ArrowRight,MagnifyingGlass,ShareNetwork,Warning} from "@phosphor-icons/react";
import {ModuleShell} from "../components/ModuleShell";

type Node={id:string;type:string;objectId:string;label:string;href:string};
type Edge={id:string;source:string;target:string;kind:string;provenance:string};
type Graph={nodes:Node[];edges:Edge[];meta:{privacy:string}};
const colors:Record<string,string>={project:"#2dd4bf",task:"#60a5fa",event:"#f59e0b",note:"#a78bfa",capture:"#f472b6",asset:"#94a3b8",automation:"#22c55e",course:"#fb7185",assignment:"#f97316"};
const request=async(url:string)=>{const response=await fetch(url),data=await response.json();if(!response.ok)throw new Error(data.error?.message||"Graph is unavailable");return data};

export default function GraphPage(){
  const [graph,setGraph]=useState<Graph>({nodes:[],edges:[],meta:{privacy:""}}),[selected,setSelected]=useState<Node|null>(null),[root,setRoot]=useState(""),[query,setQuery]=useState(""),[types,setTypes]=useState<string[]>([]),[source,setSource]=useState(""),[target,setTarget]=useState(""),[path,setPath]=useState<Graph|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const load=async(nextRoot=root)=>{setLoading(true);setError("");try{const data=await request(`/api/v1/knowledge-graph?limit=120&depth=2${nextRoot?`&root=${encodeURIComponent(nextRoot)}`:""}`);setGraph(data);setSelected(current=>data.nodes.find((node:Node)=>node.id===current?.id)||null)}catch(reason){setError((reason as Error).message)}finally{setLoading(false)}};
  useEffect(()=>{void load("")},[]);
  const availableTypes=useMemo(()=>[...new Set(graph.nodes.map(node=>node.type))].sort(),[graph.nodes]);
  const visible=useMemo(()=>graph.nodes.filter(node=>(!types.length||types.includes(node.type))&&(!query.trim()||node.label.toLowerCase().includes(query.toLowerCase()))),[graph.nodes,types,query]),ids=new Set(visible.map(node=>node.id)),edges=graph.edges.filter(edge=>ids.has(edge.source)&&ids.has(edge.target));
  const positions=useMemo(()=>Object.fromEntries(visible.map((node,index)=>{const angle=index/Math.max(visible.length,1)*Math.PI*2-Math.PI/2,radius=Math.min(240,90+visible.length*2),ring=visible.length>40?0.65+(index%3)*0.17:1;return [node.id,{x:450+Math.cos(angle)*radius*ring,y:295+Math.sin(angle)*radius*ring}]})),[visible]);
  const choose=(node:Node)=>{setSelected(node);setSource(current=>current||node.id)};
  const focus=async(node:Node)=>{setRoot(node.id);setPath(null);await load(node.id)};
  const reset=async()=>{setRoot("");setSelected(null);setPath(null);await load("")};
  const trace=async()=>{if(!source||!target)return;setError("");try{setPath(await request(`/api/v1/knowledge-graph/path?source=${encodeURIComponent(source)}&target=${encodeURIComponent(target)}`))}catch(reason){setPath(null);setError((reason as Error).message)}};
  return <ModuleShell active="Graph" title="Knowledge graph" action={<button className="secondary" disabled={loading} onClick={()=>void reset()}><ArrowClockwise/>Reset</button>}>
    <div className="module-header"><div><h2>See how your workspace connects</h2><p>Explore canonical relationships without copying note bodies, capture text, or private summaries into the graph.</p></div></div>{error&&<div className="warning-text" role="alert"><Warning/>{error}</div>}
    <section className="graph-toolbar"><label><MagnifyingGlass/><span className="sr-only">Filter nodes</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Filter labels…"/></label><div role="group" aria-label="Filter object types">{availableTypes.map(type=><button key={type} className={types.includes(type)?"active":""} aria-pressed={types.includes(type)} onClick={()=>setTypes(current=>current.includes(type)?current.filter(item=>item!==type):[...current,type])}><i style={{background:colors[type]||"#94a3b8"}}/>{type}</button>)}</div><span>{visible.length} nodes · {edges.length} relationships</span></section>
    <div className="graph-layout"><section className="graph-canvas" aria-label="Interactive knowledge graph">{loading?<p role="status">Synchronizing graph…</p>:visible.length?<svg viewBox="0 0 900 590" role="img" aria-labelledby="graph-title graph-description"><title id="graph-title">LifeOS knowledge graph</title><desc id="graph-description">{visible.length} labeled nodes and {edges.length} provenance-backed relationships. Use Tab to select nodes.</desc>{edges.map(edge=>{const a=positions[edge.source],b=positions[edge.target];return a&&b?<line key={edge.id} x1={a.x} y1={a.y} x2={b.x} y2={b.y}/>:null})}{visible.map(node=>{const point=positions[node.id],active=selected?.id===node.id||path?.nodes.some(item=>item.id===node.id);return <g key={node.id} role="button" tabIndex={0} aria-label={`${node.label}, ${node.type}`} className={active?"active":""} transform={`translate(${point.x} ${point.y})`} onClick={()=>choose(node)} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();choose(node)}}}><circle r={active?13:9} fill={colors[node.type]||"#94a3b8"}/><text y="-16" textAnchor="middle">{node.label.slice(0,28)}</text></g>})}</svg>:<div className="empty-state"><ShareNetwork/><h3>No connected objects yet</h3><p>Create tasks, notes, projects, or links to populate the graph.</p></div>}</section>
      <aside className="graph-inspector"><h3>{selected?selected.label:"Select a node"}</h3>{selected?<><span><i style={{background:colors[selected.type]}}/>{selected.type}</span><button className="secondary" onClick={()=>void focus(selected)}>Focus neighborhood</button><Link className="primary" href={selected.href}>Open source<ArrowRight/></Link></>:<p>Choose a node in the graph or table to inspect its source and neighborhood.</p>}<small>{graph.meta.privacy}</small></aside></div>
    <section className="path-finder"><header><div><h3>Trace a path</h3><p>Find the shortest provenance-backed connection between two objects.</p></div><button className="primary" disabled={!source||!target||source===target} onClick={()=>void trace()}>Trace path</button></header><div><label>From<select value={source} onChange={event=>setSource(event.target.value)}><option value="">Select source</option>{graph.nodes.map(node=><option key={node.id} value={node.id}>{node.label} · {node.type}</option>)}</select></label><ArrowRight/><label>To<select value={target} onChange={event=>setTarget(event.target.value)}><option value="">Select target</option>{graph.nodes.map(node=><option key={node.id} value={node.id}>{node.label} · {node.type}</option>)}</select></label></div>{path&&<ol aria-label="Shortest path">{path.nodes.map((node,index)=><li key={node.id}><Link href={node.href}>{node.label}</Link><small>{node.type}{index<path.edges.length?` · ${path.edges[index].kind} via ${path.edges[index].provenance}`:""}</small></li>)}</ol>}</section>
    <section className="graph-table"><div className="list-title"><h3>Accessible relationship table</h3><span>Equivalent to the visual graph</span></div><div role="region" aria-label="Knowledge graph relationships" tabIndex={0}><table><thead><tr><th>Source</th><th>Relationship</th><th>Target</th><th>Provenance</th></tr></thead><tbody>{edges.map(edge=>{const sourceNode=graph.nodes.find(node=>node.id===edge.source),targetNode=graph.nodes.find(node=>node.id===edge.target);return <tr key={edge.id}><td><button onClick={()=>sourceNode&&choose(sourceNode)}>{sourceNode?.label}</button></td><td>{edge.kind}</td><td><button onClick={()=>targetNode&&choose(targetNode)}>{targetNode?.label}</button></td><td><code>{edge.provenance}</code></td></tr>})}</tbody></table></div></section>
  </ModuleShell>;
}
