"use client";

import {FormEvent,useEffect,useState} from "react";
import {Check,Database,DownloadSimple,FolderOpen,Key,Lock,Monitor,ShieldCheck,SlidersHorizontal,User} from "@phosphor-icons/react";
import {ModuleShell} from "../components/ModuleShell";
import {AIAgentSettings} from "../components/AIAgentSettings";
import {LifeOSMigration} from "../components/LifeOSMigration";

type Settings={email:string;profile:{name:string};preferences:{startPage:string;weekStartsOn:string;compactLists:boolean};notifications:{push:boolean;reminders:boolean;jobFailures:boolean};agentPermissions:{readNotes:boolean;createDrafts:boolean;runCode:boolean;sensitiveActions:boolean};calendar:{timezone:string;selectedCalendars:string[]};backup:{enabled:boolean;retentionDays:number};ai:{profile:"fast"|"balanced"|"quality"};version:number};
type Session={id:string;device:string;createdAt:string;expiresAt:string;current:boolean};
type Mfa={enabled:boolean;enrollmentPending:boolean;recoveryCodes:number};
type GoogleCalendar={id:string;name:string;timezone:string|null;accessRole:string;selected:boolean};
type GoogleConnection={connected:boolean;configured?:boolean;email?:string;health?:string;lastError?:string|null;calendars:GoogleCalendar[]};
type CalendarSync={calendars:{id:string;name:string;lastSyncedAt:string|null;lastError:string|null}[];conflicts:{id:string}[]};
type Analytics={enabled:boolean;eventCount:number};
type VaultSource={id:string;name:string;root_path:string;state:string;taskFolders:string[];last_sync_at:string|null;lastResult:{created:number;updated:number;written:number;conflicts:number;tasks:number}|null};
const sections=["Preferences","Vault","Account","Agents","Security","Data"] as const,icons={Preferences:SlidersHorizontal,Vault:FolderOpen,Account:User,Agents:ShieldCheck,Security:Lock,Data:Database};
async function request(path:string,init?:RequestInit){const response=await fetch(path,init),data=await response.json();if(!response.ok)throw new Error(data.error?.message||"Request failed");return data}
const applicationKey=(value:string)=>{const padded=value.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(value.length/4)*4,"="),bytes=atob(padded);return Uint8Array.from(bytes,char=>char.charCodeAt(0))};

export default function SettingsPage(){
  const [section,setSection]=useState<(typeof sections)[number]>("Preferences"),[settings,setSettings]=useState<Settings|null>(null),[sessions,setSessions]=useState<Session[]>([]),[mfa,setMfa]=useState<Mfa|null>(null),[google,setGoogle]=useState<GoogleConnection>({connected:false,calendars:[]}),[sync,setSync]=useState<CalendarSync>({calendars:[],conflicts:[]}),[vaults,setVaults]=useState<VaultSource[]>([]),[analytics,setAnalytics]=useState<Analytics>({enabled:false,eventCount:0}),[enrollment,setEnrollment]=useState<{secret:string;uri:string}|null>(null),[recovery,setRecovery]=useState<string[]>([]),[message,setMessage]=useState(""),[error,setError]=useState("");
  const load=()=>Promise.all([request("/api/v1/settings"),request("/api/v1/auth/sessions"),request("/api/v1/auth/totp"),request("/api/v1/integrations/google"),request("/api/v1/calendar-sync"),request("/api/v1/analytics"),request("/api/v1/vault-sources")]).then(([value,active,status,connection,syncStatus,analyticsStatus,vaultStatus])=>{setSettings(value);setSessions(active.sessions);setMfa(status);setGoogle(connection);setSync(syncStatus);setAnalytics(analyticsStatus);setVaults(vaultStatus.sources)}).catch(reason=>setError(reason.message));
  useEffect(()=>{void load()},[]);
  const patch=(group:keyof Settings,key:string,value:unknown)=>setSettings(current=>current?{...current,[group]:{...(current[group] as object),[key]:value}}:current);
  async function save(){if(!settings)return;setError("");try{const saved=await request("/api/v1/settings",{method:"PATCH",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(settings)});setSettings({...settings,...saved});setMessage("Saved")}catch(reason){setError((reason as Error).message)}}
  async function changePassword(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{await request("/api/v1/settings/password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword:form.get("currentPassword"),newPassword:form.get("newPassword")})});event.currentTarget.reset();setMessage("Password changed; other sessions were revoked.");void load()}catch(reason){setError((reason as Error).message)}}
  async function startMfa(){try{setEnrollment(await request("/api/v1/auth/totp",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"}))}catch(reason){setError((reason as Error).message)}}
  async function confirmMfa(event:FormEvent<HTMLFormElement>){event.preventDefault();const code=new FormData(event.currentTarget).get("code");try{const result=await request("/api/v1/auth/totp",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code})});setRecovery(result.recoveryCodes);setEnrollment(null);void load()}catch(reason){setError((reason as Error).message)}}
  async function regenerateRecovery(){try{const result=await request("/api/v1/auth/recovery",{method:"POST"});setRecovery(result.recoveryCodes);void load()}catch(reason){setError((reason as Error).message)}}
  async function disableMfa(event:FormEvent<HTMLFormElement>){event.preventDefault();const password=new FormData(event.currentTarget).get("password");try{await request("/api/v1/auth/totp",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});setRecovery([]);setMessage("Two-factor authentication disabled; recovery codes invalidated.");event.currentTarget.reset();void load()}catch(reason){setError((reason as Error).message)}}
  async function revoke(id:string){try{await request(`/api/v1/auth/sessions/${id}`,{method:"DELETE"});setSessions(current=>current.filter(item=>item.id!==id))}catch(reason){setError((reason as Error).message)}}
  async function connectGoogle(){if(!google.configured){setError("Google OAuth credentials are not configured on this Noema server.");return}try{const result=await request("/api/v1/integrations/google/connect",{method:"POST"});location.assign(result.authorizationUrl)}catch(reason){setError((reason as Error).message)}}
  async function discoverCalendars(){try{const result=await request("/api/v1/integrations/google/calendars");setGoogle(current=>({...current,calendars:result.calendars}))}catch(reason){setError((reason as Error).message)}}
  async function selectCalendar(id:string,selected:boolean){const ids=google.calendars.filter(item=>item.selected&&item.id!==id).map(item=>item.id);if(selected)ids.push(id);try{const result=await request("/api/v1/integrations/google/calendars",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({calendarIds:ids})});setGoogle(current=>({...current,calendars:result.calendars}))}catch(reason){setError((reason as Error).message)}}
  async function disconnectGoogle(){try{await request("/api/v1/integrations/google",{method:"DELETE"});setGoogle({connected:false,calendars:[]})}catch(reason){setError((reason as Error).message)}}
  async function syncCalendars(){try{setMessage("Syncing calendars…");const result=await request("/api/v1/calendar-sync",{method:"POST"});setSync({calendars:result.calendars,conflicts:result.conflicts});setMessage(`Calendar sync complete · ${result.result.pushed.completed} pushed · ${result.result.pulled.imported} imported`)}catch(reason){setError((reason as Error).message);setMessage("")}}
  async function setAnalyticsEnabled(enabled:boolean){try{setAnalytics(await request("/api/v1/analytics",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({enabled})}))}catch(reason){setError((reason as Error).message)}}
  async function eraseAnalytics(){try{await request("/api/v1/analytics",{method:"DELETE"});setAnalytics(current=>({...current,eventCount:0}));setMessage("Analytics history deleted")}catch(reason){setError((reason as Error).message)}}
  async function connectVault(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{await request("/api/v1/vault-sources",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.get("name"),rootPath:form.get("rootPath"),taskFolders:String(form.get("taskFolders")||"TODO/").split(",").map(value=>value.trim()).filter(Boolean)})});event.currentTarget.reset();setMessage("Vault connected");void load()}catch(reason){setError((reason as Error).message)}}
  async function syncVault(id:string){try{setMessage("Syncing vault…");const result=await request(`/api/v1/vault-sources/${id}/sync`,{method:"POST"});setMessage(`Vault sync complete · ${result.created} created · ${result.updated} imported · ${result.written} written · ${result.conflicts} conflicts`);void load()}catch(reason){setError((reason as Error).message)}}
  async function updateVaultFolders(event:FormEvent<HTMLFormElement>,id:string){event.preventDefault();const form=new FormData(event.currentTarget);try{const source=await request(`/api/v1/vault-sources/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({taskFolders:String(form.get("taskFolders")||"").split(",").map(value=>value.trim()).filter(Boolean)})});setVaults(current=>current.map(item=>item.id===id?source:item));setMessage("Task folders updated")}catch(reason){setError((reason as Error).message)}}
  async function setPush(enabled:boolean){try{if(!("serviceWorker" in navigator)||!("PushManager" in window))throw new Error("Push notifications are not supported in this browser");const registration=await navigator.serviceWorker.ready,current=await registration.pushManager.getSubscription();if(enabled){const config=await request("/api/v1/push-subscriptions");if(!config.configured)throw new Error("Web Push is not configured on this server");if(await Notification.requestPermission()!=="granted")throw new Error("Notification permission was not granted");const subscription=current||await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:applicationKey(config.publicKey)}),value=subscription.toJSON();await request("/api/v1/push-subscriptions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({endpoint:value.endpoint,keys:value.keys})})}else if(current){await request("/api/v1/push-subscriptions",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({endpoint:current.endpoint})});await current.unsubscribe()}patch("notifications","push",enabled);setMessage(enabled?"Push notifications enabled":"Push notifications disabled")}catch(reason){setError((reason as Error).message)}}
  if(!settings)return <ModuleShell active="Settings" title="Settings"><p role={error?"alert":"status"}>{error||"Loading settings…"}</p></ModuleShell>;
  return <ModuleShell active="Settings" title="Settings"><div className="settings-layout"><nav className="settings-nav" aria-label="Settings sections">{sections.map(label=>{const Icon=icons[label];return <button className={section===label?"active":""} onClick={()=>setSection(label)} key={label}><Icon/>{label}</button>})}</nav><section className="settings-content"><header><h2>{section}</h2><p>Persisted for your private Noema account.</p></header>
    {section==="Preferences"&&<><div className="setting-row"><span><strong>Start page</strong><small>Page shown when Noema opens</small></span><select value={settings.preferences.startPage} onChange={event=>patch("preferences","startPage",event.target.value)}>{["Today","Capture","Tasks","Calendar","Vault"].map(value=><option key={value}>{value}</option>)}</select></div><div className="setting-row"><span><strong>Week starts on</strong><small>Used by calendar and planning views</small></span><select value={settings.preferences.weekStartsOn} onChange={event=>patch("preferences","weekStartsOn",event.target.value)}><option>Monday</option><option>Sunday</option></select></div><Toggle label="Compact lists" detail="Show more rows without hiding information" checked={settings.preferences.compactLists} onChange={value=>patch("preferences","compactLists",value)}/><h3>Google Calendar</h3><div className="setting-row"><span><strong>{google.connected?google.email:"Not connected"}</strong><small>{google.connected?sync.conflicts.length?`${sync.conflicts.length} conflict${sync.conflicts.length===1?"":"s"} need review`:google.health==="error"?google.lastError||"Connection needs attention":"Choose calendars for two-way sync":"OAuth credentials stay encrypted on this server"}</small></span>{google.connected?<><button className="secondary" onClick={()=>void syncCalendars()}>Sync now</button><button className="secondary" onClick={()=>void discoverCalendars()}>Refresh calendars</button><button className="secondary" onClick={()=>void disconnectGoogle()}>Disconnect</button></>:<button className="secondary" onClick={()=>void connectGoogle()}>Connect Google</button>}</div>{sync.calendars.map(calendar=><small key={calendar.id}>{calendar.name}: {calendar.lastError||calendar.lastSyncedAt?calendar.lastError||`Last synced ${new Date(calendar.lastSyncedAt!).toLocaleString()}`:"Not synced yet"}</small>)}{google.calendars.map(calendar=><Toggle key={calendar.id} label={calendar.name} detail={`${calendar.accessRole}${calendar.timezone?` · ${calendar.timezone}`:""}`} checked={calendar.selected} onChange={selected=>void selectCalendar(calendar.id,selected)}/>)}</>}
    {section==="Vault"&&<><p>Obsidian remains canonical. Noema writes through conflict-aware atomic operations.</p>{vaults.map(vault=><form onSubmit={event=>updateVaultFolders(event,vault.id)} key={vault.id}><div className="setting-row"><span><strong>{vault.name}</strong><small>{vault.root_path} · {vault.last_sync_at?`Last synced ${new Date(vault.last_sync_at).toLocaleString()}`:"Not synced yet"}{vault.lastResult?.conflicts?` · ${vault.lastResult.conflicts} conflicts`:""}</small></span><button type="button" className="secondary" onClick={()=>void syncVault(vault.id)}>Sync now</button></div><label>Task folders<input name="taskFolders" defaultValue={vault.taskFolders.join(", ")} aria-label={`Task folders for ${vault.name}`}/></label><button className="secondary">Save task folders</button></form>)}<form onSubmit={connectVault}><h3>Connect vault</h3><label>Name<input name="name" defaultValue="Obsidian" required/></label><label>Absolute server path<input name="rootPath" placeholder="/srv/obsidian/My Vault" required/></label><label>Task folders<input name="taskFolders" defaultValue="TODO/" aria-describedby="task-folder-help"/></label><small id="task-folder-help">Comma-separated paths. Checkboxes elsewhere remain note content.</small><button className="secondary"><FolderOpen/>Connect</button></form></>}
    {section==="Account"&&<><div className="profile-block"><span>{(settings.profile.name||settings.email).slice(0,2).toUpperCase()}</span><div><strong>{settings.profile.name||"Noema owner"}</strong><small>{settings.email} · Self-hosted owner</small></div><input aria-label="Display name" value={settings.profile.name} placeholder="Display name" onChange={event=>patch("profile","name",event.target.value)}/></div><form onSubmit={changePassword}><div className="setting-row"><span><strong>Password</strong><small>Changing it revokes every other session</small></span><input name="currentPassword" type="password" autoComplete="current-password" placeholder="Current password" required/><input name="newPassword" type="password" autoComplete="new-password" minLength={12} placeholder="New password" required/><button className="secondary"><Key/>Change</button></div></form></>}
    {section==="Agents"&&<><div className="setting-row"><span><strong>AI profile</strong><small>Fast minimizes latency and cost; Balanced and Quality use their ordered agent lists.</small></span><select value={settings.ai.profile} onChange={event=>patch("ai","profile",event.target.value)}><option value="fast">Fast</option><option value="balanced">Balanced</option><option value="quality">Quality</option></select></div><AIAgentSettings/><Toggle label="Read notes" detail="Use selected Vault context" checked={settings.agentPermissions.readNotes} onChange={value=>patch("agentPermissions","readNotes",value)}/><Toggle label="Create drafts" detail="Proposals still require review" checked={settings.agentPermissions.createDrafts} onChange={value=>patch("agentPermissions","createDrafts",value)}/><Toggle label="Run code" detail="Sensitive commands require approval" checked={settings.agentPermissions.runCode} onChange={value=>patch("agentPermissions","runCode",value)}/><div className="permission-note"><ShieldCheck/><span><strong>Safety boundary</strong><small>Authentication and destructive production changes cannot be auto-approved.</small></span></div></>}
    {section==="Security"&&<><div className="setting-row"><span><strong>Two-factor authentication</strong><small>{mfa?.enabled?`Enabled · ${mfa.recoveryCodes} recovery codes remain`:"Protect sensitive actions with an authenticator"}</small></span>{!mfa?.enabled&&!enrollment&&<button className="secondary" onClick={startMfa}>Set up</button>}{mfa?.enabled&&<button className="secondary" onClick={()=>void regenerateRecovery()}>New recovery codes</button>}</div>{enrollment&&<form className="auth-result" onSubmit={confirmMfa}><strong>Manual key</strong><code>{enrollment.secret}</code><small>Add this key to your authenticator, then confirm a current code.</small><input name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} aria-label="Authenticator code" required/><button className="primary">Confirm</button></form>}{recovery.length>0&&<div className="auth-result" role="status"><strong>Save these recovery codes now</strong><code>{recovery.join("\n")}</code><small>They will not be shown again. Generating another set invalidates these codes.</small></div>}{mfa?.enabled&&<form onSubmit={disableMfa}><div className="setting-row"><span><strong>Disable two-factor authentication</strong><small>Requires your password and invalidates every recovery code</small></span><input name="password" type="password" autoComplete="current-password" placeholder="Current password" required/><button className="secondary">Disable</button></div></form>}<h3>Active sessions</h3>{sessions.map(session=><div className="session-setting" key={session.id}><Monitor/><span><strong>{session.device||"Unknown device"}</strong><small>Created {new Date(session.createdAt).toLocaleString()}</small></span>{session.current?<em>Current</em>:<button className="secondary" onClick={()=>void revoke(session.id)}>Revoke</button>}</div>)}</>}
    {section==="Data"&&<><div className="setting-row"><span><strong>Export workspace</strong><small>Portable archive without credentials or secrets</small></span><button className="secondary" onClick={()=>location.assign("/api/v1/export")}><DownloadSimple/>Export</button></div><Toggle label="Scheduled backups" detail="Enable automated local backup policy" checked={settings.backup.enabled} onChange={value=>patch("backup","enabled",value)}/><div className="setting-row"><span><strong>Retention</strong><small>Number of local backups to retain</small></span><input type="number" min={1} max={365} value={settings.backup.retentionDays} onChange={event=>patch("backup","retentionDays",Number(event.target.value))}/></div><Toggle label="Push notifications" detail="Register this browser for encrypted Web Push delivery" checked={settings.notifications.push} onChange={value=>void setPush(value)}/><h3>Private analytics</h3><Toggle label="Local usage analytics" detail="Off by default; stores only fixed feature, outcome, count, and duration values" checked={analytics.enabled} onChange={value=>void setAnalyticsEnabled(value)}/><div className="setting-row"><span><strong>Stored events</strong><small>{analytics.eventCount} local event{analytics.eventCount===1?"":"s"}; never note or capture content, attachments, prompts, extracted text, or object IDs</small></span><button className="secondary" disabled={!analytics.eventCount} onClick={()=>void eraseAnalytics()}>Delete analytics</button></div><LifeOSMigration/></>}
    {error&&<p className="auth-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<footer><button className="primary" onClick={()=>void save()}>{message==="Saved"?<><Check/>Saved</>:"Save changes"}</button></footer></section></div></ModuleShell>
}

function Toggle({label,detail,checked,onChange}:{label:string;detail:string;checked:boolean;onChange:(value:boolean)=>void}){return <div className="setting-row"><span><strong>{label}</strong><small>{detail}</small></span><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)}/></div>}
