"use client";

import {FormEvent,useEffect,useState} from "react";
import {Check,Database,DownloadSimple,Key,Lock,Monitor,ShieldCheck,SlidersHorizontal,User} from "@phosphor-icons/react";
import {ModuleShell} from "../components/ModuleShell";

type Settings={email:string;profile:{name:string};preferences:{startPage:string;weekStartsOn:string;compactLists:boolean};notifications:{push:boolean;reminders:boolean;jobFailures:boolean};agentPermissions:{readNotes:boolean;createDrafts:boolean;runCode:boolean;sensitiveActions:boolean};calendar:{timezone:string;selectedCalendars:string[]};backup:{enabled:boolean;retentionDays:number};version:number};
type Session={id:string;device:string;createdAt:string;expiresAt:string;current:boolean};
type Mfa={enabled:boolean;enrollmentPending:boolean;recoveryCodes:number};
const sections=["Preferences","Account","Agents","Security","Data"] as const,icons={Preferences:SlidersHorizontal,Account:User,Agents:ShieldCheck,Security:Lock,Data:Database};
async function request(path:string,init?:RequestInit){const response=await fetch(path,init),data=await response.json();if(!response.ok)throw new Error(data.error?.message||"Request failed");return data}

export default function SettingsPage(){
  const [section,setSection]=useState<(typeof sections)[number]>("Preferences"),[settings,setSettings]=useState<Settings|null>(null),[sessions,setSessions]=useState<Session[]>([]),[mfa,setMfa]=useState<Mfa|null>(null),[enrollment,setEnrollment]=useState<{secret:string;uri:string}|null>(null),[recovery,setRecovery]=useState<string[]>([]),[message,setMessage]=useState(""),[error,setError]=useState("");
  const load=()=>Promise.all([request("/api/v1/settings"),request("/api/v1/auth/sessions"),request("/api/v1/auth/totp")]).then(([value,active,status])=>{setSettings(value);setSessions(active.sessions);setMfa(status)}).catch(reason=>setError(reason.message));
  useEffect(()=>{void load()},[]);
  const patch=(group:keyof Settings,key:string,value:unknown)=>setSettings(current=>current?{...current,[group]:{...(current[group] as object),[key]:value}}:current);
  async function save(){if(!settings)return;setError("");try{const saved=await request("/api/v1/settings",{method:"PATCH",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(settings)});setSettings({...settings,...saved});setMessage("Saved")}catch(reason){setError((reason as Error).message)}}
  async function changePassword(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{await request("/api/v1/settings/password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword:form.get("currentPassword"),newPassword:form.get("newPassword")})});event.currentTarget.reset();setMessage("Password changed; other sessions were revoked.");void load()}catch(reason){setError((reason as Error).message)}}
  async function startMfa(){try{setEnrollment(await request("/api/v1/auth/totp",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"}))}catch(reason){setError((reason as Error).message)}}
  async function confirmMfa(event:FormEvent<HTMLFormElement>){event.preventDefault();const code=new FormData(event.currentTarget).get("code");try{const result=await request("/api/v1/auth/totp",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code})});setRecovery(result.recoveryCodes);setEnrollment(null);void load()}catch(reason){setError((reason as Error).message)}}
  async function regenerateRecovery(){try{const result=await request("/api/v1/auth/recovery",{method:"POST"});setRecovery(result.recoveryCodes);void load()}catch(reason){setError((reason as Error).message)}}
  async function disableMfa(event:FormEvent<HTMLFormElement>){event.preventDefault();const password=new FormData(event.currentTarget).get("password");try{await request("/api/v1/auth/totp",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});setRecovery([]);setMessage("Two-factor authentication disabled; recovery codes invalidated.");event.currentTarget.reset();void load()}catch(reason){setError((reason as Error).message)}}
  async function revoke(id:string){try{await request(`/api/v1/auth/sessions/${id}`,{method:"DELETE"});setSessions(current=>current.filter(item=>item.id!==id))}catch(reason){setError((reason as Error).message)}}
  if(!settings)return <ModuleShell active="Settings" title="Settings"><p role={error?"alert":"status"}>{error||"Loading settings…"}</p></ModuleShell>;
  return <ModuleShell active="Settings" title="Settings"><div className="settings-layout"><nav className="settings-nav" aria-label="Settings sections">{sections.map(label=>{const Icon=icons[label];return <button className={section===label?"active":""} onClick={()=>setSection(label)} key={label}><Icon/>{label}</button>})}</nav><section className="settings-content"><header><h2>{section}</h2><p>Persisted for your private LifeOS account.</p></header>
    {section==="Preferences"&&<><div className="setting-row"><span><strong>Start page</strong><small>Page shown when LifeOS opens</small></span><select value={settings.preferences.startPage} onChange={event=>patch("preferences","startPage",event.target.value)}>{["Today","Capture","Tasks","Calendar","Vault"].map(value=><option key={value}>{value}</option>)}</select></div><div className="setting-row"><span><strong>Week starts on</strong><small>Used by calendar and planning views</small></span><select value={settings.preferences.weekStartsOn} onChange={event=>patch("preferences","weekStartsOn",event.target.value)}><option>Monday</option><option>Sunday</option></select></div><Toggle label="Compact lists" detail="Show more rows without hiding information" checked={settings.preferences.compactLists} onChange={value=>patch("preferences","compactLists",value)}/></>}
    {section==="Account"&&<><div className="profile-block"><span>{(settings.profile.name||settings.email).slice(0,2).toUpperCase()}</span><div><strong>{settings.profile.name||"LifeOS owner"}</strong><small>{settings.email} · Self-hosted owner</small></div><input aria-label="Display name" value={settings.profile.name} placeholder="Display name" onChange={event=>patch("profile","name",event.target.value)}/></div><form onSubmit={changePassword}><div className="setting-row"><span><strong>Password</strong><small>Changing it revokes every other session</small></span><input name="currentPassword" type="password" autoComplete="current-password" placeholder="Current password" required/><input name="newPassword" type="password" autoComplete="new-password" minLength={12} placeholder="New password" required/><button className="secondary"><Key/>Change</button></div></form></>}
    {section==="Agents"&&<><Toggle label="Read notes" detail="Use selected Vault context" checked={settings.agentPermissions.readNotes} onChange={value=>patch("agentPermissions","readNotes",value)}/><Toggle label="Create drafts" detail="Proposals still require review" checked={settings.agentPermissions.createDrafts} onChange={value=>patch("agentPermissions","createDrafts",value)}/><Toggle label="Run code" detail="Sensitive commands require approval" checked={settings.agentPermissions.runCode} onChange={value=>patch("agentPermissions","runCode",value)}/><div className="permission-note"><ShieldCheck/><span><strong>Safety boundary</strong><small>Authentication and destructive production changes cannot be auto-approved.</small></span></div></>}
    {section==="Security"&&<><div className="setting-row"><span><strong>Two-factor authentication</strong><small>{mfa?.enabled?`Enabled · ${mfa.recoveryCodes} recovery codes remain`:"Protect sensitive actions with an authenticator"}</small></span>{!mfa?.enabled&&!enrollment&&<button className="secondary" onClick={startMfa}>Set up</button>}{mfa?.enabled&&<button className="secondary" onClick={()=>void regenerateRecovery()}>New recovery codes</button>}</div>{enrollment&&<form className="auth-result" onSubmit={confirmMfa}><strong>Manual key</strong><code>{enrollment.secret}</code><small>Add this key to your authenticator, then confirm a current code.</small><input name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} aria-label="Authenticator code" required/><button className="primary">Confirm</button></form>}{recovery.length>0&&<div className="auth-result" role="status"><strong>Save these recovery codes now</strong><code>{recovery.join("\n")}</code><small>They will not be shown again. Generating another set invalidates these codes.</small></div>}{mfa?.enabled&&<form onSubmit={disableMfa}><div className="setting-row"><span><strong>Disable two-factor authentication</strong><small>Requires your password and invalidates every recovery code</small></span><input name="password" type="password" autoComplete="current-password" placeholder="Current password" required/><button className="secondary">Disable</button></div></form>}<h3>Active sessions</h3>{sessions.map(session=><div className="session-setting" key={session.id}><Monitor/><span><strong>{session.device||"Unknown device"}</strong><small>Created {new Date(session.createdAt).toLocaleString()}</small></span>{session.current?<em>Current</em>:<button className="secondary" onClick={()=>void revoke(session.id)}>Revoke</button>}</div>)}</>}
    {section==="Data"&&<><div className="setting-row"><span><strong>Export workspace</strong><small>Portable archive without credentials or secrets</small></span><button className="secondary" onClick={()=>location.assign("/api/v1/export")}><DownloadSimple/>Export</button></div><Toggle label="Scheduled backups" detail="Enable automated local backup policy" checked={settings.backup.enabled} onChange={value=>patch("backup","enabled",value)}/><div className="setting-row"><span><strong>Retention</strong><small>Number of local backups to retain</small></span><input type="number" min={1} max={365} value={settings.backup.retentionDays} onChange={event=>patch("backup","retentionDays",Number(event.target.value))}/></div><Toggle label="Push notifications" detail="Allow delivery to registered devices" checked={settings.notifications.push} onChange={value=>patch("notifications","push",value)}/></>}
    {error&&<p className="auth-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<footer><button className="primary" onClick={()=>void save()}>{message==="Saved"?<><Check/>Saved</>:"Save changes"}</button></footer></section></div></ModuleShell>
}

function Toggle({label,detail,checked,onChange}:{label:string;detail:string;checked:boolean;onChange:(value:boolean)=>void}){return <div className="setting-row"><span><strong>{label}</strong><small>{detail}</small></span><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)}/></div>}
