"use client";

import {useState} from "react";
import {ArrowLeft, ArrowRight, Check, Circle, Code, FileCode, GitBranch, GitCommit, Play, Plus, Terminal, Warning} from "@phosphor-icons/react";
import {ModuleShell} from "../components/ModuleShell";

const sessions=[
  {name:"LifeOS frontend",repo:"lifeosv2",state:"Running",detail:"Implementing responsive module pages",tone:"active"},
  {name:"Sync service",repo:"lifeos-sync",state:"Waiting for approval",detail:"Run database migration in staging",tone:"warning"},
  {name:"Study parser",repo:"study-agent",state:"Completed",detail:"Added PDF section extraction",tone:"success"},
];

export default function CodingPage(){const [approved,setApproved]=useState(false);const [selected,setSelected]=useState<typeof sessions[number]|null>(null);const [tab,setTab]=useState("Diff");if(selected)return <ModuleShell active="Coding" title={selected.name} action={<button className="secondary" onClick={()=>setSelected(null)}><ArrowLeft/>Sessions</button>}><div className="workspace-head"><div><h2>{selected.name}</h2><p>{selected.repo} · {selected.detail}</p></div><span className={`session-state ${selected.tone}`}><Circle weight="fill"/>{selected.state}</span></div><nav className="workspace-tabs">{["Files","Diff","Terminal","Tests"].map(item=><button className={tab===item?"active":""} onClick={()=>setTab(item)} key={item}>{item}</button>)}</nav><section className="repo-workspace"><aside>{["app/","components/","AppState.tsx","page.tsx","globals.css"].map((item,index)=><button className={index===2?"active":""} key={item}><FileCode/>{item}</button>)}</aside><div>{tab==="Diff"?<pre className="diff"><code><span>@@ app/components/AppState.tsx</span>{"\n"}<del>- toggleTask(id)</del>{"\n"}<ins>+ saveTask(task)</ins>{"\n"}<ins>+ saveEvent(event)</ins></code></pre>:tab==="Terminal"?<pre className="terminal-view"><code>$ npm run build{"\n"}✓ Compiled successfully{"\n"}✓ 15 static routes generated</code></pre>:tab==="Tests"?<div className="test-results"><Check/><h3>All checks passed</h3><p>Build, type checking, and layout scan completed.</p></div>:<pre><code>export type AppState = &#123;{"\n"}  tasks: Task[];{"\n"}  events: Event[];{"\n"}&#125;</code></pre>}</div></section></ModuleShell>;return <ModuleShell active="Coding" title="Coding" action={<button className="primary top-primary"><Plus/>New session</button>}>
  <div className="module-header"><div><h2>Agents, changes, and builds</h2><p>One agent is working. One sensitive action needs approval.</p></div></div>
  {!approved&&<section className="approval"><Warning/><div><small>Approval required</small><strong>Run staging database migration</strong><span><code>npm run migrate:staging</code> · affects 3 pending migrations</span></div><button className="secondary">Review diff</button><button className="primary" onClick={()=>setApproved(true)}><Check/>Approve once</button></section>}
  <div className="coding-layout"><section><div className="list-title"><h3>Agent sessions</h3><span>3 sessions</span></div><div className="session-list">{sessions.map(session=><button className="session-row" key={session.name} onClick={()=>setSelected(session)}><span className={`session-state ${session.tone}`}><Circle weight="fill"/></span><div><strong>{session.name}</strong><span><GitBranch/>{session.repo}</span><small>{session.detail}</small></div><em>{session.state}</em><ArrowRight/></button>)}</div></section><aside className="build-rail"><h3>Build status</h3><article><Check/><div><strong>lifeosv2</strong><span>Production build passed</span></div></article><article><Play/><div><strong>stewie-render</strong><span>Running · 67%</span></div></article><article><Warning/><div><strong>study-agent</strong><span>2 tests failed</span></div></article><button className="secondary" onClick={()=>setSelected(sessions[0])}><Terminal/>Open terminal</button></aside></div>
  <section className="commits"><div className="list-title"><h3>Recent commits</h3><button>View repositories</button></div><article><GitCommit/><code>d4bda6b</code><span>Build responsive LifeOS shell</span><time>12 min ago</time></article><article><GitCommit/><code>a91f8e2</code><span>Add capture interpretation flow</span><time>Yesterday</time></article></section>
  </ModuleShell>}
