"use client";

import Link from "next/link";
import {use, useEffect,useMemo,useRef,useState} from "react";
import {ArrowLeft,CaretRight,Check,File,Folder,GitCommit,GitDiff,Play,ShieldCheck,Terminal,WarningCircle,X} from "@phosphor-icons/react";
import {ModuleShell} from "../../../components/ModuleShell";

type Entry={name:string;path:string;type:"directory"|"file"|"other";size:number|null};
type OpenFile={path:string;content:string;original:string;hash:string};
type Repo={id:string;name:string;path:string};
type Git={status:string;diff:string;history:{ref:string;date:string;subject:string}[]};
export default function RepositoryPage({params}:{params:Promise<{id:string}>}){
  const {id}=use(params),[repo,setRepo]=useState<Repo|null>(null),[path,setPath]=useState(""),[entries,setEntries]=useState<Entry[]>([]),[files,setFiles]=useState<OpenFile[]>([]),[active,setActive]=useState(""),[git,setGit]=useState<Git>({status:"",diff:"",history:[]}),[output,setOutput]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),editor=useRef<HTMLTextAreaElement>(null);
  const current=files.find(file=>file.path===active),dirty=files.filter(file=>file.content!==file.original),crumbs=path.split("/").filter(Boolean),mobileKeys=["Tab","()","{}","[]",";","\"","'","=>"];
  async function json(url:string,init?:RequestInit){const response=await fetch(url,init),body=await response.json();if(!response.ok)throw new Error(body.error?.message||"Request failed");return body}
  async function browse(next=""){setError("");try{const body=await json(`/api/v1/repositories/${id}?path=${encodeURIComponent(next)}`);setRepo(body.repository);if(body.file){setFiles(value=>value.some(file=>file.path===body.file.path)?value:[...value,{...body.file,original:body.file.content}]);setActive(body.file.path)}else{setPath(body.path);setEntries(body.entries)}}catch(reason){setError(reason instanceof Error?reason.message:"Path could not be opened")}}
  async function refreshGit(){try{setGit(await json(`/api/v1/repositories/${id}/git`))}catch(reason){setError(reason instanceof Error?reason.message:"Git state is unavailable")}}
  useEffect(()=>{void Promise.all([browse(),refreshGit()])},[id]);
  function edit(content:string){setFiles(value=>value.map(file=>file.path===active?{...file,content}:file))}
  function insert(value:string){const element=editor.current;if(!element||!current)return;const text=value==="Tab"?"  ":value,start=element.selectionStart,end=element.selectionEnd;edit(current.content.slice(0,start)+text+current.content.slice(end));requestAnimationFrame(()=>{element.focus();element.setSelectionRange(start+text.length,start+text.length)})}
  async function approval(actionType:string,action:object,details:{summary:string;risk:string;commands?:string[];files?:string[];diff?:string}){let record=await json("/api/v1/approvals",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({actionType,action,...details})});if(!confirm(`${details.summary}\n\n${details.diff||details.commands?.join("\n")||""}`))throw new Error("Approval cancelled");await json(`/api/v1/approvals/${record.id}/approve`,{method:"POST"});return record.id}
  async function save(){if(!dirty.length)return;setBusy(true);setError("");try{const changes=dirty.map(file=>({path:file.path,expectedHash:file.hash,content:file.content})),action={repositoryId:id,changes},approvalId=await approval("repository.edit",action,{risk:"high",summary:`Write ${changes.length} reviewed repository file(s)`,files:changes.map(file=>file.path),diff:dirty.map(file=>`--- ${file.path}\n${file.original}\n+++ ${file.path}\n${file.content}`).join("\n")}),body=await json(`/api/v1/repositories/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({approvalId,changes})});setFiles(value=>value.map(file=>{const saved=body.files.find((item:OpenFile)=>item.path===file.path);return saved?{...saved,original:saved.content}:file}));await refreshGit()}catch(reason){setError(reason instanceof Error?reason.message:"Files could not be saved")}finally{setBusy(false)}}
  async function run(commandId:string){setBusy(true);setError("");try{const action={repositoryId:id,commandId},approvalId=await approval("repository.command",action,{risk:"high",summary:`Run allowlisted command: ${commandId}`,commands:[commandId]}),body=await json(`/api/v1/repositories/${id}/commands`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({approvalId,commandId})});setOutput(`${commandId} · exit ${body.exitCode}${body.truncated?" · truncated":""}\n${body.output||"(no output)"}`);await refreshGit()}catch(reason){setError(reason instanceof Error?reason.message:"Command failed")}finally{setBusy(false)}}
  async function gitAction(input:{action:"commit";message:string;paths:string[]}|{action:"revert";ref:string}){setBusy(true);setError("");try{const action={repositoryId:id,...input},approvalId=await approval(`repository.${input.action}`,action,{risk:input.action==="revert"?"critical":"high",summary:input.action==="commit"?`Commit ${input.paths.length} reviewed file(s)`: `Revert commit ${input.ref}`,commands:[input.action==="commit"?`git commit -m ${input.message}`:`git revert --no-edit ${input.ref}`],files:input.action==="commit"?input.paths:[],diff:git.diff});await json(`/api/v1/repositories/${id}/git`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...input,approvalId})});await refreshGit()}catch(reason){setError(reason instanceof Error?reason.message:"Git action failed")}finally{setBusy(false)}}
  async function commit(){const message=prompt("Commit message");if(message)await gitAction({action:"commit",message,paths:Array.from(new Set(git.status.split("\n").filter(Boolean).map(line=>line.slice(3))))})}
  const parent=useMemo(()=>path.split("/").slice(0,-1).join("/"),[path]);
  return <ModuleShell active="Coding" title={repo?.name||"Repository"} action={<Link className="secondary" href="/coding"><ArrowLeft/>Repositories</Link>}><div className="repo-workspace">
    <header className="repo-toolbar"><div><strong>{repo?.name}</strong><small>{repo?.path}</small></div><button className="primary" disabled={busy||!dirty.length} onClick={()=>void save()}><Check/>Save {dirty.length||""}</button><button className="secondary" disabled={busy||!git.status.trim()} onClick={()=>void commit()}><GitCommit/>Commit</button></header>
    {error&&<p className="auth-error" role="alert"><WarningCircle/>{error}</p>}
    <nav className="repo-crumbs" aria-label="Repository path"><button onClick={()=>void browse("")}>root</button>{crumbs.map((part,index)=><span key={`${part}-${index}`}><CaretRight/><button onClick={()=>void browse(crumbs.slice(0,index+1).join("/"))}>{part}</button></span>)}</nav>
    <div className="repo-main"><aside className="repo-tree" aria-label="Files">{path&&<button onClick={()=>void browse(parent)}><Folder/>..</button>}{entries.map(entry=><button key={entry.path} onClick={()=>void browse(entry.path)} disabled={entry.type==="other"}>{entry.type==="directory"?<Folder/>:<File/>}<span>{entry.name}</span><small>{entry.size??""}</small></button>)}</aside>
      <section className="repo-editor"><div className="repo-tabs" role="tablist">{files.map(file=><button role="tab" aria-selected={active===file.path} key={file.path} onClick={()=>setActive(file.path)}>{file.content!==file.original&&<i/>}{file.path.split("/").pop()}<X onClick={event=>{event.stopPropagation();setFiles(value=>value.filter(item=>item.path!==file.path));if(active===file.path)setActive("")}}/></button>)}</div>{current?<><label><span className="sr-only">Editing {current.path}</span><textarea ref={editor} spellCheck={false} value={current.content} onChange={event=>edit(event.target.value)} onKeyDown={event=>{if((event.ctrlKey||event.metaKey)&&event.key==="s"){event.preventDefault();void save()}}}/></label><div className="mobile-toolbar" aria-label="Mobile editor keys">{mobileKeys.map(key=><button key={key} onClick={()=>insert(key)}>{key}</button>)}</div></>:<div className="empty-state"><File/><h3>Open a text file</h3><p>Files up to 512 KiB can be edited.</p></div>}</section></div>
    <section className="repo-terminal"><header><Terminal/><strong>Isolated commands</strong>{["status","diff","test","typecheck","build"].map(command=><button key={command} disabled={busy} onClick={()=>void run(command)}><Play/>{command}</button>)}</header><pre aria-live="polite" tabIndex={0}><code>{output||"Select an allowlisted command. Each run requires approval."}</code></pre></section>
    <div className="repo-git"><section><h3><GitDiff/>Working-tree review</h3><pre tabIndex={0}><code>{git.status||"Working tree clean"}{git.diff&&`\n\n${git.diff}`}</code></pre></section><section><h3>History</h3>{git.history.map(item=><article key={item.ref}><code>{item.ref}</code><span><strong>{item.subject}</strong><small>{new Date(item.date).toLocaleString()}</small></span><button className="danger-link" disabled={busy} onClick={()=>void gitAction({action:"revert",ref:item.ref})}>Revert</button></article>)}</section></div>
    <p className="permission-note"><ShieldCheck/><span><strong>Repository isolation active</strong><small>Symlinks and traversal are rejected. Writes require matching hashes; commands have no network and stop after two minutes.</small></span></p>
  </div></ModuleShell>
}
