"use client";

import {createId} from "../lib/id";

import {useEffect,useState} from "react";
import {ArrowDown,ArrowLeft,ArrowRight,ArrowUp,Copy,FloppyDisk,PencilSimple,Plus,Trash,Warning} from "@phosphor-icons/react";
import {ModuleShell} from "../components/ModuleShell";

type Widget={id:string;type:string;title:string;x:number;y:number;w:number;h:number;config:Record<string,unknown>;data?:Record<string,unknown>[]};
type Dashboard={id:string;name:string;position:number;layout:Widget[];widgets?:Widget[];version:number};
const types=["tasks","events","notes","captures","projects","notifications","automations","study"];
const request=async(path:string,init?:RequestInit)=>{const response=await fetch(path,init),data=await response.json();if(!response.ok)throw new Error(data.error?.message||"Dashboard request failed");return data};
const label=(item:Record<string,unknown>)=>String(item.title||item.name||item.sourceLabel||item.course||"Untitled");
const detail=(item:Record<string,unknown>)=>String(item.project||item.status||item.due||item.startAt||item.kind||item.course||item.lastRunAt||"");
const overlaps=(a:Widget,b:Widget)=>a.id!==b.id&&a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;

export default function DashboardsPage(){
  const [dashboards,setDashboards]=useState<Dashboard[]>([]),[active,setActive]=useState<Dashboard|null>(null),[draft,setDraft]=useState<Dashboard|null>(null),[editing,setEditing]=useState(false),[creating,setCreating]=useState(false),[name,setName]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const load=async(select?:string)=>{setError("");try{const data=await request("/api/v1/dashboards"),items=data.dashboards as Dashboard[];setDashboards(items);const id=select||active?.id||items[0]?.id;if(id){const view=await request(`/api/v1/dashboards/${id}`);setActive(view);if(!editing)setDraft(view)}else{setActive(null);setDraft(null)}}catch(reason){setError((reason as Error).message)}};
  useEffect(()=>{void load()},[]);
  const select=async(id:string)=>{setEditing(false);setError("");try{const view=await request(`/api/v1/dashboards/${id}`);setActive(view);setDraft(view)}catch(reason){setError((reason as Error).message)}};
  const create=async()=>{if(!name.trim())return;setBusy(true);try{const created=await request("/api/v1/dashboards",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":createId()},body:JSON.stringify({name,layout:[]})});setCreating(false);setName("");await load(created.id);setEditing(true)}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const save=async()=>{if(!draft)return;setBusy(true);try{const saved=await request("/api/v1/dashboards",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":createId()},body:JSON.stringify({id:draft.id,version:draft.version,name:draft.name,layout:draft.layout})});setEditing(false);await load(saved.id)}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const duplicate=async()=>{if(!active)return;setBusy(true);try{const copy=await request(`/api/v1/dashboards/${active.id}`,{method:"POST"});await load(copy.id)}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const remove=async()=>{if(!active||!confirm(`Delete “${active.name}”?`))return;setBusy(true);try{await request(`/api/v1/dashboards/${active.id}?version=${active.version}`,{method:"DELETE"});setActive(null);await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const reorder=async(direction:-1|1)=>{if(!active)return;const index=dashboards.findIndex(item=>item.id===active.id),target=index+direction;if(target<0||target>=dashboards.length)return;const ids=dashboards.map(item=>item.id);[ids[index],ids[target]]=[ids[target],ids[index]];setBusy(true);try{const data=await request("/api/v1/dashboards/reorder",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids})});setDashboards(data.dashboards);await select(active.id)}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const change=(widget:Widget,next:Partial<Widget>)=>{if(!draft)return;const candidate={...widget,...next};if(candidate.x<0||candidate.y<0||candidate.w<2||candidate.h<1||candidate.x+candidate.w>12||candidate.h>12||draft.layout.some(item=>overlaps(candidate,item)))return;setDraft({...draft,layout:draft.layout.map(item=>item.id===widget.id?candidate:item)})};
  const add=(type:string)=>{if(!draft)return;const y=draft.layout.reduce((max,item)=>Math.max(max,item.y+item.h),0),widget={id:createId(),type,title:type[0].toUpperCase()+type.slice(1),x:0,y,w:6,h:2,config:{}};setDraft({...draft,layout:[...draft.layout,widget]})};
  const shown=editing?draft:active,widgets=shown?(editing?shown.layout:shown.widgets||[]):[];
  return <ModuleShell active="Dashboards" title="Dashboards" action={<button className="primary top-primary" onClick={()=>setCreating(true)}><Plus/>New dashboard</button>}>
    <div className="module-header"><div><h2>Your workspace, arranged your way</h2><p>Build responsive views from canonical Noema data. Layout changes never copy or fork source objects.</p></div></div>{error&&<div className="warning-text" role="alert"><Warning/>{error}</div>}
    {creating&&<form className="dashboard-create" onSubmit={event=>{event.preventDefault();void create()}}><label>Dashboard name<input autoFocus required maxLength={300} value={name} onChange={event=>setName(event.target.value)}/></label><button type="button" className="secondary" onClick={()=>setCreating(false)}>Cancel</button><button className="primary" disabled={busy}>Create</button></form>}
    <nav className="dashboard-tabs" aria-label="Custom dashboards">{dashboards.map(item=><button className={active?.id===item.id?"active":""} key={item.id} onClick={()=>void select(item.id)}>{item.name}</button>)}{active&&<><button className="icon-button" aria-label="Move dashboard left" disabled={dashboards[0]?.id===active.id||busy} onClick={()=>void reorder(-1)}><ArrowLeft/></button><button className="icon-button" aria-label="Move dashboard right" disabled={dashboards.at(-1)?.id===active.id||busy} onClick={()=>void reorder(1)}><ArrowRight/></button></>}</nav>
    {!shown?<div className="empty-state"><Plus/><h3>Create your first dashboard</h3><p>Combine tasks, calendar, notes, projects, notifications, automations, and study data.</p><button className="primary" onClick={()=>setCreating(true)}>Create dashboard</button></div>:<>
      <header className="dashboard-head">{editing?<label>Dashboard name<input value={draft!.name} onChange={event=>setDraft({...draft!,name:event.target.value})}/></label>:<div><h3>{active!.name}</h3><span>{widgets.length} widgets</span></div>}<div>{editing?<><button className="secondary" onClick={()=>{setDraft(active);setEditing(false)}}>Cancel</button><button className="primary" disabled={busy} onClick={()=>void save()}><FloppyDisk/>Save layout</button></>:<><button className="secondary" onClick={()=>{setDraft(active);setEditing(true)}}><PencilSimple/>Edit</button><button className="secondary" onClick={()=>void duplicate()}><Copy/>Duplicate</button><button className="danger-button" onClick={()=>void remove()}><Trash/>Delete</button></>}</div></header>
      {editing&&<section className="widget-catalog" aria-label="Widget catalog"><strong>Add widget</strong>{types.map(type=><button key={type} disabled={widgets.length>=20} onClick={()=>add(type)}><Plus/>{type}</button>)}</section>}
      <section className={`dashboard-grid ${editing?"editing":""}`} aria-label={`${shown.name} widgets`}>{widgets.map(widget=><article className="dashboard-widget" key={widget.id} style={{gridColumn:`${widget.x+1} / span ${widget.w}`,gridRow:`${widget.y+1} / span ${widget.h}`}}><header>{editing?<input aria-label={`${widget.title} title`} value={widget.title} onChange={event=>change(widget,{title:event.target.value})}/>:<strong>{widget.title}</strong>}<small>{widget.type}</small></header>{editing?<div className="widget-controls" aria-label={`${widget.title} layout controls`}><button aria-label={`Move ${widget.title} left`} onClick={()=>change(widget,{x:widget.x-1})}><ArrowLeft/></button><button aria-label={`Move ${widget.title} right`} onClick={()=>change(widget,{x:widget.x+1})}><ArrowRight/></button><button aria-label={`Move ${widget.title} up`} onClick={()=>change(widget,{y:widget.y-1})}><ArrowUp/></button><button aria-label={`Move ${widget.title} down`} onClick={()=>change(widget,{y:widget.y+1})}><ArrowDown/></button><button onClick={()=>change(widget,{w:widget.w-1})}>Narrower</button><button onClick={()=>change(widget,{w:widget.w+1})}>Wider</button><button onClick={()=>change(widget,{h:widget.h-1})}>Shorter</button><button onClick={()=>change(widget,{h:widget.h+1})}>Taller</button><button className="remove" onClick={()=>setDraft({...draft!,layout:draft!.layout.filter(item=>item.id!==widget.id)})}><Trash/>Remove</button></div>:widget.data?.length?<ul>{widget.data.map((item,index)=><li key={String(item.id||index)}><strong>{label(item)}</strong><small>{detail(item)}</small></li>)}</ul>:<div className="widget-empty">No {widget.type} yet.</div>}</article>)}{!widgets.length&&<div className="dashboard-empty"><Plus/><strong>{editing?"Add a widget to begin":"This dashboard is empty"}</strong><span>{editing?"Choose from the catalog above.":"Edit the dashboard to add canonical workspace data."}</span></div>}</section>
    </>}
  </ModuleShell>;
}
